/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Вход или привязка через Google
         * @description Без bearer-токена: вход в привязанный аккаунт или создание нового защищённого аккаунта. С bearer-токеном: привязка Google к текущему аккаунту.
         */
        post: operations["auth-google"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Вход по email и паролю (защищённый аккаунт) */
        post: operations["auth-login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Выход (отозвать refresh-токен) */
        post: operations["auth-logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Обновить токены
         * @description Refresh-токен одноразовый: выдаётся новая пара, старый отзывается. Повторное использование отзывает все сессии пользователя.
         */
        post: operations["auth-refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Регистрация по имени
         * @description Создаёт лёгкий аккаунт (уровень L1). Email и пароль не нужны; их можно добавить позже через /me/credentials.
         */
        post: operations["auth-register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать группу */
        post: operations["groups-create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/join/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Что за группа стоит за кодом
         * @description Без аутентификации — для экрана «Вступить в группу?».
         */
        get: operations["groups-preview"];
        put?: never;
        /** Вступить по коду приглашения или коду группы */
        post: operations["groups-join"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Группа и моё членство */
        get: operations["groups-get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Настройки группы */
        patch: operations["groups-update"];
        trace?: never;
    };
    "/groups/{groupId}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Лента активности (кто что когда) */
        get: operations["activity-list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupId}/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Активные приглашения */
        get: operations["invites-list"];
        put?: never;
        /** Создать приглашение */
        post: operations["invites-create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupId}/invites/{inviteId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Отозвать приглашение */
        delete: operations["invites-revoke"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupId}/join-code/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Сменить код группы */
        post: operations["groups-rotate-join-code"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Участники группы */
        get: operations["groups-members"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupId}/members/{userId}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Назначить роли участнику */
        put: operations["groups-member-roles"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupId}/members/{userId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Заблокировать или восстановить участника */
        put: operations["groups-member-status"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupId}/quick-tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Быстрые теги для главного экрана
         * @description Системные фильтры («Мои», «Сохранённое», «Непрочитанное») и активные предметы в порядке сортировки.
         */
        get: operations["tags-quick"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupId}/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Предметы группы */
        get: operations["subjects-list"];
        put?: never;
        /**
         * Добавить предмет
         * @description Вместе с предметом создаётся его тег (kind=SUBJECT) и тред обсуждения (со 2-го этапа).
         */
        post: operations["subjects-create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupId}/subjects/{subjectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Предмет */
        get: operations["subjects-get"];
        /** Изменить предмет */
        put: operations["subjects-update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupId}/subjects/{subjectId}/aliases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Добавить синонимы предмета */
        post: operations["subjects-add-aliases"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupId}/subjects/{subjectId}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Архивировать предмет */
        post: operations["subjects-archive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupId}/subjects/{subjectId}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Восстановить предмет */
        post: operations["subjects-restore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupId}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Дельта-синхронизация журнала группы
         * @description Возвращает события с seq > since. 410 Gone — история за курсором уже удалена: клиент должен перезагрузить данные с нуля.
         */
        get: operations["sync-since"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupId}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Теги группы */
        get: operations["tags-list"];
        put?: never;
        /** Создать тег */
        post: operations["tags-create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupId}/tags/{tagId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Изменить тег */
        put: operations["tags-update"];
        post?: never;
        /** Удалить тег */
        delete: operations["tags-delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Текущий пользователь */
        get: operations["me-get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Обновить профиль */
        patch: operations["me-update"];
        trace?: never;
    };
    "/me/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Защитить аккаунт: задать email и/или пароль
         * @description Переводит аккаунт на уровень L2 — вход с других устройств, восстановление, роли админа/модератора/старосты.
         */
        post: operations["me-set-credentials"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Устройства пользователя */
        get: operations["me-devices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/devices/{deviceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить устройство */
        delete: operations["me-device-delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/devices/{deviceId}/push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Зарегистрировать push-токен устройства */
        put: operations["me-device-push"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Мои группы */
        get: operations["me-groups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Завершить все сессии */
        post: operations["me-logout-all"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ActivityOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/ActivityOutputBody.json
             */
            readonly $schema?: string;
            items: components["schemas"]["EventDTO"][] | null;
        };
        AliasesInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/AliasesInputBody.json
             */
            readonly $schema?: string;
            aliases: string[] | null;
        };
        CreateGroupInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/CreateGroupInputBody.json
             */
            readonly $schema?: string;
            /**
             * @description По умолчанию MASTERS. DPO — отдельный поток с выключенными по умолчанию уведомлениями.
             * @enum {string}
             */
            kind?: "MASTERS" | "DPO" | "OTHER";
            name: string;
        };
        CreateInviteInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/CreateInviteInputBody.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description 0 — бессрочно.
             */
            expires_days?: number;
            /** Format: int32 */
            max_uses?: number;
            /** @description Роли приглашённого; по умолчанию STUDENT. */
            roles?: string[] | null;
        };
        CredentialsInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/CredentialsInputBody.json
             */
            readonly $schema?: string;
            /** Format: email */
            email?: string;
            password?: string;
        };
        DeviceDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/DeviceDTO.json
             */
            readonly $schema?: string;
            /** Format: date-time */
            created_at: string;
            id: string;
            /** Format: date-time */
            last_seen_at: string;
            name?: string;
            /** @enum {string} */
            platform: "IOS" | "ANDROID" | "WEB";
            push_enabled: boolean;
            push_provider?: string;
        };
        DevicesOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/DevicesOutputBody.json
             */
            readonly $schema?: string;
            items: components["schemas"]["DeviceDTO"][] | null;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        EventDTO: {
            actor_id?: string;
            /** Format: date-time */
            created_at: string;
            entity_id?: string;
            entity_type: string;
            group_id: string;
            id: string;
            kind: string;
            payload: unknown;
            /** Format: int64 */
            seq: number;
        };
        GoogleInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/GoogleInputBody.json
             */
            readonly $schema?: string;
            device_name?: string;
            id_token: string;
            /**
             * @description Платформа клиента; по умолчанию WEB.
             * @enum {string}
             */
            platform?: "IOS" | "ANDROID" | "WEB";
        };
        GroupDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/GroupDTO.json
             */
            readonly $schema?: string;
            /** Format: date-time */
            archived_at?: string;
            /** Format: date-time */
            created_at: string;
            id: string;
            /** @description Постоянный код для вступления (политика OPEN). */
            join_code?: string;
            /** @enum {string} */
            join_policy: "OPEN" | "INVITE" | "APPROVAL";
            /** @enum {string} */
            kind: "MASTERS" | "DPO" | "OTHER";
            /**
             * Format: int64
             * @description Последний seq журнала событий группы.
             */
            last_seq: number;
            /** @enum {string} */
            media_mode: "LINK" | "CACHE" | "IMPORT";
            name: string;
            public_read: boolean;
            settings: unknown;
            slug: string;
        };
        GroupWithMembershipDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/GroupWithMembershipDTO.json
             */
            readonly $schema?: string;
            group: components["schemas"]["GroupDTO"];
            membership: components["schemas"]["MembershipDTO"];
        };
        GroupsListOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/GroupsListOutputBody.json
             */
            readonly $schema?: string;
            items: components["schemas"]["GroupWithMembershipDTO"][] | null;
        };
        InviteDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/InviteDTO.json
             */
            readonly $schema?: string;
            code: string;
            /** Format: date-time */
            created_at: string;
            created_by: string;
            /** Format: date-time */
            expires_at?: string;
            group_id: string;
            id: string;
            /** Format: int32 */
            max_uses?: number;
            /** Format: date-time */
            revoked_at?: string;
            roles: string[] | null;
            /** Format: int32 */
            uses: number;
        };
        InvitesOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/InvitesOutputBody.json
             */
            readonly $schema?: string;
            items: components["schemas"]["InviteDTO"][] | null;
        };
        LoginInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/LoginInputBody.json
             */
            readonly $schema?: string;
            device_name?: string;
            /** Format: email */
            email: string;
            password: string;
            /**
             * @description Платформа клиента; по умолчанию WEB.
             * @enum {string}
             */
            platform?: "IOS" | "ANDROID" | "WEB";
        };
        MemberDTO: {
            membership: components["schemas"]["MembershipDTO"];
            user: components["schemas"]["PublicUserDTO"];
        };
        MemberRolesInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/MemberRolesInputBody.json
             */
            readonly $schema?: string;
            /** @description Полный набор ролей участника. */
            roles: string[] | null;
        };
        MemberStatusInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/MemberStatusInputBody.json
             */
            readonly $schema?: string;
            /** @enum {string} */
            status: "ACTIVE" | "BANNED";
        };
        MembersOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/MembersOutputBody.json
             */
            readonly $schema?: string;
            /** @description true — ответ содержит расширенные поля пользователей (админ). */
            extended: boolean;
            items: components["schemas"]["MemberDTO"][] | null;
        };
        MembershipDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/MembershipDTO.json
             */
            readonly $schema?: string;
            group_id: string;
            id: string;
            /** Format: date-time */
            joined_at: string;
            joined_via: string;
            /** @description Действия, доступные этому участнику (только для собственного членства). */
            permissions?: string[] | null;
            roles: string[] | null;
            /** @enum {string} */
            status: "ACTIVE" | "PENDING" | "BANNED";
            user_id: string;
        };
        PreviewOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/PreviewOutputBody.json
             */
            readonly $schema?: string;
            group: components["schemas"]["GroupDTO"];
            /** Format: int64 */
            member_count: number;
            roles: string[] | null;
            via_invite: boolean;
        };
        PublicUserDTO: {
            avatar_key?: string;
            /** Format: date-time */
            created_at?: string;
            email?: string;
            id: string;
            name: string;
            secured?: boolean;
        };
        PushInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/PushInputBody.json
             */
            readonly $schema?: string;
            /** @enum {string} */
            provider: "EXPO" | "WEBPUSH";
            /** @description Web Push subscription JSON. */
            subscription?: unknown;
            /** @description Expo push token. */
            token?: string;
        };
        QuickTagDTO: {
            color?: string;
            /** @description Стабильный ключ: system:<name> или subject:<id>. */
            key: string;
            kind: string;
            /** @description Для system — ключ i18n, для предметов — название. */
            label: string;
            /** Format: int64 */
            order: number;
            subject_id?: string;
            tag_id?: string;
        };
        QuickTagsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/QuickTagsOutputBody.json
             */
            readonly $schema?: string;
            items: components["schemas"]["QuickTagDTO"][] | null;
        };
        RefreshInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/RefreshInputBody.json
             */
            readonly $schema?: string;
            refresh_token: string;
        };
        RegisterInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/RegisterInputBody.json
             */
            readonly $schema?: string;
            device_name?: string;
            /** @description Код приглашения или код группы — сразу вступить. */
            invite_code?: string;
            locale?: string;
            /** @description Имя — единственное обязательное поле. */
            name: string;
            /**
             * @description Платформа клиента; по умолчанию WEB.
             * @enum {string}
             */
            platform?: "IOS" | "ANDROID" | "WEB";
            timezone?: string;
        };
        SessionDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/SessionDTO.json
             */
            readonly $schema?: string;
            /** Format: date-time */
            access_expires_at: string;
            access_token: string;
            device_id: string;
            /** @description Группа, к которой присоединились по коду при регистрации. */
            joined?: components["schemas"]["GroupWithMembershipDTO"];
            refresh_token: string;
            user: components["schemas"]["UserDTO"];
        };
        SubjectBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/SubjectBody.json
             */
            readonly $schema?: string;
            /** @description Синонимы для классификатора файлов с Диска. */
            aliases?: string[] | null;
            /** @description Цвет чипа, например #3B82F6. */
            color?: string;
            name: string;
            semester?: string;
            short_name?: string;
            /** Format: int32 */
            sort_order?: number;
            teacher?: string;
            teacher_contact?: string;
        };
        SubjectDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/SubjectDTO.json
             */
            readonly $schema?: string;
            aliases: string[] | null;
            /** Format: date-time */
            archived_at?: string;
            color?: string;
            /** Format: date-time */
            created_at: string;
            group_id: string;
            id: string;
            name: string;
            semester?: string;
            short_name?: string;
            /** Format: int32 */
            sort_order: number;
            teacher?: string;
            teacher_contact?: string;
            /** Format: date-time */
            updated_at: string;
        };
        SubjectsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/SubjectsOutputBody.json
             */
            readonly $schema?: string;
            items: components["schemas"]["SubjectDTO"][] | null;
        };
        SyncOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/SyncOutputBody.json
             */
            readonly $schema?: string;
            events: components["schemas"]["EventDTO"][] | null;
            has_more: boolean;
            /**
             * Format: int64
             * @description Последний seq группы на момент ответа.
             */
            latest: number;
            /**
             * Format: int64
             * @description Курсор для следующего вызова.
             */
            next_seq: number;
        };
        TagBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/TagBody.json
             */
            readonly $schema?: string;
            color?: string;
            /**
             * @description По умолчанию CUSTOM.
             * @enum {string}
             */
            kind?: "TOPIC" | "TYPE" | "CUSTOM";
            name: string;
        };
        TagDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/TagDTO.json
             */
            readonly $schema?: string;
            color?: string;
            /** Format: date-time */
            created_at: string;
            group_id: string;
            id: string;
            /** @enum {string} */
            kind: "SUBJECT" | "TOPIC" | "TYPE" | "SYSTEM" | "CUSTOM";
            name: string;
            slug: string;
            subject_id?: string;
        };
        TagsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/TagsOutputBody.json
             */
            readonly $schema?: string;
            items: components["schemas"]["TagDTO"][] | null;
        };
        UpdateGroupInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/UpdateGroupInputBody.json
             */
            readonly $schema?: string;
            /** @enum {string} */
            join_policy?: "OPEN" | "INVITE";
            /** @enum {string} */
            kind?: "MASTERS" | "DPO" | "OTHER";
            /** @enum {string} */
            media_mode?: "LINK" | "CACHE" | "IMPORT";
            name?: string;
            public_read?: boolean;
            settings?: unknown;
        };
        UpdateProfileInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/UpdateProfileInputBody.json
             */
            readonly $schema?: string;
            locale?: string;
            name?: string;
            /** @description Произвольные настройки клиента (набор быстрых тегов и т.п.). */
            settings?: unknown;
            timezone?: string;
        };
        UserDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/UserDTO.json
             */
            readonly $schema?: string;
            avatar_key?: string;
            /** Format: date-time */
            created_at: string;
            email?: string;
            /** @enum {string} */
            global_role: "USER" | "SUPERADMIN";
            has_password: boolean;
            id: string;
            locale: string;
            name: string;
            /** @description Аккаунт защищён паролем/email/Google (уровень L2). */
            secured: boolean;
            settings: unknown;
            timezone: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "auth-google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "auth-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "auth-logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshInputBody"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "auth-refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "auth-register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "groups-create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGroupInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupWithMembershipDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "groups-preview": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "groups-join": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupWithMembershipDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "groups-get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupWithMembershipDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "groups-update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGroupInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "activity-list": {
        parameters: {
            query?: {
                /** @description Вернуть события с seq меньше этого; 0 — с самых новых. */
                before?: number;
                limit?: number;
            };
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "invites-list": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitesOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "invites-create": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInviteInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "invites-revoke": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
                inviteId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "groups-rotate-join-code": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "groups-members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembersOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "groups-member-roles": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberRolesInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "groups-member-status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberStatusInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "tags-quick": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuickTagsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "subjects-list": {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "subjects-create": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubjectBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "subjects-get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
                subjectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "subjects-update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
                subjectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubjectBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "subjects-add-aliases": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
                subjectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AliasesInputBody"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "subjects-archive": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
                subjectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "subjects-restore": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
                subjectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "sync-since": {
        parameters: {
            query?: {
                /** @description Последний полученный seq; 0 — с начала. */
                since?: number;
                limit?: number;
            };
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "tags-list": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "tags-create": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "tags-update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
                tagId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "tags-delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
                tagId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "me-get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "me-update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "me-set-credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialsInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "me-devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevicesOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "me-device-delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "me-device-push": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "me-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupsListOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "me-logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
