// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: announcements.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createAnnouncement = `-- name: CreateAnnouncement :one
INSERT INTO announcements (id, group_id, author_id, title, body, urgent, pinned)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, group_id, author_id, title, body, urgent, pinned, created_at, updated_at, deleted_at
`

type CreateAnnouncementParams struct {
	ID       uuid.UUID
	GroupID  uuid.UUID
	AuthorID *uuid.UUID
	Title    string
	Body     string
	Urgent   bool
	Pinned   bool
}

func (q *Queries) CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, createAnnouncement,
		arg.ID,
		arg.GroupID,
		arg.AuthorID,
		arg.Title,
		arg.Body,
		arg.Urgent,
		arg.Pinned,
	)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.AuthorID,
		&i.Title,
		&i.Body,
		&i.Urgent,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteAnnouncement = `-- name: DeleteAnnouncement :execrows
UPDATE announcements SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteAnnouncement(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAnnouncement, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAnnouncement = `-- name: GetAnnouncement :one
SELECT id, group_id, author_id, title, body, urgent, pinned, created_at, updated_at, deleted_at FROM announcements WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAnnouncement(ctx context.Context, id uuid.UUID) (Announcement, error) {
	row := q.db.QueryRow(ctx, getAnnouncement, id)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.AuthorID,
		&i.Title,
		&i.Body,
		&i.Urgent,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAnnouncements = `-- name: ListAnnouncements :many
SELECT a.id, a.group_id, a.author_id, a.title, a.body, a.urgent, a.pinned, a.created_at, a.updated_at, a.deleted_at, COALESCE(u.name, '')::text AS author_name
FROM announcements a
LEFT JOIN users u ON u.id = a.author_id
WHERE a.group_id = $1::uuid AND a.deleted_at IS NULL
ORDER BY a.pinned DESC, a.created_at DESC
LIMIT $2::int
`

type ListAnnouncementsParams struct {
	GroupID uuid.UUID
	Lim     int32
}

type ListAnnouncementsRow struct {
	Announcement Announcement
	AuthorName   string
}

// Pinned first, then newest; a page is small, so a limit is enough.
func (q *Queries) ListAnnouncements(ctx context.Context, arg ListAnnouncementsParams) ([]ListAnnouncementsRow, error) {
	rows, err := q.db.Query(ctx, listAnnouncements, arg.GroupID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnnouncementsRow{}
	for rows.Next() {
		var i ListAnnouncementsRow
		if err := rows.Scan(
			&i.Announcement.ID,
			&i.Announcement.GroupID,
			&i.Announcement.AuthorID,
			&i.Announcement.Title,
			&i.Announcement.Body,
			&i.Announcement.Urgent,
			&i.Announcement.Pinned,
			&i.Announcement.CreatedAt,
			&i.Announcement.UpdatedAt,
			&i.Announcement.DeletedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnnouncement = `-- name: UpdateAnnouncement :one
UPDATE announcements
SET title = $1, body = $2, urgent = $3, pinned = $4
WHERE id = $5 AND deleted_at IS NULL
RETURNING id, group_id, author_id, title, body, urgent, pinned, created_at, updated_at, deleted_at
`

type UpdateAnnouncementParams struct {
	Title  string
	Body   string
	Urgent bool
	Pinned bool
	ID     uuid.UUID
}

func (q *Queries) UpdateAnnouncement(ctx context.Context, arg UpdateAnnouncementParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, updateAnnouncement,
		arg.Title,
		arg.Body,
		arg.Urgent,
		arg.Pinned,
		arg.ID,
	)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.AuthorID,
		&i.Title,
		&i.Body,
		&i.Urgent,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
