// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (id, user_id, platform, name)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, platform, name, push_provider, push_token, push_subscription, enabled, last_seen_at, created_at, updated_at
`

type CreateDeviceParams struct {
	ID       uuid.UUID
	UserID   uuid.UUID
	Platform string
	Name     *string
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.ID,
		arg.UserID,
		arg.Platform,
		arg.Name,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.Name,
		&i.PushProvider,
		&i.PushToken,
		&i.PushSubscription,
		&i.Enabled,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createIdentity = `-- name: CreateIdentity :one
INSERT INTO auth_identities (id, user_id, provider, provider_user_id, email)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, provider, provider_user_id, email, refresh_token_enc, created_at, updated_at
`

type CreateIdentityParams struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Provider       string
	ProviderUserID string
	Email          *string
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, createIdentity,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.Email,
	)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.RefreshTokenEnc,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (id, user_id, device_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, device_id, token_hash, expires_at, revoked_at, replaced_by, created_at
`

type CreateRefreshTokenParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	DeviceID  *uuid.UUID
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.ID,
		arg.UserID,
		arg.DeviceID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDevice = `-- name: DeleteDevice :exec
DELETE FROM devices WHERE id = $1 AND user_id = $2
`

type DeleteDeviceParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteDevice(ctx context.Context, arg DeleteDeviceParams) error {
	_, err := q.db.Exec(ctx, deleteDevice, arg.ID, arg.UserID)
	return err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :execrows
DELETE FROM refresh_tokens WHERE expires_at < now() - interval '7 days'
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredRefreshTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const disableDevicePush = `-- name: DisableDevicePush :exec
UPDATE devices SET enabled = false WHERE id = $1
`

func (q *Queries) DisableDevicePush(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, disableDevicePush, id)
	return err
}

const getDevice = `-- name: GetDevice :one
SELECT id, user_id, platform, name, push_provider, push_token, push_subscription, enabled, last_seen_at, created_at, updated_at FROM devices WHERE id = $1 AND user_id = $2
`

type GetDeviceParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetDevice(ctx context.Context, arg GetDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, getDevice, arg.ID, arg.UserID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.Name,
		&i.PushProvider,
		&i.PushToken,
		&i.PushSubscription,
		&i.Enabled,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIdentityByProvider = `-- name: GetIdentityByProvider :one
SELECT id, user_id, provider, provider_user_id, email, refresh_token_enc, created_at, updated_at FROM auth_identities WHERE provider = $1 AND provider_user_id = $2
`

type GetIdentityByProviderParams struct {
	Provider       string
	ProviderUserID string
}

func (q *Queries) GetIdentityByProvider(ctx context.Context, arg GetIdentityByProviderParams) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, getIdentityByProvider, arg.Provider, arg.ProviderUserID)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.RefreshTokenEnc,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, device_id, token_hash, expires_at, revoked_at, replaced_by, created_at FROM refresh_tokens WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listDevicesByUser = `-- name: ListDevicesByUser :many
SELECT id, user_id, platform, name, push_provider, push_token, push_subscription, enabled, last_seen_at, created_at, updated_at FROM devices WHERE user_id = $1 ORDER BY last_seen_at DESC
`

func (q *Queries) ListDevicesByUser(ctx context.Context, userID uuid.UUID) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevicesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Platform,
			&i.Name,
			&i.PushProvider,
			&i.PushToken,
			&i.PushSubscription,
			&i.Enabled,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdentitiesByUser = `-- name: ListIdentitiesByUser :many
SELECT id, user_id, provider, provider_user_id, email, refresh_token_enc, created_at, updated_at FROM auth_identities WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ListIdentitiesByUser(ctx context.Context, userID uuid.UUID) ([]AuthIdentity, error) {
	rows, err := q.db.Query(ctx, listIdentitiesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthIdentity{}
	for rows.Next() {
		var i AuthIdentity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderUserID,
			&i.Email,
			&i.RefreshTokenEnc,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
UPDATE refresh_tokens SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked_at = now(), replaced_by = $2
WHERE id = $1 AND revoked_at IS NULL
`

type RevokeRefreshTokenParams struct {
	ID         uuid.UUID
	ReplacedBy *uuid.UUID
}

func (q *Queries) RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, arg.ID, arg.ReplacedBy)
	return err
}

const touchDevice = `-- name: TouchDevice :exec
UPDATE devices SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) TouchDevice(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchDevice, id)
	return err
}

const updateDevicePush = `-- name: UpdateDevicePush :one
UPDATE devices
SET push_provider = $3, push_token = $4, push_subscription = $5, enabled = true
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, platform, name, push_provider, push_token, push_subscription, enabled, last_seen_at, created_at, updated_at
`

type UpdateDevicePushParams struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	PushProvider     *string
	PushToken        *string
	PushSubscription []byte
}

func (q *Queries) UpdateDevicePush(ctx context.Context, arg UpdateDevicePushParams) (Device, error) {
	row := q.db.QueryRow(ctx, updateDevicePush,
		arg.ID,
		arg.UserID,
		arg.PushProvider,
		arg.PushToken,
		arg.PushSubscription,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.Name,
		&i.PushProvider,
		&i.PushToken,
		&i.PushSubscription,
		&i.Enabled,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
