// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: discussions.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const adjustThreadMessageCount = `-- name: AdjustThreadMessageCount :exec
UPDATE threads SET message_count = GREATEST(message_count + $1::int, 0) WHERE id = $2
`

type AdjustThreadMessageCountParams struct {
	Delta int32
	ID    uuid.UUID
}

func (q *Queries) AdjustThreadMessageCount(ctx context.Context, arg AdjustThreadMessageCountParams) error {
	_, err := q.db.Exec(ctx, adjustThreadMessageCount, arg.Delta, arg.ID)
	return err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (id, group_id, thread_id, author_id, client_id, seq, body, reply_to_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, group_id, thread_id, author_id, client_id, seq, body, reply_to_id, edited_at, deleted_at, hidden_for_all_by, hidden_for_all_at, created_at, updated_at
`

type CreateMessageParams struct {
	ID        uuid.UUID
	GroupID   uuid.UUID
	ThreadID  uuid.UUID
	AuthorID  *uuid.UUID
	ClientID  uuid.UUID
	Seq       int64
	Body      string
	ReplyToID *uuid.UUID
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ID,
		arg.GroupID,
		arg.ThreadID,
		arg.AuthorID,
		arg.ClientID,
		arg.Seq,
		arg.Body,
		arg.ReplyToID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.ThreadID,
		&i.AuthorID,
		&i.ClientID,
		&i.Seq,
		&i.Body,
		&i.ReplyToID,
		&i.EditedAt,
		&i.DeletedAt,
		&i.HiddenForAllBy,
		&i.HiddenForAllAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const editMessage = `-- name: EditMessage :one
UPDATE messages SET body = $2, edited_at = $3 WHERE id = $1 RETURNING id, group_id, thread_id, author_id, client_id, seq, body, reply_to_id, edited_at, deleted_at, hidden_for_all_by, hidden_for_all_at, created_at, updated_at
`

type EditMessageParams struct {
	ID       uuid.UUID
	Body     string
	EditedAt *time.Time
}

func (q *Queries) EditMessage(ctx context.Context, arg EditMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, editMessage, arg.ID, arg.Body, arg.EditedAt)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.ThreadID,
		&i.AuthorID,
		&i.ClientID,
		&i.Seq,
		&i.Body,
		&i.ReplyToID,
		&i.EditedAt,
		&i.DeletedAt,
		&i.HiddenForAllBy,
		&i.HiddenForAllAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensureThread = `-- name: EnsureThread :one
INSERT INTO threads (id, group_id, target_type, target_id, subject_id, title, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (group_id, target_type, target_id) DO UPDATE SET target_id = EXCLUDED.target_id
RETURNING id, group_id, target_type, target_id, subject_id, title, created_by, message_count, last_message_at, last_seq, created_at, updated_at
`

type EnsureThreadParams struct {
	ID         uuid.UUID
	GroupID    uuid.UUID
	TargetType string
	TargetID   uuid.UUID
	SubjectID  *uuid.UUID
	Title      *string
	CreatedBy  *uuid.UUID
}

// The no-op update makes RETURNING yield the existing row on conflict.
func (q *Queries) EnsureThread(ctx context.Context, arg EnsureThreadParams) (Thread, error) {
	row := q.db.QueryRow(ctx, ensureThread,
		arg.ID,
		arg.GroupID,
		arg.TargetType,
		arg.TargetID,
		arg.SubjectID,
		arg.Title,
		arg.CreatedBy,
	)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.TargetType,
		&i.TargetID,
		&i.SubjectID,
		&i.Title,
		&i.CreatedBy,
		&i.MessageCount,
		&i.LastMessageAt,
		&i.LastSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMessage = `-- name: GetMessage :one
SELECT id, group_id, thread_id, author_id, client_id, seq, body, reply_to_id, edited_at, deleted_at, hidden_for_all_by, hidden_for_all_at, created_at, updated_at FROM messages WHERE id = $1
`

func (q *Queries) GetMessage(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.ThreadID,
		&i.AuthorID,
		&i.ClientID,
		&i.Seq,
		&i.Body,
		&i.ReplyToID,
		&i.EditedAt,
		&i.DeletedAt,
		&i.HiddenForAllBy,
		&i.HiddenForAllAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMessageByClientID = `-- name: GetMessageByClientID :one
SELECT id, group_id, thread_id, author_id, client_id, seq, body, reply_to_id, edited_at, deleted_at, hidden_for_all_by, hidden_for_all_at, created_at, updated_at FROM messages WHERE thread_id = $1 AND client_id = $2
`

type GetMessageByClientIDParams struct {
	ThreadID uuid.UUID
	ClientID uuid.UUID
}

func (q *Queries) GetMessageByClientID(ctx context.Context, arg GetMessageByClientIDParams) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByClientID, arg.ThreadID, arg.ClientID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.ThreadID,
		&i.AuthorID,
		&i.ClientID,
		&i.Seq,
		&i.Body,
		&i.ReplyToID,
		&i.EditedAt,
		&i.DeletedAt,
		&i.HiddenForAllBy,
		&i.HiddenForAllAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMessageView = `-- name: GetMessageView :one
SELECT m.id, m.group_id, m.thread_id, m.author_id, m.client_id, m.seq, m.body, m.reply_to_id, m.edited_at, m.deleted_at, m.hidden_for_all_by, m.hidden_for_all_at, m.created_at, m.updated_at,
       COALESCE(u.name, '')::text AS author_name,
       EXISTS (SELECT 1 FROM message_hides h WHERE h.message_id = m.id AND h.user_id = $1::uuid) AS hidden_by_me,
       rm.id AS reply_id,
       rm.author_id AS reply_author_id,
       COALESCE(ru.name, '')::text AS reply_author_name,
       COALESCE(left(rm.body, 200), '')::text AS reply_body,
       (rm.deleted_at IS NOT NULL)::boolean AS reply_deleted,
       (rm.hidden_for_all_at IS NOT NULL)::boolean AS reply_hidden_for_all
FROM messages m
LEFT JOIN users u ON u.id = m.author_id
LEFT JOIN messages rm ON rm.id = m.reply_to_id
LEFT JOIN users ru ON ru.id = rm.author_id
WHERE m.id = $2::uuid
`

type GetMessageViewParams struct {
	ViewerID uuid.UUID
	ID       uuid.UUID
}

type GetMessageViewRow struct {
	Message           Message
	AuthorName        string
	HiddenByMe        bool
	ReplyID           *uuid.UUID
	ReplyAuthorID     *uuid.UUID
	ReplyAuthorName   string
	ReplyBody         string
	ReplyDeleted      bool
	ReplyHiddenForAll bool
}

func (q *Queries) GetMessageView(ctx context.Context, arg GetMessageViewParams) (GetMessageViewRow, error) {
	row := q.db.QueryRow(ctx, getMessageView, arg.ViewerID, arg.ID)
	var i GetMessageViewRow
	err := row.Scan(
		&i.Message.ID,
		&i.Message.GroupID,
		&i.Message.ThreadID,
		&i.Message.AuthorID,
		&i.Message.ClientID,
		&i.Message.Seq,
		&i.Message.Body,
		&i.Message.ReplyToID,
		&i.Message.EditedAt,
		&i.Message.DeletedAt,
		&i.Message.HiddenForAllBy,
		&i.Message.HiddenForAllAt,
		&i.Message.CreatedAt,
		&i.Message.UpdatedAt,
		&i.AuthorName,
		&i.HiddenByMe,
		&i.ReplyID,
		&i.ReplyAuthorID,
		&i.ReplyAuthorName,
		&i.ReplyBody,
		&i.ReplyDeleted,
		&i.ReplyHiddenForAll,
	)
	return i, err
}

const getThread = `-- name: GetThread :one
SELECT id, group_id, target_type, target_id, subject_id, title, created_by, message_count, last_message_at, last_seq, created_at, updated_at FROM threads WHERE id = $1
`

func (q *Queries) GetThread(ctx context.Context, id uuid.UUID) (Thread, error) {
	row := q.db.QueryRow(ctx, getThread, id)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.TargetType,
		&i.TargetID,
		&i.SubjectID,
		&i.Title,
		&i.CreatedBy,
		&i.MessageCount,
		&i.LastMessageAt,
		&i.LastSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getThreadByTarget = `-- name: GetThreadByTarget :one
SELECT id, group_id, target_type, target_id, subject_id, title, created_by, message_count, last_message_at, last_seq, created_at, updated_at FROM threads WHERE group_id = $1 AND target_type = $2 AND target_id = $3
`

type GetThreadByTargetParams struct {
	GroupID    uuid.UUID
	TargetType string
	TargetID   uuid.UUID
}

func (q *Queries) GetThreadByTarget(ctx context.Context, arg GetThreadByTargetParams) (Thread, error) {
	row := q.db.QueryRow(ctx, getThreadByTarget, arg.GroupID, arg.TargetType, arg.TargetID)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.TargetType,
		&i.TargetID,
		&i.SubjectID,
		&i.Title,
		&i.CreatedBy,
		&i.MessageCount,
		&i.LastMessageAt,
		&i.LastSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getThreadReadSeq = `-- name: GetThreadReadSeq :one
SELECT COALESCE((SELECT last_read_seq FROM thread_reads WHERE thread_id = $1 AND user_id = $2), 0)::bigint
`

type GetThreadReadSeqParams struct {
	ThreadID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) GetThreadReadSeq(ctx context.Context, arg GetThreadReadSeqParams) (int64, error) {
	row := q.db.QueryRow(ctx, getThreadReadSeq, arg.ThreadID, arg.UserID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const hideMessage = `-- name: HideMessage :exec
INSERT INTO message_hides (message_id, user_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type HideMessageParams struct {
	MessageID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) HideMessage(ctx context.Context, arg HideMessageParams) error {
	_, err := q.db.Exec(ctx, hideMessage, arg.MessageID, arg.UserID)
	return err
}

const listHiddenByUser = `-- name: ListHiddenByUser :many
SELECT m.id, m.group_id, m.thread_id, m.author_id, m.client_id, m.seq, m.body, m.reply_to_id, m.edited_at, m.deleted_at, m.hidden_for_all_by, m.hidden_for_all_at, m.created_at, m.updated_at,
       t.id, t.group_id, t.target_type, t.target_id, t.subject_id, t.title, t.created_by, t.message_count, t.last_message_at, t.last_seq, t.created_at, t.updated_at,
       COALESCE(u.name, '')::text AS author_name
FROM message_hides h
JOIN messages m ON m.id = h.message_id
JOIN threads t ON t.id = m.thread_id
LEFT JOIN users u ON u.id = m.author_id
WHERE h.user_id = $1::uuid AND m.group_id = $2::uuid AND m.deleted_at IS NULL
ORDER BY h.created_at DESC, m.id
LIMIT $3
`

type ListHiddenByUserParams struct {
	UserID  uuid.UUID
	GroupID uuid.UUID
	MaxRows int32
}

type ListHiddenByUserRow struct {
	Message    Message
	Thread     Thread
	AuthorName string
}

func (q *Queries) ListHiddenByUser(ctx context.Context, arg ListHiddenByUserParams) ([]ListHiddenByUserRow, error) {
	rows, err := q.db.Query(ctx, listHiddenByUser, arg.UserID, arg.GroupID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHiddenByUserRow{}
	for rows.Next() {
		var i ListHiddenByUserRow
		if err := rows.Scan(
			&i.Message.ID,
			&i.Message.GroupID,
			&i.Message.ThreadID,
			&i.Message.AuthorID,
			&i.Message.ClientID,
			&i.Message.Seq,
			&i.Message.Body,
			&i.Message.ReplyToID,
			&i.Message.EditedAt,
			&i.Message.DeletedAt,
			&i.Message.HiddenForAllBy,
			&i.Message.HiddenForAllAt,
			&i.Message.CreatedAt,
			&i.Message.UpdatedAt,
			&i.Thread.ID,
			&i.Thread.GroupID,
			&i.Thread.TargetType,
			&i.Thread.TargetID,
			&i.Thread.SubjectID,
			&i.Thread.Title,
			&i.Thread.CreatedBy,
			&i.Thread.MessageCount,
			&i.Thread.LastMessageAt,
			&i.Thread.LastSeq,
			&i.Thread.CreatedAt,
			&i.Thread.UpdatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesAfter = `-- name: ListMessagesAfter :many
SELECT m.id, m.group_id, m.thread_id, m.author_id, m.client_id, m.seq, m.body, m.reply_to_id, m.edited_at, m.deleted_at, m.hidden_for_all_by, m.hidden_for_all_at, m.created_at, m.updated_at,
       COALESCE(u.name, '')::text AS author_name,
       EXISTS (SELECT 1 FROM message_hides h WHERE h.message_id = m.id AND h.user_id = $1::uuid) AS hidden_by_me,
       rm.id AS reply_id,
       rm.author_id AS reply_author_id,
       COALESCE(ru.name, '')::text AS reply_author_name,
       COALESCE(left(rm.body, 200), '')::text AS reply_body,
       (rm.deleted_at IS NOT NULL)::boolean AS reply_deleted,
       (rm.hidden_for_all_at IS NOT NULL)::boolean AS reply_hidden_for_all
FROM messages m
LEFT JOIN users u ON u.id = m.author_id
LEFT JOIN messages rm ON rm.id = m.reply_to_id
LEFT JOIN users ru ON ru.id = rm.author_id
WHERE m.thread_id = $2::uuid AND m.seq > $3::bigint
ORDER BY m.seq
LIMIT $4
`

type ListMessagesAfterParams struct {
	ViewerID uuid.UUID
	ThreadID uuid.UUID
	AfterSeq int64
	MaxRows  int32
}

type ListMessagesAfterRow struct {
	Message           Message
	AuthorName        string
	HiddenByMe        bool
	ReplyID           *uuid.UUID
	ReplyAuthorID     *uuid.UUID
	ReplyAuthorName   string
	ReplyBody         string
	ReplyDeleted      bool
	ReplyHiddenForAll bool
}

// Messages newer than after_seq, oldest first (catching up a thread).
func (q *Queries) ListMessagesAfter(ctx context.Context, arg ListMessagesAfterParams) ([]ListMessagesAfterRow, error) {
	rows, err := q.db.Query(ctx, listMessagesAfter,
		arg.ViewerID,
		arg.ThreadID,
		arg.AfterSeq,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesAfterRow{}
	for rows.Next() {
		var i ListMessagesAfterRow
		if err := rows.Scan(
			&i.Message.ID,
			&i.Message.GroupID,
			&i.Message.ThreadID,
			&i.Message.AuthorID,
			&i.Message.ClientID,
			&i.Message.Seq,
			&i.Message.Body,
			&i.Message.ReplyToID,
			&i.Message.EditedAt,
			&i.Message.DeletedAt,
			&i.Message.HiddenForAllBy,
			&i.Message.HiddenForAllAt,
			&i.Message.CreatedAt,
			&i.Message.UpdatedAt,
			&i.AuthorName,
			&i.HiddenByMe,
			&i.ReplyID,
			&i.ReplyAuthorID,
			&i.ReplyAuthorName,
			&i.ReplyBody,
			&i.ReplyDeleted,
			&i.ReplyHiddenForAll,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesBefore = `-- name: ListMessagesBefore :many
SELECT m.id, m.group_id, m.thread_id, m.author_id, m.client_id, m.seq, m.body, m.reply_to_id, m.edited_at, m.deleted_at, m.hidden_for_all_by, m.hidden_for_all_at, m.created_at, m.updated_at,
       COALESCE(u.name, '')::text AS author_name,
       EXISTS (SELECT 1 FROM message_hides h WHERE h.message_id = m.id AND h.user_id = $1::uuid) AS hidden_by_me,
       rm.id AS reply_id,
       rm.author_id AS reply_author_id,
       COALESCE(ru.name, '')::text AS reply_author_name,
       COALESCE(left(rm.body, 200), '')::text AS reply_body,
       (rm.deleted_at IS NOT NULL)::boolean AS reply_deleted,
       (rm.hidden_for_all_at IS NOT NULL)::boolean AS reply_hidden_for_all
FROM messages m
LEFT JOIN users u ON u.id = m.author_id
LEFT JOIN messages rm ON rm.id = m.reply_to_id
LEFT JOIN users ru ON ru.id = rm.author_id
WHERE m.thread_id = $2::uuid
  AND ($3::bigint IS NULL OR m.seq < $3::bigint)
ORDER BY m.seq DESC
LIMIT $4
`

type ListMessagesBeforeParams struct {
	ViewerID  uuid.UUID
	ThreadID  uuid.UUID
	BeforeSeq *int64
	MaxRows   int32
}

type ListMessagesBeforeRow struct {
	Message           Message
	AuthorName        string
	HiddenByMe        bool
	ReplyID           *uuid.UUID
	ReplyAuthorID     *uuid.UUID
	ReplyAuthorName   string
	ReplyBody         string
	ReplyDeleted      bool
	ReplyHiddenForAll bool
}

// The newest page (before_seq null) or older messages, newest first.
func (q *Queries) ListMessagesBefore(ctx context.Context, arg ListMessagesBeforeParams) ([]ListMessagesBeforeRow, error) {
	rows, err := q.db.Query(ctx, listMessagesBefore,
		arg.ViewerID,
		arg.ThreadID,
		arg.BeforeSeq,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesBeforeRow{}
	for rows.Next() {
		var i ListMessagesBeforeRow
		if err := rows.Scan(
			&i.Message.ID,
			&i.Message.GroupID,
			&i.Message.ThreadID,
			&i.Message.AuthorID,
			&i.Message.ClientID,
			&i.Message.Seq,
			&i.Message.Body,
			&i.Message.ReplyToID,
			&i.Message.EditedAt,
			&i.Message.DeletedAt,
			&i.Message.HiddenForAllBy,
			&i.Message.HiddenForAllAt,
			&i.Message.CreatedAt,
			&i.Message.UpdatedAt,
			&i.AuthorName,
			&i.HiddenByMe,
			&i.ReplyID,
			&i.ReplyAuthorID,
			&i.ReplyAuthorName,
			&i.ReplyBody,
			&i.ReplyDeleted,
			&i.ReplyHiddenForAll,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadSummaries = `-- name: ListThreadSummaries :many
SELECT t.id, t.group_id, t.target_type, t.target_id, t.subject_id, t.title, t.created_by, t.message_count, t.last_message_at, t.last_seq, t.created_at, t.updated_at,
       (SELECT count(*) FROM messages m
        WHERE m.thread_id = t.id
          AND m.seq > COALESCE(r.last_read_seq, 0)
          AND m.deleted_at IS NULL
          AND m.hidden_for_all_at IS NULL
          AND m.author_id IS DISTINCT FROM $1::uuid
          AND NOT EXISTS (SELECT 1 FROM message_hides h WHERE h.message_id = m.id AND h.user_id = $1::uuid)
       )::int AS unread,
       lm.author_id AS last_author_id,
       COALESCE(lu.name, '')::text AS last_author_name,
       (lm.created_at IS NOT NULL)::boolean AS has_last,
       COALESCE(lm.body, '')::text AS last_body,
       COALESCE(lm.created_at, t.created_at)::timestamptz AS last_created_at
FROM threads t
LEFT JOIN thread_reads r ON r.thread_id = t.id AND r.user_id = $1::uuid
LEFT JOIN LATERAL (
  SELECT m.author_id, left(m.body, 200) AS body, m.created_at
  FROM messages m
  WHERE m.thread_id = t.id AND m.deleted_at IS NULL AND m.hidden_for_all_at IS NULL
  ORDER BY m.seq DESC
  LIMIT 1
) lm ON true
LEFT JOIN users lu ON lu.id = lm.author_id
WHERE t.group_id = $2::uuid AND t.message_count > 0
ORDER BY t.last_message_at DESC NULLS LAST, t.id
`

type ListThreadSummariesParams struct {
	ViewerID uuid.UUID
	GroupID  uuid.UUID
}

type ListThreadSummariesRow struct {
	Thread         Thread
	Unread         int32
	LastAuthorID   *uuid.UUID
	LastAuthorName string
	HasLast        bool
	LastBody       string
	LastCreatedAt  time.Time
}

func (q *Queries) ListThreadSummaries(ctx context.Context, arg ListThreadSummariesParams) ([]ListThreadSummariesRow, error) {
	rows, err := q.db.Query(ctx, listThreadSummaries, arg.ViewerID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListThreadSummariesRow{}
	for rows.Next() {
		var i ListThreadSummariesRow
		if err := rows.Scan(
			&i.Thread.ID,
			&i.Thread.GroupID,
			&i.Thread.TargetType,
			&i.Thread.TargetID,
			&i.Thread.SubjectID,
			&i.Thread.Title,
			&i.Thread.CreatedBy,
			&i.Thread.MessageCount,
			&i.Thread.LastMessageAt,
			&i.Thread.LastSeq,
			&i.Thread.CreatedAt,
			&i.Thread.UpdatedAt,
			&i.Unread,
			&i.LastAuthorID,
			&i.LastAuthorName,
			&i.HasLast,
			&i.LastBody,
			&i.LastCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markThreadRead = `-- name: MarkThreadRead :exec
INSERT INTO thread_reads (thread_id, user_id, last_read_seq, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (thread_id, user_id) DO UPDATE
SET last_read_seq = GREATEST(thread_reads.last_read_seq, EXCLUDED.last_read_seq), updated_at = now()
`

type MarkThreadReadParams struct {
	ThreadID    uuid.UUID
	UserID      uuid.UUID
	LastReadSeq int64
}

func (q *Queries) MarkThreadRead(ctx context.Context, arg MarkThreadReadParams) error {
	_, err := q.db.Exec(ctx, markThreadRead, arg.ThreadID, arg.UserID, arg.LastReadSeq)
	return err
}

const setMessageHiddenForAll = `-- name: SetMessageHiddenForAll :one
UPDATE messages SET hidden_for_all_by = $2, hidden_for_all_at = $3 WHERE id = $1 RETURNING id, group_id, thread_id, author_id, client_id, seq, body, reply_to_id, edited_at, deleted_at, hidden_for_all_by, hidden_for_all_at, created_at, updated_at
`

type SetMessageHiddenForAllParams struct {
	ID             uuid.UUID
	HiddenForAllBy *uuid.UUID
	HiddenForAllAt *time.Time
}

func (q *Queries) SetMessageHiddenForAll(ctx context.Context, arg SetMessageHiddenForAllParams) (Message, error) {
	row := q.db.QueryRow(ctx, setMessageHiddenForAll, arg.ID, arg.HiddenForAllBy, arg.HiddenForAllAt)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.ThreadID,
		&i.AuthorID,
		&i.ClientID,
		&i.Seq,
		&i.Body,
		&i.ReplyToID,
		&i.EditedAt,
		&i.DeletedAt,
		&i.HiddenForAllBy,
		&i.HiddenForAllAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteMessage = `-- name: SoftDeleteMessage :one
UPDATE messages SET deleted_at = $2 WHERE id = $1 RETURNING id, group_id, thread_id, author_id, client_id, seq, body, reply_to_id, edited_at, deleted_at, hidden_for_all_by, hidden_for_all_at, created_at, updated_at
`

type SoftDeleteMessageParams struct {
	ID        uuid.UUID
	DeletedAt *time.Time
}

func (q *Queries) SoftDeleteMessage(ctx context.Context, arg SoftDeleteMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, softDeleteMessage, arg.ID, arg.DeletedAt)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.ThreadID,
		&i.AuthorID,
		&i.ClientID,
		&i.Seq,
		&i.Body,
		&i.ReplyToID,
		&i.EditedAt,
		&i.DeletedAt,
		&i.HiddenForAllBy,
		&i.HiddenForAllAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchThread = `-- name: TouchThread :exec
UPDATE threads
SET message_count = message_count + 1,
    last_seq = GREATEST(last_seq, $1::bigint),
    last_message_at = $2::timestamptz
WHERE id = $3
`

type TouchThreadParams struct {
	Seq int64
	At  time.Time
	ID  uuid.UUID
}

func (q *Queries) TouchThread(ctx context.Context, arg TouchThreadParams) error {
	_, err := q.db.Exec(ctx, touchThread, arg.Seq, arg.At, arg.ID)
	return err
}

const undeleteMessage = `-- name: UndeleteMessage :one
UPDATE messages SET deleted_at = NULL WHERE id = $1 RETURNING id, group_id, thread_id, author_id, client_id, seq, body, reply_to_id, edited_at, deleted_at, hidden_for_all_by, hidden_for_all_at, created_at, updated_at
`

func (q *Queries) UndeleteMessage(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, undeleteMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.ThreadID,
		&i.AuthorID,
		&i.ClientID,
		&i.Seq,
		&i.Body,
		&i.ReplyToID,
		&i.EditedAt,
		&i.DeletedAt,
		&i.HiddenForAllBy,
		&i.HiddenForAllAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unhideMessage = `-- name: UnhideMessage :exec
DELETE FROM message_hides WHERE message_id = $1 AND user_id = $2
`

type UnhideMessageParams struct {
	MessageID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) UnhideMessage(ctx context.Context, arg UnhideMessageParams) error {
	_, err := q.db.Exec(ctx, unhideMessage, arg.MessageID, arg.UserID)
	return err
}
