// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: drive.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const beginDriveSync = `-- name: BeginDriveSync :execrows
UPDATE drive_connections
SET status = 'SYNCING', sync_started_at = $1::timestamptz
WHERE id = $2
  AND (status <> 'SYNCING' OR sync_started_at IS NULL OR sync_started_at < $3::timestamptz)
`

type BeginDriveSyncParams struct {
	Now         time.Time
	ID          uuid.UUID
	StaleBefore time.Time
}

func (q *Queries) BeginDriveSync(ctx context.Context, arg BeginDriveSyncParams) (int64, error) {
	result, err := q.db.Exec(ctx, beginDriveSync, arg.Now, arg.ID, arg.StaleBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDriveConnection = `-- name: DeleteDriveConnection :exec
DELETE FROM drive_connections WHERE id = $1
`

func (q *Queries) DeleteDriveConnection(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDriveConnection, id)
	return err
}

const deleteDriveItems = `-- name: DeleteDriveItems :exec
DELETE FROM drive_items WHERE connection_id = $1
`

func (q *Queries) DeleteDriveItems(ctx context.Context, connectionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDriveItems, connectionID)
	return err
}

const deleteDrivePublisher = `-- name: DeleteDrivePublisher :exec
DELETE FROM drive_publishers WHERE group_id = $1
`

func (q *Queries) DeleteDrivePublisher(ctx context.Context, groupID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDrivePublisher, groupID)
	return err
}

const driveItemStats = `-- name: DriveItemStats :one
SELECT
  count(*) FILTER (WHERE NOT is_folder AND state <> 'DELETED')::bigint AS files,
  count(*) FILTER (WHERE is_folder AND state <> 'DELETED')::bigint AS folders,
  count(*) FILTER (WHERE state IN ('LINKED', 'IMPORTED'))::bigint AS linked,
  count(*) FILTER (WHERE state = 'SKIPPED')::bigint AS skipped,
  count(*) FILTER (WHERE state = 'DELETED')::bigint AS deleted,
  count(*) FILTER (WHERE state = 'ERROR')::bigint AS errors
FROM drive_items WHERE connection_id = $1
`

type DriveItemStatsRow struct {
	Files   int64
	Folders int64
	Linked  int64
	Skipped int64
	Deleted int64
	Errors  int64
}

func (q *Queries) DriveItemStats(ctx context.Context, connectionID uuid.UUID) (DriveItemStatsRow, error) {
	row := q.db.QueryRow(ctx, driveItemStats, connectionID)
	var i DriveItemStatsRow
	err := row.Scan(
		&i.Files,
		&i.Folders,
		&i.Linked,
		&i.Skipped,
		&i.Deleted,
		&i.Errors,
	)
	return i, err
}

const finishDriveSync = `-- name: FinishDriveSync :exec
UPDATE drive_connections
SET status = $1,
    last_error = $2,
    last_error_code = $3,
    sync_started_at = NULL,
    changes_page_token = COALESCE($4, changes_page_token),
    -- a failed run still counts as an attempt, so the scheduler backs off
    last_sync_at = $5::timestamptz,
    last_full_scan_at = CASE WHEN $6::boolean AND $7::boolean
                             THEN $5::timestamptz ELSE last_full_scan_at END
WHERE id = $8
`

type FinishDriveSyncParams struct {
	Status        string
	LastError     *string
	LastErrorCode *string
	PageToken     *string
	CompletedAt   time.Time
	FullScan      bool
	Succeeded     bool
	ID            uuid.UUID
}

func (q *Queries) FinishDriveSync(ctx context.Context, arg FinishDriveSyncParams) error {
	_, err := q.db.Exec(ctx, finishDriveSync,
		arg.Status,
		arg.LastError,
		arg.LastErrorCode,
		arg.PageToken,
		arg.CompletedAt,
		arg.FullScan,
		arg.Succeeded,
		arg.ID,
	)
	return err
}

const getDriveConnection = `-- name: GetDriveConnection :one
SELECT id, group_id, mode, root_folder_id, root_folder_name, drive_id, status, last_error, sync_started_at, last_sync_at, last_full_scan_at, changes_page_token, sync_interval_sec, writable, created_by, created_at, updated_at, last_error_code FROM drive_connections WHERE id = $1
`

func (q *Queries) GetDriveConnection(ctx context.Context, id uuid.UUID) (DriveConnection, error) {
	row := q.db.QueryRow(ctx, getDriveConnection, id)
	var i DriveConnection
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Mode,
		&i.RootFolderID,
		&i.RootFolderName,
		&i.DriveID,
		&i.Status,
		&i.LastError,
		&i.SyncStartedAt,
		&i.LastSyncAt,
		&i.LastFullScanAt,
		&i.ChangesPageToken,
		&i.SyncIntervalSec,
		&i.Writable,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastErrorCode,
	)
	return i, err
}

const getDriveConnectionByGroup = `-- name: GetDriveConnectionByGroup :one
SELECT id, group_id, mode, root_folder_id, root_folder_name, drive_id, status, last_error, sync_started_at, last_sync_at, last_full_scan_at, changes_page_token, sync_interval_sec, writable, created_by, created_at, updated_at, last_error_code FROM drive_connections WHERE group_id = $1
`

func (q *Queries) GetDriveConnectionByGroup(ctx context.Context, groupID uuid.UUID) (DriveConnection, error) {
	row := q.db.QueryRow(ctx, getDriveConnectionByGroup, groupID)
	var i DriveConnection
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Mode,
		&i.RootFolderID,
		&i.RootFolderName,
		&i.DriveID,
		&i.Status,
		&i.LastError,
		&i.SyncStartedAt,
		&i.LastSyncAt,
		&i.LastFullScanAt,
		&i.ChangesPageToken,
		&i.SyncIntervalSec,
		&i.Writable,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastErrorCode,
	)
	return i, err
}

const getDriveItem = `-- name: GetDriveItem :one
SELECT id, connection_id, drive_file_id, parent_id, path_cache, name, mime, is_folder, md5, size_bytes, modified_time, web_view_link, material_id, state, classification, last_error, seen_at, created_at, updated_at FROM drive_items WHERE connection_id = $1 AND drive_file_id = $2
`

type GetDriveItemParams struct {
	ConnectionID uuid.UUID
	DriveFileID  string
}

func (q *Queries) GetDriveItem(ctx context.Context, arg GetDriveItemParams) (DriveItem, error) {
	row := q.db.QueryRow(ctx, getDriveItem, arg.ConnectionID, arg.DriveFileID)
	var i DriveItem
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.DriveFileID,
		&i.ParentID,
		&i.PathCache,
		&i.Name,
		&i.Mime,
		&i.IsFolder,
		&i.Md5,
		&i.SizeBytes,
		&i.ModifiedTime,
		&i.WebViewLink,
		&i.MaterialID,
		&i.State,
		&i.Classification,
		&i.LastError,
		&i.SeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDriveItemByMaterial = `-- name: GetDriveItemByMaterial :one
SELECT id, connection_id, drive_file_id, parent_id, path_cache, name, mime, is_folder, md5, size_bytes, modified_time, web_view_link, material_id, state, classification, last_error, seen_at, created_at, updated_at FROM drive_items WHERE material_id = $1 ORDER BY updated_at DESC LIMIT 1
`

func (q *Queries) GetDriveItemByMaterial(ctx context.Context, materialID *uuid.UUID) (DriveItem, error) {
	row := q.db.QueryRow(ctx, getDriveItemByMaterial, materialID)
	var i DriveItem
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.DriveFileID,
		&i.ParentID,
		&i.PathCache,
		&i.Name,
		&i.Mime,
		&i.IsFolder,
		&i.Md5,
		&i.SizeBytes,
		&i.ModifiedTime,
		&i.WebViewLink,
		&i.MaterialID,
		&i.State,
		&i.Classification,
		&i.LastError,
		&i.SeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDrivePublisher = `-- name: GetDrivePublisher :one
SELECT group_id, google_email, refresh_token_enc, scopes, last_error, connected_by, created_at, updated_at FROM drive_publishers WHERE group_id = $1
`

func (q *Queries) GetDrivePublisher(ctx context.Context, groupID uuid.UUID) (DrivePublisher, error) {
	row := q.db.QueryRow(ctx, getDrivePublisher, groupID)
	var i DrivePublisher
	err := row.Scan(
		&i.GroupID,
		&i.GoogleEmail,
		&i.RefreshTokenEnc,
		&i.Scopes,
		&i.LastError,
		&i.ConnectedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDriveFolders = `-- name: ListDriveFolders :many
SELECT id, connection_id, drive_file_id, parent_id, path_cache, name, mime, is_folder, md5, size_bytes, modified_time, web_view_link, material_id, state, classification, last_error, seen_at, created_at, updated_at FROM drive_items WHERE connection_id = $1 AND is_folder AND state <> 'DELETED'
`

func (q *Queries) ListDriveFolders(ctx context.Context, connectionID uuid.UUID) ([]DriveItem, error) {
	rows, err := q.db.Query(ctx, listDriveFolders, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DriveItem{}
	for rows.Next() {
		var i DriveItem
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.DriveFileID,
			&i.ParentID,
			&i.PathCache,
			&i.Name,
			&i.Mime,
			&i.IsFolder,
			&i.Md5,
			&i.SizeBytes,
			&i.ModifiedTime,
			&i.WebViewLink,
			&i.MaterialID,
			&i.State,
			&i.Classification,
			&i.LastError,
			&i.SeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDriveItems = `-- name: ListDriveItems :many
SELECT id, connection_id, drive_file_id, parent_id, path_cache, name, mime, is_folder, md5, size_bytes, modified_time, web_view_link, material_id, state, classification, last_error, seen_at, created_at, updated_at FROM drive_items
WHERE connection_id = $1 AND NOT is_folder
  AND ($4::text IS NULL OR state = $4::text)
ORDER BY path_cache, name
LIMIT $2 OFFSET $3
`

type ListDriveItemsParams struct {
	ConnectionID uuid.UUID
	Limit        int32
	Offset       int32
	State        *string
}

func (q *Queries) ListDriveItems(ctx context.Context, arg ListDriveItemsParams) ([]DriveItem, error) {
	rows, err := q.db.Query(ctx, listDriveItems,
		arg.ConnectionID,
		arg.Limit,
		arg.Offset,
		arg.State,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DriveItem{}
	for rows.Next() {
		var i DriveItem
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.DriveFileID,
			&i.ParentID,
			&i.PathCache,
			&i.Name,
			&i.Mime,
			&i.IsFolder,
			&i.Md5,
			&i.SizeBytes,
			&i.ModifiedTime,
			&i.WebViewLink,
			&i.MaterialID,
			&i.State,
			&i.Classification,
			&i.LastError,
			&i.SeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueDriveConnections = `-- name: ListDueDriveConnections :many
SELECT c.id, c.group_id, c.mode, c.root_folder_id, c.root_folder_name, c.drive_id, c.status, c.last_error, c.sync_started_at, c.last_sync_at, c.last_full_scan_at, c.changes_page_token, c.sync_interval_sec, c.writable, c.created_by, c.created_at, c.updated_at, c.last_error_code FROM drive_connections c
JOIN groups g ON g.id = c.group_id AND g.archived_at IS NULL
WHERE c.status <> 'SYNCING'
  AND (c.last_sync_at IS NULL
       OR c.last_sync_at + make_interval(secs => c.sync_interval_sec) <= $1::timestamptz)
ORDER BY c.last_sync_at NULLS FIRST
`

func (q *Queries) ListDueDriveConnections(ctx context.Context, now time.Time) ([]DriveConnection, error) {
	rows, err := q.db.Query(ctx, listDueDriveConnections, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DriveConnection{}
	for rows.Next() {
		var i DriveConnection
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Mode,
			&i.RootFolderID,
			&i.RootFolderName,
			&i.DriveID,
			&i.Status,
			&i.LastError,
			&i.SyncStartedAt,
			&i.LastSyncAt,
			&i.LastFullScanAt,
			&i.ChangesPageToken,
			&i.SyncIntervalSec,
			&i.Writable,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastErrorCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReclassifyCandidates = `-- name: ListReclassifyCandidates :many
SELECT i.id, i.connection_id, i.drive_file_id, i.parent_id, i.path_cache, i.name, i.mime, i.is_folder, i.md5, i.size_bytes, i.modified_time, i.web_view_link, i.material_id, i.state, i.classification, i.last_error, i.seen_at, i.created_at, i.updated_at FROM drive_items i
JOIN drive_connections c ON c.id = i.connection_id
JOIN materials m ON m.id = i.material_id AND m.group_id = c.group_id
WHERE c.group_id = $1
  AND NOT i.is_folder
  AND i.state = 'LINKED'
  AND m.source = 'GDRIVE'
  AND m.status = 'ACTIVE'
  AND m.needs_review
  AND m.review_reason = 'LOW_CONFIDENCE'
  AND coalesce(m.classification ->> 'method', 'auto') = 'auto'
ORDER BY i.path_cache, i.name
`

// Drive files waiting in the Inbox only because the classifier was unsure:
// new subjects or aliases may resolve them. Manual decisions are left alone.
func (q *Queries) ListReclassifyCandidates(ctx context.Context, groupID uuid.UUID) ([]DriveItem, error) {
	rows, err := q.db.Query(ctx, listReclassifyCandidates, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DriveItem{}
	for rows.Next() {
		var i DriveItem
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.DriveFileID,
			&i.ParentID,
			&i.PathCache,
			&i.Name,
			&i.Mime,
			&i.IsFolder,
			&i.Md5,
			&i.SizeBytes,
			&i.ModifiedTime,
			&i.WebViewLink,
			&i.MaterialID,
			&i.State,
			&i.Classification,
			&i.LastError,
			&i.SeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnseenDriveItems = `-- name: ListUnseenDriveItems :many
SELECT id, connection_id, drive_file_id, parent_id, path_cache, name, mime, is_folder, md5, size_bytes, modified_time, web_view_link, material_id, state, classification, last_error, seen_at, created_at, updated_at FROM drive_items WHERE connection_id = $1 AND seen_at < $2 AND state <> 'DELETED'
`

type ListUnseenDriveItemsParams struct {
	ConnectionID uuid.UUID
	SeenAt       time.Time
}

func (q *Queries) ListUnseenDriveItems(ctx context.Context, arg ListUnseenDriveItemsParams) ([]DriveItem, error) {
	rows, err := q.db.Query(ctx, listUnseenDriveItems, arg.ConnectionID, arg.SeenAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DriveItem{}
	for rows.Next() {
		var i DriveItem
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.DriveFileID,
			&i.ParentID,
			&i.PathCache,
			&i.Name,
			&i.Mime,
			&i.IsFolder,
			&i.Md5,
			&i.SizeBytes,
			&i.ModifiedTime,
			&i.WebViewLink,
			&i.MaterialID,
			&i.State,
			&i.Classification,
			&i.LastError,
			&i.SeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDrivePublisherError = `-- name: SetDrivePublisherError :exec
UPDATE drive_publishers SET last_error = $2 WHERE group_id = $1
`

type SetDrivePublisherErrorParams struct {
	GroupID   uuid.UUID
	LastError *string
}

func (q *Queries) SetDrivePublisherError(ctx context.Context, arg SetDrivePublisherErrorParams) error {
	_, err := q.db.Exec(ctx, setDrivePublisherError, arg.GroupID, arg.LastError)
	return err
}

const updateDriveItemState = `-- name: UpdateDriveItemState :exec
UPDATE drive_items
SET state = $2, material_id = $3, classification = $4, last_error = $5
WHERE id = $1
`

type UpdateDriveItemStateParams struct {
	ID             uuid.UUID
	State          string
	MaterialID     *uuid.UUID
	Classification []byte
	LastError      *string
}

func (q *Queries) UpdateDriveItemState(ctx context.Context, arg UpdateDriveItemStateParams) error {
	_, err := q.db.Exec(ctx, updateDriveItemState,
		arg.ID,
		arg.State,
		arg.MaterialID,
		arg.Classification,
		arg.LastError,
	)
	return err
}

const upsertDriveConnection = `-- name: UpsertDriveConnection :one
INSERT INTO drive_connections (id, group_id, root_folder_id, root_folder_name, drive_id, status, sync_interval_sec,
                               writable, created_by)
VALUES ($1, $2, $3, $4, $5, 'PENDING', $6, $7, $8)
ON CONFLICT (group_id) DO UPDATE
SET root_folder_id = EXCLUDED.root_folder_id,
    root_folder_name = EXCLUDED.root_folder_name,
    drive_id = EXCLUDED.drive_id,
    sync_interval_sec = EXCLUDED.sync_interval_sec,
    writable = EXCLUDED.writable,
    -- a different folder starts from scratch
    status = CASE WHEN drive_connections.root_folder_id = EXCLUDED.root_folder_id
                  THEN drive_connections.status ELSE 'PENDING' END,
    changes_page_token = CASE WHEN drive_connections.root_folder_id = EXCLUDED.root_folder_id
                              THEN drive_connections.changes_page_token ELSE NULL END,
    last_full_scan_at = CASE WHEN drive_connections.root_folder_id = EXCLUDED.root_folder_id
                             THEN drive_connections.last_full_scan_at ELSE NULL END,
    last_error = NULL
RETURNING id, group_id, mode, root_folder_id, root_folder_name, drive_id, status, last_error, sync_started_at, last_sync_at, last_full_scan_at, changes_page_token, sync_interval_sec, writable, created_by, created_at, updated_at, last_error_code
`

type UpsertDriveConnectionParams struct {
	ID              uuid.UUID
	GroupID         uuid.UUID
	RootFolderID    string
	RootFolderName  string
	DriveID         *string
	SyncIntervalSec int32
	Writable        bool
	CreatedBy       *uuid.UUID
}

func (q *Queries) UpsertDriveConnection(ctx context.Context, arg UpsertDriveConnectionParams) (DriveConnection, error) {
	row := q.db.QueryRow(ctx, upsertDriveConnection,
		arg.ID,
		arg.GroupID,
		arg.RootFolderID,
		arg.RootFolderName,
		arg.DriveID,
		arg.SyncIntervalSec,
		arg.Writable,
		arg.CreatedBy,
	)
	var i DriveConnection
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Mode,
		&i.RootFolderID,
		&i.RootFolderName,
		&i.DriveID,
		&i.Status,
		&i.LastError,
		&i.SyncStartedAt,
		&i.LastSyncAt,
		&i.LastFullScanAt,
		&i.ChangesPageToken,
		&i.SyncIntervalSec,
		&i.Writable,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastErrorCode,
	)
	return i, err
}

const upsertDriveItem = `-- name: UpsertDriveItem :one
INSERT INTO drive_items (id, connection_id, drive_file_id, parent_id, path_cache, name, mime, is_folder, md5,
                         size_bytes, modified_time, web_view_link, material_id, state, classification, seen_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
ON CONFLICT (connection_id, drive_file_id) DO UPDATE
SET parent_id = EXCLUDED.parent_id,
    path_cache = EXCLUDED.path_cache,
    name = EXCLUDED.name,
    mime = EXCLUDED.mime,
    is_folder = EXCLUDED.is_folder,
    md5 = EXCLUDED.md5,
    size_bytes = EXCLUDED.size_bytes,
    modified_time = EXCLUDED.modified_time,
    web_view_link = EXCLUDED.web_view_link,
    -- the sync run's clock, compared against its start to find vanished files
    seen_at = EXCLUDED.seen_at
RETURNING id, connection_id, drive_file_id, parent_id, path_cache, name, mime, is_folder, md5, size_bytes, modified_time, web_view_link, material_id, state, classification, last_error, seen_at, created_at, updated_at
`

type UpsertDriveItemParams struct {
	ID             uuid.UUID
	ConnectionID   uuid.UUID
	DriveFileID    string
	ParentID       *string
	PathCache      string
	Name           string
	Mime           string
	IsFolder       bool
	Md5            *string
	SizeBytes      *int64
	ModifiedTime   *time.Time
	WebViewLink    *string
	MaterialID     *uuid.UUID
	State          string
	Classification []byte
	SeenAt         time.Time
}

func (q *Queries) UpsertDriveItem(ctx context.Context, arg UpsertDriveItemParams) (DriveItem, error) {
	row := q.db.QueryRow(ctx, upsertDriveItem,
		arg.ID,
		arg.ConnectionID,
		arg.DriveFileID,
		arg.ParentID,
		arg.PathCache,
		arg.Name,
		arg.Mime,
		arg.IsFolder,
		arg.Md5,
		arg.SizeBytes,
		arg.ModifiedTime,
		arg.WebViewLink,
		arg.MaterialID,
		arg.State,
		arg.Classification,
		arg.SeenAt,
	)
	var i DriveItem
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.DriveFileID,
		&i.ParentID,
		&i.PathCache,
		&i.Name,
		&i.Mime,
		&i.IsFolder,
		&i.Md5,
		&i.SizeBytes,
		&i.ModifiedTime,
		&i.WebViewLink,
		&i.MaterialID,
		&i.State,
		&i.Classification,
		&i.LastError,
		&i.SeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDrivePublisher = `-- name: UpsertDrivePublisher :one
INSERT INTO drive_publishers (group_id, google_email, refresh_token_enc, scopes, connected_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (group_id) DO UPDATE
SET google_email = EXCLUDED.google_email, refresh_token_enc = EXCLUDED.refresh_token_enc,
    scopes = EXCLUDED.scopes, connected_by = EXCLUDED.connected_by, last_error = NULL,
    created_at = now()
RETURNING group_id, google_email, refresh_token_enc, scopes, last_error, connected_by, created_at, updated_at
`

type UpsertDrivePublisherParams struct {
	GroupID         uuid.UUID
	GoogleEmail     string
	RefreshTokenEnc []byte
	Scopes          string
	ConnectedBy     *uuid.UUID
}

func (q *Queries) UpsertDrivePublisher(ctx context.Context, arg UpsertDrivePublisherParams) (DrivePublisher, error) {
	row := q.db.QueryRow(ctx, upsertDrivePublisher,
		arg.GroupID,
		arg.GoogleEmail,
		arg.RefreshTokenEnc,
		arg.Scopes,
		arg.ConnectedBy,
	)
	var i DrivePublisher
	err := row.Scan(
		&i.GroupID,
		&i.GoogleEmail,
		&i.RefreshTokenEnc,
		&i.Scopes,
		&i.LastError,
		&i.ConnectedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
