// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteGroupEventsBefore = `-- name: DeleteGroupEventsBefore :execrows
DELETE FROM group_events WHERE created_at < $1
`

func (q *Queries) DeleteGroupEventsBefore(ctx context.Context, createdAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGroupEventsBefore, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertGroupEvent = `-- name: InsertGroupEvent :one
INSERT INTO group_events (id, group_id, seq, kind, actor_id, entity_type, entity_id, payload, audit)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, group_id, seq, kind, actor_id, entity_type, entity_id, payload, audit, created_at
`

type InsertGroupEventParams struct {
	ID         uuid.UUID
	GroupID    uuid.UUID
	Seq        int64
	Kind       string
	ActorID    *uuid.UUID
	EntityType string
	EntityID   *uuid.UUID
	Payload    []byte
	Audit      bool
}

func (q *Queries) InsertGroupEvent(ctx context.Context, arg InsertGroupEventParams) (GroupEvent, error) {
	row := q.db.QueryRow(ctx, insertGroupEvent,
		arg.ID,
		arg.GroupID,
		arg.Seq,
		arg.Kind,
		arg.ActorID,
		arg.EntityType,
		arg.EntityID,
		arg.Payload,
		arg.Audit,
	)
	var i GroupEvent
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Seq,
		&i.Kind,
		&i.ActorID,
		&i.EntityType,
		&i.EntityID,
		&i.Payload,
		&i.Audit,
		&i.CreatedAt,
	)
	return i, err
}

const listGroupAuditEvents = `-- name: ListGroupAuditEvents :many
SELECT id, group_id, seq, kind, actor_id, entity_type, entity_id, payload, audit, created_at FROM group_events
WHERE group_id = $1 AND audit = true AND ($3::bigint IS NULL OR seq < $3::bigint)
ORDER BY seq DESC
LIMIT $2
`

type ListGroupAuditEventsParams struct {
	GroupID   uuid.UUID
	Limit     int32
	BeforeSeq *int64
}

func (q *Queries) ListGroupAuditEvents(ctx context.Context, arg ListGroupAuditEventsParams) ([]GroupEvent, error) {
	rows, err := q.db.Query(ctx, listGroupAuditEvents, arg.GroupID, arg.Limit, arg.BeforeSeq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GroupEvent{}
	for rows.Next() {
		var i GroupEvent
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Seq,
			&i.Kind,
			&i.ActorID,
			&i.EntityType,
			&i.EntityID,
			&i.Payload,
			&i.Audit,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupEventsSince = `-- name: ListGroupEventsSince :many
SELECT id, group_id, seq, kind, actor_id, entity_type, entity_id, payload, audit, created_at FROM group_events
WHERE group_id = $1 AND seq > $2
ORDER BY seq
LIMIT $3
`

type ListGroupEventsSinceParams struct {
	GroupID uuid.UUID
	Seq     int64
	Limit   int32
}

func (q *Queries) ListGroupEventsSince(ctx context.Context, arg ListGroupEventsSinceParams) ([]GroupEvent, error) {
	rows, err := q.db.Query(ctx, listGroupEventsSince, arg.GroupID, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GroupEvent{}
	for rows.Next() {
		var i GroupEvent
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Seq,
			&i.Kind,
			&i.ActorID,
			&i.EntityType,
			&i.EntityID,
			&i.Payload,
			&i.Audit,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const oldestGroupEventSeq = `-- name: OldestGroupEventSeq :one
SELECT COALESCE(min(seq), 0)::bigint FROM group_events WHERE group_id = $1
`

func (q *Queries) OldestGroupEventSeq(ctx context.Context, groupID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, oldestGroupEventSeq, groupID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
