// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const archiveGroup = `-- name: ArchiveGroup :exec
UPDATE groups SET archived_at = now() WHERE id = $1
`

func (q *Queries) ArchiveGroup(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, archiveGroup, id)
	return err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (id, name, slug, kind, join_policy, join_code, media_mode, settings, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, name, slug, kind, join_policy, join_code, public_read, media_mode, settings, last_seq, created_by, created_at, updated_at, archived_at
`

type CreateGroupParams struct {
	ID         uuid.UUID
	Name       string
	Slug       string
	Kind       string
	JoinPolicy string
	JoinCode   *string
	MediaMode  string
	Settings   []byte
	CreatedBy  uuid.UUID
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Kind,
		arg.JoinPolicy,
		arg.JoinCode,
		arg.MediaMode,
		arg.Settings,
		arg.CreatedBy,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Kind,
		&i.JoinPolicy,
		&i.JoinCode,
		&i.PublicRead,
		&i.MediaMode,
		&i.Settings,
		&i.LastSeq,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getGroup = `-- name: GetGroup :one
SELECT id, name, slug, kind, join_policy, join_code, public_read, media_mode, settings, last_seq, created_by, created_at, updated_at, archived_at FROM groups WHERE id = $1
`

func (q *Queries) GetGroup(ctx context.Context, id uuid.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, getGroup, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Kind,
		&i.JoinPolicy,
		&i.JoinCode,
		&i.PublicRead,
		&i.MediaMode,
		&i.Settings,
		&i.LastSeq,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getGroupByJoinCode = `-- name: GetGroupByJoinCode :one
SELECT id, name, slug, kind, join_policy, join_code, public_read, media_mode, settings, last_seq, created_by, created_at, updated_at, archived_at FROM groups WHERE join_code = $1 AND archived_at IS NULL
`

func (q *Queries) GetGroupByJoinCode(ctx context.Context, joinCode *string) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByJoinCode, joinCode)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Kind,
		&i.JoinPolicy,
		&i.JoinCode,
		&i.PublicRead,
		&i.MediaMode,
		&i.Settings,
		&i.LastSeq,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getGroupBySlug = `-- name: GetGroupBySlug :one
SELECT id, name, slug, kind, join_policy, join_code, public_read, media_mode, settings, last_seq, created_by, created_at, updated_at, archived_at FROM groups WHERE slug = $1
`

func (q *Queries) GetGroupBySlug(ctx context.Context, slug string) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupBySlug, slug)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Kind,
		&i.JoinPolicy,
		&i.JoinCode,
		&i.PublicRead,
		&i.MediaMode,
		&i.Settings,
		&i.LastSeq,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const groupSlugExists = `-- name: GroupSlugExists :one
SELECT EXISTS (SELECT 1 FROM groups WHERE slug = $1)
`

func (q *Queries) GroupSlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, groupSlugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listGroupsForUser = `-- name: ListGroupsForUser :many
SELECT groups.id, groups.name, groups.slug, groups.kind, groups.join_policy, groups.join_code, groups.public_read, groups.media_mode, groups.settings, groups.last_seq, groups.created_by, groups.created_at, groups.updated_at, groups.archived_at, memberships.id, memberships.user_id, memberships.group_id, memberships.roles, memberships.status, memberships.joined_via, memberships.joined_at, memberships.created_at, memberships.updated_at
FROM groups
JOIN memberships ON memberships.group_id = groups.id
WHERE memberships.user_id = $1
  AND memberships.status = 'ACTIVE'
  AND groups.archived_at IS NULL
ORDER BY groups.created_at
`

type ListGroupsForUserRow struct {
	Group      Group
	Membership Membership
}

func (q *Queries) ListGroupsForUser(ctx context.Context, userID uuid.UUID) ([]ListGroupsForUserRow, error) {
	rows, err := q.db.Query(ctx, listGroupsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupsForUserRow{}
	for rows.Next() {
		var i ListGroupsForUserRow
		if err := rows.Scan(
			&i.Group.ID,
			&i.Group.Name,
			&i.Group.Slug,
			&i.Group.Kind,
			&i.Group.JoinPolicy,
			&i.Group.JoinCode,
			&i.Group.PublicRead,
			&i.Group.MediaMode,
			&i.Group.Settings,
			&i.Group.LastSeq,
			&i.Group.CreatedBy,
			&i.Group.CreatedAt,
			&i.Group.UpdatedAt,
			&i.Group.ArchivedAt,
			&i.Membership.ID,
			&i.Membership.UserID,
			&i.Membership.GroupID,
			&i.Membership.Roles,
			&i.Membership.Status,
			&i.Membership.JoinedVia,
			&i.Membership.JoinedAt,
			&i.Membership.CreatedAt,
			&i.Membership.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextGroupSeq = `-- name: NextGroupSeq :one
UPDATE groups SET last_seq = last_seq + 1 WHERE id = $1 RETURNING last_seq
`

func (q *Queries) NextGroupSeq(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, nextGroupSeq, id)
	var last_seq int64
	err := row.Scan(&last_seq)
	return last_seq, err
}

const searchOpenGroups = `-- name: SearchOpenGroups :many
SELECT g.id, g.name, g.slug, g.kind, g.join_policy, g.join_code, g.public_read, g.media_mode, g.settings, g.last_seq, g.created_by, g.created_at, g.updated_at, g.archived_at,
       (SELECT count(*) FROM memberships m
         WHERE m.group_id = g.id AND m.status = 'ACTIVE')::bigint AS member_count,
       EXISTS (SELECT 1 FROM memberships m
         WHERE m.group_id = g.id AND m.user_id = $1 AND m.status = 'ACTIVE') AS is_member
FROM groups g
WHERE g.archived_at IS NULL
  AND g.join_policy = 'OPEN'
  AND g.name ILIKE '%' || $2::text || '%' ESCAPE '\'
ORDER BY lower(g.name) = lower($3::text) DESC,
         g.name ILIKE $2::text || '%' ESCAPE '\' DESC,
         member_count DESC,
         g.name
LIMIT $4
`

type SearchOpenGroupsParams struct {
	UserID     uuid.UUID
	Pattern    string
	Query      string
	MaxResults int32
}

type SearchOpenGroupsRow struct {
	Group       Group
	MemberCount int64
	IsMember    bool
}

// Groups anyone may join by name (D33): open, not archived. An empty pattern
// lists all of them. Exact and prefix matches first, then larger groups.
func (q *Queries) SearchOpenGroups(ctx context.Context, arg SearchOpenGroupsParams) ([]SearchOpenGroupsRow, error) {
	rows, err := q.db.Query(ctx, searchOpenGroups,
		arg.UserID,
		arg.Pattern,
		arg.Query,
		arg.MaxResults,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchOpenGroupsRow{}
	for rows.Next() {
		var i SearchOpenGroupsRow
		if err := rows.Scan(
			&i.Group.ID,
			&i.Group.Name,
			&i.Group.Slug,
			&i.Group.Kind,
			&i.Group.JoinPolicy,
			&i.Group.JoinCode,
			&i.Group.PublicRead,
			&i.Group.MediaMode,
			&i.Group.Settings,
			&i.Group.LastSeq,
			&i.Group.CreatedBy,
			&i.Group.CreatedAt,
			&i.Group.UpdatedAt,
			&i.Group.ArchivedAt,
			&i.MemberCount,
			&i.IsMember,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setGroupJoinCode = `-- name: SetGroupJoinCode :one
UPDATE groups SET join_code = $2 WHERE id = $1 RETURNING id, name, slug, kind, join_policy, join_code, public_read, media_mode, settings, last_seq, created_by, created_at, updated_at, archived_at
`

type SetGroupJoinCodeParams struct {
	ID       uuid.UUID
	JoinCode *string
}

func (q *Queries) SetGroupJoinCode(ctx context.Context, arg SetGroupJoinCodeParams) (Group, error) {
	row := q.db.QueryRow(ctx, setGroupJoinCode, arg.ID, arg.JoinCode)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Kind,
		&i.JoinPolicy,
		&i.JoinCode,
		&i.PublicRead,
		&i.MediaMode,
		&i.Settings,
		&i.LastSeq,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups
SET name = $2, kind = $3, join_policy = $4, public_read = $5, media_mode = $6, settings = $7
WHERE id = $1
RETURNING id, name, slug, kind, join_policy, join_code, public_read, media_mode, settings, last_seq, created_by, created_at, updated_at, archived_at
`

type UpdateGroupParams struct {
	ID         uuid.UUID
	Name       string
	Kind       string
	JoinPolicy string
	PublicRead bool
	MediaMode  string
	Settings   []byte
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroup,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.JoinPolicy,
		arg.PublicRead,
		arg.MediaMode,
		arg.Settings,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Kind,
		&i.JoinPolicy,
		&i.JoinCode,
		&i.PublicRead,
		&i.MediaMode,
		&i.Settings,
		&i.LastSeq,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}
