// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invites.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (id, group_id, code, roles, expires_at, max_uses, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, group_id, code, roles, expires_at, max_uses, uses, created_by, revoked_at, created_at
`

type CreateInviteParams struct {
	ID        uuid.UUID
	GroupID   uuid.UUID
	Code      string
	Roles     []string
	ExpiresAt *time.Time
	MaxUses   *int32
	CreatedBy uuid.UUID
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.ID,
		arg.GroupID,
		arg.Code,
		arg.Roles,
		arg.ExpiresAt,
		arg.MaxUses,
		arg.CreatedBy,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Code,
		&i.Roles,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.Uses,
		&i.CreatedBy,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInviteByCode = `-- name: GetInviteByCode :one
SELECT id, group_id, code, roles, expires_at, max_uses, uses, created_by, revoked_at, created_at FROM invites WHERE code = $1
`

func (q *Queries) GetInviteByCode(ctx context.Context, code string) (Invite, error) {
	row := q.db.QueryRow(ctx, getInviteByCode, code)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Code,
		&i.Roles,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.Uses,
		&i.CreatedBy,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementInviteUses = `-- name: IncrementInviteUses :one
UPDATE invites SET uses = uses + 1 WHERE id = $1 RETURNING id, group_id, code, roles, expires_at, max_uses, uses, created_by, revoked_at, created_at
`

func (q *Queries) IncrementInviteUses(ctx context.Context, id uuid.UUID) (Invite, error) {
	row := q.db.QueryRow(ctx, incrementInviteUses, id)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Code,
		&i.Roles,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.Uses,
		&i.CreatedBy,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listInvitesByGroup = `-- name: ListInvitesByGroup :many
SELECT id, group_id, code, roles, expires_at, max_uses, uses, created_by, revoked_at, created_at FROM invites WHERE group_id = $1 AND revoked_at IS NULL ORDER BY created_at DESC
`

func (q *Queries) ListInvitesByGroup(ctx context.Context, groupID uuid.UUID) ([]Invite, error) {
	rows, err := q.db.Query(ctx, listInvitesByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invite{}
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Code,
			&i.Roles,
			&i.ExpiresAt,
			&i.MaxUses,
			&i.Uses,
			&i.CreatedBy,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeInvite = `-- name: RevokeInvite :exec
UPDATE invites SET revoked_at = now() WHERE id = $1 AND group_id = $2
`

type RevokeInviteParams struct {
	ID      uuid.UUID
	GroupID uuid.UUID
}

func (q *Queries) RevokeInvite(ctx context.Context, arg RevokeInviteParams) error {
	_, err := q.db.Exec(ctx, revokeInvite, arg.ID, arg.GroupID)
	return err
}
