// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: materials.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimVersionPreview = `-- name: ClaimVersionPreview :one
UPDATE material_versions SET preview_status = 'PENDING', preview_error = NULL
WHERE id = $1 AND (preview_status IS NULL OR preview_status = 'FAILED')
RETURNING id
`

// Marks a preview as requested unless it is already pending, ready or
// skipped (a failed one may be retried): the caller enqueues the conversion
// only when a row comes back.
func (q *Queries) ClaimVersionPreview(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, claimVersionPreview, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const countInbox = `-- name: CountInbox :one
SELECT count(*) FROM materials WHERE group_id = $1 AND needs_review AND status = 'ACTIVE'
`

func (q *Queries) CountInbox(ctx context.Context, groupID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countInbox, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMaterial = `-- name: CreateMaterial :one
INSERT INTO materials (id, group_id, subject_id, uploader_id, title, description, kind, source, status,
                       classification, needs_review, review_reason, sort_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, group_id, subject_id, uploader_id, title, description, kind, source, status, current_version_id,
          classification, needs_review, review_reason, download_count, sort_at, archived_by, archived_at,
          deleted_by, deleted_at, created_at, updated_at
`

type CreateMaterialParams struct {
	ID             uuid.UUID
	GroupID        uuid.UUID
	SubjectID      *uuid.UUID
	UploaderID     *uuid.UUID
	Title          string
	Description    string
	Kind           string
	Source         string
	Status         string
	Classification []byte
	NeedsReview    bool
	ReviewReason   *string
	SortAt         time.Time
}

type CreateMaterialRow struct {
	ID               uuid.UUID
	GroupID          uuid.UUID
	SubjectID        *uuid.UUID
	UploaderID       *uuid.UUID
	Title            string
	Description      string
	Kind             string
	Source           string
	Status           string
	CurrentVersionID *uuid.UUID
	Classification   []byte
	NeedsReview      bool
	ReviewReason     *string
	DownloadCount    int32
	SortAt           time.Time
	ArchivedBy       *uuid.UUID
	ArchivedAt       *time.Time
	DeletedBy        *uuid.UUID
	DeletedAt        *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) CreateMaterial(ctx context.Context, arg CreateMaterialParams) (CreateMaterialRow, error) {
	row := q.db.QueryRow(ctx, createMaterial,
		arg.ID,
		arg.GroupID,
		arg.SubjectID,
		arg.UploaderID,
		arg.Title,
		arg.Description,
		arg.Kind,
		arg.Source,
		arg.Status,
		arg.Classification,
		arg.NeedsReview,
		arg.ReviewReason,
		arg.SortAt,
	)
	var i CreateMaterialRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.SubjectID,
		&i.UploaderID,
		&i.Title,
		&i.Description,
		&i.Kind,
		&i.Source,
		&i.Status,
		&i.CurrentVersionID,
		&i.Classification,
		&i.NeedsReview,
		&i.ReviewReason,
		&i.DownloadCount,
		&i.SortAt,
		&i.ArchivedBy,
		&i.ArchivedAt,
		&i.DeletedBy,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMaterialVersion = `-- name: CreateMaterialVersion :one
INSERT INTO material_versions (id, material_id, version_no, storage, storage_key, drive_file_id, drive_web_view_link,
                               drive_md5, drive_modified_time, drive_revision_id, drive_upload_status, original_name,
                               mime, size_bytes, sha256, scan_status, uploaded_by)
VALUES ($1, $2,
        COALESCE((SELECT max(version_no) FROM material_versions WHERE material_id = $2), 0) + 1,
        $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id, material_id, version_no, storage, storage_key, cache_expires_at, drive_file_id, drive_web_view_link, drive_md5, drive_modified_time, drive_upload_status, drive_upload_error, original_name, mime, size_bytes, sha256, scan_status, text_key, preview_key, uploaded_by, created_at, drive_revision_id, preview_status, preview_error
`

type CreateMaterialVersionParams struct {
	ID                uuid.UUID
	MaterialID        uuid.UUID
	Storage           string
	StorageKey        *string
	DriveFileID       *string
	DriveWebViewLink  *string
	DriveMd5          *string
	DriveModifiedTime *time.Time
	DriveRevisionID   *string
	DriveUploadStatus *string
	OriginalName      string
	Mime              string
	SizeBytes         int64
	Sha256            *string
	ScanStatus        string
	UploadedBy        *uuid.UUID
}

func (q *Queries) CreateMaterialVersion(ctx context.Context, arg CreateMaterialVersionParams) (MaterialVersion, error) {
	row := q.db.QueryRow(ctx, createMaterialVersion,
		arg.ID,
		arg.MaterialID,
		arg.Storage,
		arg.StorageKey,
		arg.DriveFileID,
		arg.DriveWebViewLink,
		arg.DriveMd5,
		arg.DriveModifiedTime,
		arg.DriveRevisionID,
		arg.DriveUploadStatus,
		arg.OriginalName,
		arg.Mime,
		arg.SizeBytes,
		arg.Sha256,
		arg.ScanStatus,
		arg.UploadedBy,
	)
	var i MaterialVersion
	err := row.Scan(
		&i.ID,
		&i.MaterialID,
		&i.VersionNo,
		&i.Storage,
		&i.StorageKey,
		&i.CacheExpiresAt,
		&i.DriveFileID,
		&i.DriveWebViewLink,
		&i.DriveMd5,
		&i.DriveModifiedTime,
		&i.DriveUploadStatus,
		&i.DriveUploadError,
		&i.OriginalName,
		&i.Mime,
		&i.SizeBytes,
		&i.Sha256,
		&i.ScanStatus,
		&i.TextKey,
		&i.PreviewKey,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.DriveRevisionID,
		&i.PreviewStatus,
		&i.PreviewError,
	)
	return i, err
}

const deleteMaterialTags = `-- name: DeleteMaterialTags :exec
DELETE FROM material_tags WHERE material_id = $1
`

func (q *Queries) DeleteMaterialTags(ctx context.Context, materialID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMaterialTags, materialID)
	return err
}

const getMaterial = `-- name: GetMaterial :one
SELECT id, group_id, subject_id, uploader_id, title, description, kind, source, status, current_version_id,
       classification, needs_review, review_reason, download_count, sort_at, archived_by, archived_at,
       deleted_by, deleted_at, created_at, updated_at
FROM materials WHERE id = $1
`

type GetMaterialRow struct {
	ID               uuid.UUID
	GroupID          uuid.UUID
	SubjectID        *uuid.UUID
	UploaderID       *uuid.UUID
	Title            string
	Description      string
	Kind             string
	Source           string
	Status           string
	CurrentVersionID *uuid.UUID
	Classification   []byte
	NeedsReview      bool
	ReviewReason     *string
	DownloadCount    int32
	SortAt           time.Time
	ArchivedBy       *uuid.UUID
	ArchivedAt       *time.Time
	DeletedBy        *uuid.UUID
	DeletedAt        *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) GetMaterial(ctx context.Context, id uuid.UUID) (GetMaterialRow, error) {
	row := q.db.QueryRow(ctx, getMaterial, id)
	var i GetMaterialRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.SubjectID,
		&i.UploaderID,
		&i.Title,
		&i.Description,
		&i.Kind,
		&i.Source,
		&i.Status,
		&i.CurrentVersionID,
		&i.Classification,
		&i.NeedsReview,
		&i.ReviewReason,
		&i.DownloadCount,
		&i.SortAt,
		&i.ArchivedBy,
		&i.ArchivedAt,
		&i.DeletedBy,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMaterialVersion = `-- name: GetMaterialVersion :one
SELECT id, material_id, version_no, storage, storage_key, cache_expires_at, drive_file_id, drive_web_view_link, drive_md5, drive_modified_time, drive_upload_status, drive_upload_error, original_name, mime, size_bytes, sha256, scan_status, text_key, preview_key, uploaded_by, created_at, drive_revision_id, preview_status, preview_error FROM material_versions WHERE id = $1
`

func (q *Queries) GetMaterialVersion(ctx context.Context, id uuid.UUID) (MaterialVersion, error) {
	row := q.db.QueryRow(ctx, getMaterialVersion, id)
	var i MaterialVersion
	err := row.Scan(
		&i.ID,
		&i.MaterialID,
		&i.VersionNo,
		&i.Storage,
		&i.StorageKey,
		&i.CacheExpiresAt,
		&i.DriveFileID,
		&i.DriveWebViewLink,
		&i.DriveMd5,
		&i.DriveModifiedTime,
		&i.DriveUploadStatus,
		&i.DriveUploadError,
		&i.OriginalName,
		&i.Mime,
		&i.SizeBytes,
		&i.Sha256,
		&i.ScanStatus,
		&i.TextKey,
		&i.PreviewKey,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.DriveRevisionID,
		&i.PreviewStatus,
		&i.PreviewError,
	)
	return i, err
}

const getMaterialView = `-- name: GetMaterialView :one
SELECT m.id, m.group_id, m.subject_id, m.uploader_id, m.title, m.description, m.kind, m.source, m.status,
       m.current_version_id, m.classification, m.needs_review, m.review_reason, m.download_count, m.sort_at,
       m.archived_by, m.archived_at, m.deleted_by, m.deleted_at, m.created_at, m.updated_at,
       v.id, v.material_id, v.version_no, v.storage, v.storage_key, v.cache_expires_at, v.drive_file_id, v.drive_web_view_link, v.drive_md5, v.drive_modified_time, v.drive_upload_status, v.drive_upload_error, v.original_name, v.mime, v.size_bytes, v.sha256, v.scan_status, v.text_key, v.preview_key, v.uploaded_by, v.created_at, v.drive_revision_id, v.preview_status, v.preview_error
FROM materials m
JOIN material_versions v ON v.id = m.current_version_id
WHERE m.id = $1
`

type GetMaterialViewRow struct {
	ID               uuid.UUID
	GroupID          uuid.UUID
	SubjectID        *uuid.UUID
	UploaderID       *uuid.UUID
	Title            string
	Description      string
	Kind             string
	Source           string
	Status           string
	CurrentVersionID *uuid.UUID
	Classification   []byte
	NeedsReview      bool
	ReviewReason     *string
	DownloadCount    int32
	SortAt           time.Time
	ArchivedBy       *uuid.UUID
	ArchivedAt       *time.Time
	DeletedBy        *uuid.UUID
	DeletedAt        *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
	MaterialVersion  MaterialVersion
}

func (q *Queries) GetMaterialView(ctx context.Context, id uuid.UUID) (GetMaterialViewRow, error) {
	row := q.db.QueryRow(ctx, getMaterialView, id)
	var i GetMaterialViewRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.SubjectID,
		&i.UploaderID,
		&i.Title,
		&i.Description,
		&i.Kind,
		&i.Source,
		&i.Status,
		&i.CurrentVersionID,
		&i.Classification,
		&i.NeedsReview,
		&i.ReviewReason,
		&i.DownloadCount,
		&i.SortAt,
		&i.ArchivedBy,
		&i.ArchivedAt,
		&i.DeletedBy,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaterialVersion.ID,
		&i.MaterialVersion.MaterialID,
		&i.MaterialVersion.VersionNo,
		&i.MaterialVersion.Storage,
		&i.MaterialVersion.StorageKey,
		&i.MaterialVersion.CacheExpiresAt,
		&i.MaterialVersion.DriveFileID,
		&i.MaterialVersion.DriveWebViewLink,
		&i.MaterialVersion.DriveMd5,
		&i.MaterialVersion.DriveModifiedTime,
		&i.MaterialVersion.DriveUploadStatus,
		&i.MaterialVersion.DriveUploadError,
		&i.MaterialVersion.OriginalName,
		&i.MaterialVersion.Mime,
		&i.MaterialVersion.SizeBytes,
		&i.MaterialVersion.Sha256,
		&i.MaterialVersion.ScanStatus,
		&i.MaterialVersion.TextKey,
		&i.MaterialVersion.PreviewKey,
		&i.MaterialVersion.UploadedBy,
		&i.MaterialVersion.CreatedAt,
		&i.MaterialVersion.DriveRevisionID,
		&i.MaterialVersion.PreviewStatus,
		&i.MaterialVersion.PreviewError,
	)
	return i, err
}

const hardDeleteMaterial = `-- name: HardDeleteMaterial :exec
DELETE FROM materials WHERE id = $1
`

func (q *Queries) HardDeleteMaterial(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteMaterial, id)
	return err
}

const incrementMaterialDownloads = `-- name: IncrementMaterialDownloads :exec
UPDATE materials SET download_count = download_count + 1 WHERE id = $1
`

func (q *Queries) IncrementMaterialDownloads(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementMaterialDownloads, id)
	return err
}

const insertMaterialTags = `-- name: InsertMaterialTags :exec
INSERT INTO material_tags (material_id, tag_id)
SELECT $1::uuid, unnest($2::uuid[])
ON CONFLICT DO NOTHING
`

type InsertMaterialTagsParams struct {
	MaterialID uuid.UUID
	TagIds     []uuid.UUID
}

func (q *Queries) InsertMaterialTags(ctx context.Context, arg InsertMaterialTagsParams) error {
	_, err := q.db.Exec(ctx, insertMaterialTags, arg.MaterialID, arg.TagIds)
	return err
}

const listMaterialTags = `-- name: ListMaterialTags :many
SELECT material_id, tag_id FROM material_tags WHERE material_id = ANY ($1::uuid[])
`

func (q *Queries) ListMaterialTags(ctx context.Context, materialIds []uuid.UUID) ([]MaterialTag, error) {
	rows, err := q.db.Query(ctx, listMaterialTags, materialIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaterialTag{}
	for rows.Next() {
		var i MaterialTag
		if err := rows.Scan(&i.MaterialID, &i.TagID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaterialVersions = `-- name: ListMaterialVersions :many
SELECT id, material_id, version_no, storage, storage_key, cache_expires_at, drive_file_id, drive_web_view_link, drive_md5, drive_modified_time, drive_upload_status, drive_upload_error, original_name, mime, size_bytes, sha256, scan_status, text_key, preview_key, uploaded_by, created_at, drive_revision_id, preview_status, preview_error FROM material_versions WHERE material_id = $1 ORDER BY version_no DESC
`

func (q *Queries) ListMaterialVersions(ctx context.Context, materialID uuid.UUID) ([]MaterialVersion, error) {
	rows, err := q.db.Query(ctx, listMaterialVersions, materialID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaterialVersion{}
	for rows.Next() {
		var i MaterialVersion
		if err := rows.Scan(
			&i.ID,
			&i.MaterialID,
			&i.VersionNo,
			&i.Storage,
			&i.StorageKey,
			&i.CacheExpiresAt,
			&i.DriveFileID,
			&i.DriveWebViewLink,
			&i.DriveMd5,
			&i.DriveModifiedTime,
			&i.DriveUploadStatus,
			&i.DriveUploadError,
			&i.OriginalName,
			&i.Mime,
			&i.SizeBytes,
			&i.Sha256,
			&i.ScanStatus,
			&i.TextKey,
			&i.PreviewKey,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.DriveRevisionID,
			&i.PreviewStatus,
			&i.PreviewError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaterials = `-- name: ListMaterials :many
SELECT m.id, m.group_id, m.subject_id, m.uploader_id, m.title, m.description, m.kind, m.source, m.status,
       m.current_version_id, m.classification, m.needs_review, m.review_reason, m.download_count, m.sort_at,
       m.archived_by, m.archived_at, m.deleted_by, m.deleted_at, m.created_at, m.updated_at,
       v.id, v.material_id, v.version_no, v.storage, v.storage_key, v.cache_expires_at, v.drive_file_id, v.drive_web_view_link, v.drive_md5, v.drive_modified_time, v.drive_upload_status, v.drive_upload_error, v.original_name, v.mime, v.size_bytes, v.sha256, v.scan_status, v.text_key, v.preview_key, v.uploaded_by, v.created_at, v.drive_revision_id, v.preview_status, v.preview_error
FROM materials m
JOIN material_versions v ON v.id = m.current_version_id
WHERE m.group_id = $1
  AND m.status = $2
  AND ($3::uuid IS NULL OR m.subject_id = $3::uuid)
  AND (NOT $4::boolean OR m.subject_id IS NULL)
  AND ($5::text IS NULL OR m.kind = $5::text)
  AND ($6::uuid IS NULL OR m.uploader_id = $6::uuid)
  AND (NOT $7::boolean OR m.needs_review)
  AND (cardinality($8::text[]) = 0
       OR (v.mime LIKE ANY ($8::text[])) <> $9::boolean)
  AND (cardinality($10::uuid[]) = 0 OR (
        SELECT count(*) FROM material_tags mt
        WHERE mt.material_id = m.id AND mt.tag_id = ANY ($10::uuid[])
      ) = cardinality($10::uuid[]))
  AND ($11::text IS NULL
       OR m.search @@ websearch_to_tsquery('russian', $11::text)
       OR m.title ILIKE '%' || $12::text || '%' ESCAPE '\'
       OR v.original_name ILIKE '%' || $12::text || '%' ESCAPE '\')
  AND ($13::timestamptz IS NULL
       OR (m.sort_at, m.id) < ($13::timestamptz, $14::uuid))
ORDER BY m.sort_at DESC, m.id DESC
LIMIT $15
`

type ListMaterialsParams struct {
	GroupID      uuid.UUID
	Status       string
	SubjectID    *uuid.UUID
	NoSubject    bool
	Kind         *string
	UploaderID   *uuid.UUID
	Inbox        bool
	MimePatterns []string
	MimeExclude  bool
	TagIds       []uuid.UUID
	Query        *string
	LikePattern  *string
	AfterSortAt  *time.Time
	AfterID      *uuid.UUID
	MaxRows      int32
}

type ListMaterialsRow struct {
	ID               uuid.UUID
	GroupID          uuid.UUID
	SubjectID        *uuid.UUID
	UploaderID       *uuid.UUID
	Title            string
	Description      string
	Kind             string
	Source           string
	Status           string
	CurrentVersionID *uuid.UUID
	Classification   []byte
	NeedsReview      bool
	ReviewReason     *string
	DownloadCount    int32
	SortAt           time.Time
	ArchivedBy       *uuid.UUID
	ArchivedAt       *time.Time
	DeletedBy        *uuid.UUID
	DeletedAt        *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
	MaterialVersion  MaterialVersion
}

func (q *Queries) ListMaterials(ctx context.Context, arg ListMaterialsParams) ([]ListMaterialsRow, error) {
	rows, err := q.db.Query(ctx, listMaterials,
		arg.GroupID,
		arg.Status,
		arg.SubjectID,
		arg.NoSubject,
		arg.Kind,
		arg.UploaderID,
		arg.Inbox,
		arg.MimePatterns,
		arg.MimeExclude,
		arg.TagIds,
		arg.Query,
		arg.LikePattern,
		arg.AfterSortAt,
		arg.AfterID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMaterialsRow{}
	for rows.Next() {
		var i ListMaterialsRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.SubjectID,
			&i.UploaderID,
			&i.Title,
			&i.Description,
			&i.Kind,
			&i.Source,
			&i.Status,
			&i.CurrentVersionID,
			&i.Classification,
			&i.NeedsReview,
			&i.ReviewReason,
			&i.DownloadCount,
			&i.SortAt,
			&i.ArchivedBy,
			&i.ArchivedAt,
			&i.DeletedBy,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MaterialVersion.ID,
			&i.MaterialVersion.MaterialID,
			&i.MaterialVersion.VersionNo,
			&i.MaterialVersion.Storage,
			&i.MaterialVersion.StorageKey,
			&i.MaterialVersion.CacheExpiresAt,
			&i.MaterialVersion.DriveFileID,
			&i.MaterialVersion.DriveWebViewLink,
			&i.MaterialVersion.DriveMd5,
			&i.MaterialVersion.DriveModifiedTime,
			&i.MaterialVersion.DriveUploadStatus,
			&i.MaterialVersion.DriveUploadError,
			&i.MaterialVersion.OriginalName,
			&i.MaterialVersion.Mime,
			&i.MaterialVersion.SizeBytes,
			&i.MaterialVersion.Sha256,
			&i.MaterialVersion.ScanStatus,
			&i.MaterialVersion.TextKey,
			&i.MaterialVersion.PreviewKey,
			&i.MaterialVersion.UploadedBy,
			&i.MaterialVersion.CreatedAt,
			&i.MaterialVersion.DriveRevisionID,
			&i.MaterialVersion.PreviewStatus,
			&i.MaterialVersion.PreviewError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurgeableMaterials = `-- name: ListPurgeableMaterials :many
SELECT id, group_id, subject_id, uploader_id, title, description, kind, source, status, current_version_id,
       classification, needs_review, review_reason, download_count, sort_at, archived_by, archived_at,
       deleted_by, deleted_at, created_at, updated_at
FROM materials
WHERE status = 'DELETED' AND deleted_at < $1
ORDER BY deleted_at
LIMIT $2
`

type ListPurgeableMaterialsParams struct {
	DeletedAt *time.Time
	Limit     int32
}

type ListPurgeableMaterialsRow struct {
	ID               uuid.UUID
	GroupID          uuid.UUID
	SubjectID        *uuid.UUID
	UploaderID       *uuid.UUID
	Title            string
	Description      string
	Kind             string
	Source           string
	Status           string
	CurrentVersionID *uuid.UUID
	Classification   []byte
	NeedsReview      bool
	ReviewReason     *string
	DownloadCount    int32
	SortAt           time.Time
	ArchivedBy       *uuid.UUID
	ArchivedAt       *time.Time
	DeletedBy        *uuid.UUID
	DeletedAt        *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) ListPurgeableMaterials(ctx context.Context, arg ListPurgeableMaterialsParams) ([]ListPurgeableMaterialsRow, error) {
	rows, err := q.db.Query(ctx, listPurgeableMaterials, arg.DeletedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPurgeableMaterialsRow{}
	for rows.Next() {
		var i ListPurgeableMaterialsRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.SubjectID,
			&i.UploaderID,
			&i.Title,
			&i.Description,
			&i.Kind,
			&i.Source,
			&i.Status,
			&i.CurrentVersionID,
			&i.Classification,
			&i.NeedsReview,
			&i.ReviewReason,
			&i.DownloadCount,
			&i.SortAt,
			&i.ArchivedBy,
			&i.ArchivedAt,
			&i.DeletedBy,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCurrentVersion = `-- name: SetCurrentVersion :exec
UPDATE materials SET current_version_id = $2 WHERE id = $1
`

type SetCurrentVersionParams struct {
	ID               uuid.UUID
	CurrentVersionID *uuid.UUID
}

func (q *Queries) SetCurrentVersion(ctx context.Context, arg SetCurrentVersionParams) error {
	_, err := q.db.Exec(ctx, setCurrentVersion, arg.ID, arg.CurrentVersionID)
	return err
}

const setMaterialStatus = `-- name: SetMaterialStatus :one
UPDATE materials
SET status = $1,
    archived_by = CASE WHEN $1 = 'ARCHIVED' THEN $2::uuid
                       WHEN $1 = 'ACTIVE' THEN NULL ELSE archived_by END,
    archived_at = CASE WHEN $1 = 'ARCHIVED' THEN now()
                       WHEN $1 = 'ACTIVE' THEN NULL ELSE archived_at END,
    deleted_by  = CASE WHEN $1 = 'DELETED' THEN $2::uuid ELSE NULL END,
    deleted_at  = CASE WHEN $1 = 'DELETED' THEN now() ELSE NULL END
WHERE id = $3
RETURNING id, group_id, subject_id, uploader_id, title, description, kind, source, status, current_version_id,
          classification, needs_review, review_reason, download_count, sort_at, archived_by, archived_at,
          deleted_by, deleted_at, created_at, updated_at
`

type SetMaterialStatusParams struct {
	Status string
	Actor  *uuid.UUID
	ID     uuid.UUID
}

type SetMaterialStatusRow struct {
	ID               uuid.UUID
	GroupID          uuid.UUID
	SubjectID        *uuid.UUID
	UploaderID       *uuid.UUID
	Title            string
	Description      string
	Kind             string
	Source           string
	Status           string
	CurrentVersionID *uuid.UUID
	Classification   []byte
	NeedsReview      bool
	ReviewReason     *string
	DownloadCount    int32
	SortAt           time.Time
	ArchivedBy       *uuid.UUID
	ArchivedAt       *time.Time
	DeletedBy        *uuid.UUID
	DeletedAt        *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) SetMaterialStatus(ctx context.Context, arg SetMaterialStatusParams) (SetMaterialStatusRow, error) {
	row := q.db.QueryRow(ctx, setMaterialStatus, arg.Status, arg.Actor, arg.ID)
	var i SetMaterialStatusRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.SubjectID,
		&i.UploaderID,
		&i.Title,
		&i.Description,
		&i.Kind,
		&i.Source,
		&i.Status,
		&i.CurrentVersionID,
		&i.Classification,
		&i.NeedsReview,
		&i.ReviewReason,
		&i.DownloadCount,
		&i.SortAt,
		&i.ArchivedBy,
		&i.ArchivedAt,
		&i.DeletedBy,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setVersionDriveRevision = `-- name: SetVersionDriveRevision :exec
UPDATE material_versions SET drive_revision_id = $2 WHERE id = $1
`

type SetVersionDriveRevisionParams struct {
	ID              uuid.UUID
	DriveRevisionID *string
}

func (q *Queries) SetVersionDriveRevision(ctx context.Context, arg SetVersionDriveRevisionParams) error {
	_, err := q.db.Exec(ctx, setVersionDriveRevision, arg.ID, arg.DriveRevisionID)
	return err
}

const setVersionDriveUpload = `-- name: SetVersionDriveUpload :exec
UPDATE material_versions
SET drive_upload_status = $2, drive_upload_error = $3,
    drive_file_id = COALESCE($4, drive_file_id),
    drive_web_view_link = COALESCE($5, drive_web_view_link)
WHERE id = $1
`

type SetVersionDriveUploadParams struct {
	ID                uuid.UUID
	DriveUploadStatus *string
	DriveUploadError  *string
	FileID            *string
	WebViewLink       *string
}

func (q *Queries) SetVersionDriveUpload(ctx context.Context, arg SetVersionDriveUploadParams) error {
	_, err := q.db.Exec(ctx, setVersionDriveUpload,
		arg.ID,
		arg.DriveUploadStatus,
		arg.DriveUploadError,
		arg.FileID,
		arg.WebViewLink,
	)
	return err
}

const setVersionHash = `-- name: SetVersionHash :exec
UPDATE material_versions SET sha256 = $2 WHERE id = $1
`

type SetVersionHashParams struct {
	ID     uuid.UUID
	Sha256 *string
}

func (q *Queries) SetVersionHash(ctx context.Context, arg SetVersionHashParams) error {
	_, err := q.db.Exec(ctx, setVersionHash, arg.ID, arg.Sha256)
	return err
}

const setVersionPreview = `-- name: SetVersionPreview :exec
UPDATE material_versions
SET preview_status = $2, preview_key = $3, preview_error = $4
WHERE id = $1
`

type SetVersionPreviewParams struct {
	ID            uuid.UUID
	PreviewStatus *string
	PreviewKey    *string
	PreviewError  *string
}

func (q *Queries) SetVersionPreview(ctx context.Context, arg SetVersionPreviewParams) error {
	_, err := q.db.Exec(ctx, setVersionPreview,
		arg.ID,
		arg.PreviewStatus,
		arg.PreviewKey,
		arg.PreviewError,
	)
	return err
}

const updateMaterial = `-- name: UpdateMaterial :one
UPDATE materials
SET title = $2, description = $3, subject_id = $4, kind = $5, classification = $6,
    needs_review = $7, review_reason = $8
WHERE id = $1
RETURNING id, group_id, subject_id, uploader_id, title, description, kind, source, status, current_version_id,
          classification, needs_review, review_reason, download_count, sort_at, archived_by, archived_at,
          deleted_by, deleted_at, created_at, updated_at
`

type UpdateMaterialParams struct {
	ID             uuid.UUID
	Title          string
	Description    string
	SubjectID      *uuid.UUID
	Kind           string
	Classification []byte
	NeedsReview    bool
	ReviewReason   *string
}

type UpdateMaterialRow struct {
	ID               uuid.UUID
	GroupID          uuid.UUID
	SubjectID        *uuid.UUID
	UploaderID       *uuid.UUID
	Title            string
	Description      string
	Kind             string
	Source           string
	Status           string
	CurrentVersionID *uuid.UUID
	Classification   []byte
	NeedsReview      bool
	ReviewReason     *string
	DownloadCount    int32
	SortAt           time.Time
	ArchivedBy       *uuid.UUID
	ArchivedAt       *time.Time
	DeletedBy        *uuid.UUID
	DeletedAt        *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) UpdateMaterial(ctx context.Context, arg UpdateMaterialParams) (UpdateMaterialRow, error) {
	row := q.db.QueryRow(ctx, updateMaterial,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.SubjectID,
		arg.Kind,
		arg.Classification,
		arg.NeedsReview,
		arg.ReviewReason,
	)
	var i UpdateMaterialRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.SubjectID,
		&i.UploaderID,
		&i.Title,
		&i.Description,
		&i.Kind,
		&i.Source,
		&i.Status,
		&i.CurrentVersionID,
		&i.Classification,
		&i.NeedsReview,
		&i.ReviewReason,
		&i.DownloadCount,
		&i.SortAt,
		&i.ArchivedBy,
		&i.ArchivedAt,
		&i.DeletedBy,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVersionFile = `-- name: UpdateVersionFile :exec
UPDATE material_versions
SET original_name = $2, mime = $3, size_bytes = $4, drive_web_view_link = $5, drive_md5 = $6, drive_modified_time = $7,
    drive_revision_id = COALESCE($8, drive_revision_id)
WHERE id = $1
`

type UpdateVersionFileParams struct {
	ID                uuid.UUID
	OriginalName      string
	Mime              string
	SizeBytes         int64
	DriveWebViewLink  *string
	DriveMd5          *string
	DriveModifiedTime *time.Time
	DriveRevisionID   *string
}

func (q *Queries) UpdateVersionFile(ctx context.Context, arg UpdateVersionFileParams) error {
	_, err := q.db.Exec(ctx, updateVersionFile,
		arg.ID,
		arg.OriginalName,
		arg.Mime,
		arg.SizeBytes,
		arg.DriveWebViewLink,
		arg.DriveMd5,
		arg.DriveModifiedTime,
		arg.DriveRevisionID,
	)
	return err
}
