// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memberships.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const countActiveMembers = `-- name: CountActiveMembers :one
SELECT count(*) FROM memberships WHERE group_id = $1 AND status = 'ACTIVE'
`

func (q *Queries) CountActiveMembers(ctx context.Context, groupID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveMembers, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMembership = `-- name: CreateMembership :one
INSERT INTO memberships (id, user_id, group_id, roles, status, joined_via)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, group_id, roles, status, joined_via, joined_at, created_at, updated_at
`

type CreateMembershipParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	GroupID   uuid.UUID
	Roles     []string
	Status    string
	JoinedVia string
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, createMembership,
		arg.ID,
		arg.UserID,
		arg.GroupID,
		arg.Roles,
		arg.Status,
		arg.JoinedVia,
	)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.Roles,
		&i.Status,
		&i.JoinedVia,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMembership = `-- name: GetMembership :one
SELECT id, user_id, group_id, roles, status, joined_via, joined_at, created_at, updated_at FROM memberships WHERE user_id = $1 AND group_id = $2
`

type GetMembershipParams struct {
	UserID  uuid.UUID
	GroupID uuid.UUID
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.UserID, arg.GroupID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.Roles,
		&i.Status,
		&i.JoinedVia,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMembershipByID = `-- name: GetMembershipByID :one
SELECT id, user_id, group_id, roles, status, joined_via, joined_at, created_at, updated_at FROM memberships WHERE id = $1
`

func (q *Queries) GetMembershipByID(ctx context.Context, id uuid.UUID) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembershipByID, id)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.Roles,
		&i.Status,
		&i.JoinedVia,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveMemberUserIDs = `-- name: ListActiveMemberUserIDs :many
SELECT user_id FROM memberships WHERE group_id = $1 AND status = 'ACTIVE'
`

func (q *Queries) ListActiveMemberUserIDs(ctx context.Context, groupID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listActiveMemberUserIDs, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT memberships.id, memberships.user_id, memberships.group_id, memberships.roles, memberships.status, memberships.joined_via, memberships.joined_at, memberships.created_at, memberships.updated_at, users.id, users.name, users.email, users.password_hash, users.locale, users.timezone, users.avatar_key, users.global_role, users.settings, users.secured_at, users.created_at, users.updated_at, users.deleted_at
FROM memberships
JOIN users ON users.id = memberships.user_id
WHERE memberships.group_id = $1 AND users.deleted_at IS NULL
ORDER BY memberships.joined_at
`

type ListMembersRow struct {
	Membership Membership
	User       User
}

func (q *Queries) ListMembers(ctx context.Context, groupID uuid.UUID) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersRow{}
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.Membership.ID,
			&i.Membership.UserID,
			&i.Membership.GroupID,
			&i.Membership.Roles,
			&i.Membership.Status,
			&i.Membership.JoinedVia,
			&i.Membership.JoinedAt,
			&i.Membership.CreatedAt,
			&i.Membership.UpdatedAt,
			&i.User.ID,
			&i.User.Name,
			&i.User.Email,
			&i.User.PasswordHash,
			&i.User.Locale,
			&i.User.Timezone,
			&i.User.AvatarKey,
			&i.User.GlobalRole,
			&i.User.Settings,
			&i.User.SecuredAt,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.User.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMembershipRoles = `-- name: UpdateMembershipRoles :one
UPDATE memberships SET roles = $3 WHERE user_id = $1 AND group_id = $2 RETURNING id, user_id, group_id, roles, status, joined_via, joined_at, created_at, updated_at
`

type UpdateMembershipRolesParams struct {
	UserID  uuid.UUID
	GroupID uuid.UUID
	Roles   []string
}

func (q *Queries) UpdateMembershipRoles(ctx context.Context, arg UpdateMembershipRolesParams) (Membership, error) {
	row := q.db.QueryRow(ctx, updateMembershipRoles, arg.UserID, arg.GroupID, arg.Roles)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.Roles,
		&i.Status,
		&i.JoinedVia,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMembershipStatus = `-- name: UpdateMembershipStatus :one
UPDATE memberships SET status = $3 WHERE user_id = $1 AND group_id = $2 RETURNING id, user_id, group_id, roles, status, joined_via, joined_at, created_at, updated_at
`

type UpdateMembershipStatusParams struct {
	UserID  uuid.UUID
	GroupID uuid.UUID
	Status  string
}

func (q *Queries) UpdateMembershipStatus(ctx context.Context, arg UpdateMembershipStatusParams) (Membership, error) {
	row := q.db.QueryRow(ctx, updateMembershipStatus, arg.UserID, arg.GroupID, arg.Status)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.Roles,
		&i.Status,
		&i.JoinedVia,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
