// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
)

type AuthIdentity struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	Provider        string
	ProviderUserID  string
	Email           *string
	RefreshTokenEnc []byte
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Device struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	Platform         string
	Name             *string
	PushProvider     *string
	PushToken        *string
	PushSubscription []byte
	Enabled          bool
	LastSeenAt       time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type Group struct {
	ID         uuid.UUID
	Name       string
	Slug       string
	Kind       string
	JoinPolicy string
	JoinCode   *string
	PublicRead bool
	MediaMode  string
	Settings   []byte
	LastSeq    int64
	CreatedBy  uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	ArchivedAt *time.Time
}

type GroupEvent struct {
	ID         uuid.UUID
	GroupID    uuid.UUID
	Seq        int64
	Kind       string
	ActorID    *uuid.UUID
	EntityType string
	EntityID   *uuid.UUID
	Payload    []byte
	Audit      bool
	CreatedAt  time.Time
}

type Invite struct {
	ID        uuid.UUID
	GroupID   uuid.UUID
	Code      string
	Roles     []string
	ExpiresAt *time.Time
	MaxUses   *int32
	Uses      int32
	CreatedBy uuid.UUID
	RevokedAt *time.Time
	CreatedAt time.Time
}

type Membership struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	GroupID   uuid.UUID
	Roles     []string
	Status    string
	JoinedVia string
	JoinedAt  time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type RefreshToken struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	DeviceID   *uuid.UUID
	TokenHash  string
	ExpiresAt  time.Time
	RevokedAt  *time.Time
	ReplacedBy *uuid.UUID
	CreatedAt  time.Time
}

type Subject struct {
	ID             uuid.UUID
	GroupID        uuid.UUID
	Name           string
	ShortName      *string
	Teacher        *string
	TeacherContact *string
	Color          *string
	Semester       *string
	Aliases        []string
	SortOrder      int32
	CreatedBy      *uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	ArchivedAt     *time.Time
}

type Tag struct {
	ID        uuid.UUID
	GroupID   uuid.UUID
	Name      string
	Slug      string
	Color     *string
	Kind      string
	SubjectID *uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID           uuid.UUID
	Name         string
	Email        *string
	PasswordHash *string
	Locale       string
	Timezone     string
	AvatarKey    *string
	GlobalRole   string
	Settings     []byte
	SecuredAt    *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    *time.Time
}
