// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
)

type AuthIdentity struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	Provider        string
	ProviderUserID  string
	Email           *string
	RefreshTokenEnc []byte
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Device struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	Platform         string
	Name             *string
	PushProvider     *string
	PushToken        *string
	PushSubscription []byte
	Enabled          bool
	LastSeenAt       time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type DriveConnection struct {
	ID               uuid.UUID
	GroupID          uuid.UUID
	Mode             string
	RootFolderID     string
	RootFolderName   string
	DriveID          *string
	Status           string
	LastError        *string
	SyncStartedAt    *time.Time
	LastSyncAt       *time.Time
	LastFullScanAt   *time.Time
	ChangesPageToken *string
	SyncIntervalSec  int32
	Writable         bool
	CreatedBy        *uuid.UUID
	CreatedAt        time.Time
	UpdatedAt        time.Time
	LastErrorCode    *string
}

type DriveItem struct {
	ID             uuid.UUID
	ConnectionID   uuid.UUID
	DriveFileID    string
	ParentID       *string
	PathCache      string
	Name           string
	Mime           string
	IsFolder       bool
	Md5            *string
	SizeBytes      *int64
	ModifiedTime   *time.Time
	WebViewLink    *string
	MaterialID     *uuid.UUID
	State          string
	Classification []byte
	LastError      *string
	SeenAt         time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type DrivePublisher struct {
	GroupID         uuid.UUID
	GoogleEmail     string
	RefreshTokenEnc []byte
	Scopes          string
	LastError       *string
	ConnectedBy     *uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Group struct {
	ID         uuid.UUID
	Name       string
	Slug       string
	Kind       string
	JoinPolicy string
	JoinCode   *string
	PublicRead bool
	MediaMode  string
	Settings   []byte
	LastSeq    int64
	CreatedBy  uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	ArchivedAt *time.Time
}

type GroupEvent struct {
	ID         uuid.UUID
	GroupID    uuid.UUID
	Seq        int64
	Kind       string
	ActorID    *uuid.UUID
	EntityType string
	EntityID   *uuid.UUID
	Payload    []byte
	Audit      bool
	CreatedAt  time.Time
}

type Invite struct {
	ID        uuid.UUID
	GroupID   uuid.UUID
	Code      string
	Roles     []string
	ExpiresAt *time.Time
	MaxUses   *int32
	Uses      int32
	CreatedBy uuid.UUID
	RevokedAt *time.Time
	CreatedAt time.Time
}

type Material struct {
	ID               uuid.UUID
	GroupID          uuid.UUID
	SubjectID        *uuid.UUID
	UploaderID       *uuid.UUID
	Title            string
	Description      string
	Kind             string
	Source           string
	Status           string
	CurrentVersionID *uuid.UUID
	Classification   []byte
	NeedsReview      bool
	ReviewReason     *string
	DownloadCount    int32
	SortAt           time.Time
	Search           interface{}
	ArchivedBy       *uuid.UUID
	ArchivedAt       *time.Time
	DeletedBy        *uuid.UUID
	DeletedAt        *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
	TaskID           *uuid.UUID
}

type MaterialTag struct {
	MaterialID uuid.UUID
	TagID      uuid.UUID
}

type MaterialVersion struct {
	ID                uuid.UUID
	MaterialID        uuid.UUID
	VersionNo         int32
	Storage           string
	StorageKey        *string
	CacheExpiresAt    *time.Time
	DriveFileID       *string
	DriveWebViewLink  *string
	DriveMd5          *string
	DriveModifiedTime *time.Time
	DriveUploadStatus *string
	DriveUploadError  *string
	OriginalName      string
	Mime              string
	SizeBytes         int64
	Sha256            *string
	ScanStatus        string
	TextKey           *string
	PreviewKey        *string
	UploadedBy        *uuid.UUID
	CreatedAt         time.Time
	DriveRevisionID   *string
	PreviewStatus     *string
	PreviewError      *string
}

type Membership struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	GroupID   uuid.UUID
	Roles     []string
	Status    string
	JoinedVia string
	JoinedAt  time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Message struct {
	ID             uuid.UUID
	GroupID        uuid.UUID
	ThreadID       uuid.UUID
	AuthorID       *uuid.UUID
	ClientID       uuid.UUID
	Seq            int64
	Body           string
	ReplyToID      *uuid.UUID
	EditedAt       *time.Time
	DeletedAt      *time.Time
	HiddenForAllBy *uuid.UUID
	HiddenForAllAt *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type MessageHide struct {
	MessageID uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
}

type RefreshToken struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	DeviceID   *uuid.UUID
	TokenHash  string
	ExpiresAt  time.Time
	RevokedAt  *time.Time
	ReplacedBy *uuid.UUID
	CreatedAt  time.Time
}

type Subject struct {
	ID             uuid.UUID
	GroupID        uuid.UUID
	Name           string
	ShortName      *string
	Teacher        *string
	TeacherContact *string
	Color          *string
	Semester       *string
	Aliases        []string
	SortOrder      int32
	CreatedBy      *uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	ArchivedAt     *time.Time
}

type Tag struct {
	ID        uuid.UUID
	GroupID   uuid.UUID
	Name      string
	Slug      string
	Color     *string
	Kind      string
	SubjectID *uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Task struct {
	ID              uuid.UUID
	GroupID         uuid.UUID
	SubjectID       *uuid.UUID
	CreatedBy       *uuid.UUID
	ClientID        *uuid.UUID
	Title           string
	Description     string
	Kind            string
	Status          string
	Priority        string
	AssignMode      string
	Visibility      string
	DueAt           *time.Time
	NotifiedOffsets []int32
	PinnedBy        *uuid.UUID
	PinnedAt        *time.Time
	CompletedAt     *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       *time.Time
}

type TaskAssignment struct {
	TaskID      uuid.UUID
	UserID      uuid.UUID
	Status      string
	CompletedAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type TaskAttachment struct {
	TaskID     uuid.UUID
	MaterialID uuid.UUID
	CreatedAt  time.Time
}

type Thread struct {
	ID            uuid.UUID
	GroupID       uuid.UUID
	TargetType    string
	TargetID      uuid.UUID
	SubjectID     *uuid.UUID
	Title         *string
	CreatedBy     *uuid.UUID
	MessageCount  int32
	LastMessageAt *time.Time
	LastSeq       int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type ThreadRead struct {
	ThreadID    uuid.UUID
	UserID      uuid.UUID
	LastReadSeq int64
	UpdatedAt   time.Time
}

type Upload struct {
	ID          uuid.UUID
	GroupID     uuid.UUID
	UserID      uuid.UUID
	Storage     string
	StorageKey  string
	FileName    string
	Mime        string
	SizeBytes   int64
	Meta        []byte
	Status      string
	MaterialID  *uuid.UUID
	ExpiresAt   time.Time
	CompletedAt *time.Time
	CreatedAt   time.Time
}

type User struct {
	ID               uuid.UUID
	Name             string
	Email            *string
	PasswordHash     *string
	Locale           string
	Timezone         string
	AvatarKey        *string
	GlobalRole       string
	Settings         []byte
	SecuredAt        *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
	DeletedAt        *time.Time
	RegisterClientID *uuid.UUID
}
