// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*)::int FROM notifications
WHERE user_id = $1::uuid
  AND read_at IS NULL
  AND ($2::uuid IS NULL OR group_id = $2::uuid)
`

type CountUnreadNotificationsParams struct {
	UserID  uuid.UUID
	GroupID *uuid.UUID
}

func (q *Queries) CountUnreadNotifications(ctx context.Context, arg CountUnreadNotificationsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, arg.UserID, arg.GroupID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteExpiredNotificationMutes = `-- name: DeleteExpiredNotificationMutes :execrows
DELETE FROM notification_mutes WHERE until <= $1
`

func (q *Queries) DeleteExpiredNotificationMutes(ctx context.Context, until time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredNotificationMutes, until)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteNotificationMute = `-- name: DeleteNotificationMute :execrows
DELETE FROM notification_mutes
WHERE user_id = $1::uuid AND group_id = $2::uuid
  AND scope_type = $3::text AND scope_id = $4::text
`

type DeleteNotificationMuteParams struct {
	UserID    uuid.UUID
	GroupID   uuid.UUID
	ScopeType string
	ScopeID   string
}

func (q *Queries) DeleteNotificationMute(ctx context.Context, arg DeleteNotificationMuteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNotificationMute,
		arg.UserID,
		arg.GroupID,
		arg.ScopeType,
		arg.ScopeID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldNotifications = `-- name: DeleteOldNotifications :execrows
DELETE FROM notifications WHERE created_at < $1
`

func (q *Queries) DeleteOldNotifications(ctx context.Context, createdAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldNotifications, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNotificationSettings = `-- name: GetNotificationSettings :one
SELECT user_id, push_enabled, quiet_from, quiet_to, updated_at, urgent_in_quiet FROM notification_settings WHERE user_id = $1
`

func (q *Queries) GetNotificationSettings(ctx context.Context, userID uuid.UUID) (NotificationSetting, error) {
	row := q.db.QueryRow(ctx, getNotificationSettings, userID)
	var i NotificationSetting
	err := row.Scan(
		&i.UserID,
		&i.PushEnabled,
		&i.QuietFrom,
		&i.QuietTo,
		&i.UpdatedAt,
		&i.UrgentInQuiet,
	)
	return i, err
}

const getNotifierCursor = `-- name: GetNotifierCursor :one
SELECT last_seq FROM notifier_cursors WHERE group_id = $1
`

func (q *Queries) GetNotifierCursor(ctx context.Context, groupID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getNotifierCursor, groupID)
	var last_seq int64
	err := row.Scan(&last_seq)
	return last_seq, err
}

const getNotifyMaterialOwner = `-- name: GetNotifyMaterialOwner :one
SELECT uploader_id FROM materials WHERE id = $1
`

func (q *Queries) GetNotifyMaterialOwner(ctx context.Context, id uuid.UUID) (*uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getNotifyMaterialOwner, id)
	var uploader_id *uuid.UUID
	err := row.Scan(&uploader_id)
	return uploader_id, err
}

const getNotifyMessage = `-- name: GetNotifyMessage :one
SELECT m.id, m.thread_id, m.seq, m.author_id, m.reply_to_id, m.deleted_at, m.hidden_for_all_at,
       left(m.body, 300)::text AS body,
       COALESCE(u.name, '')::text AS author_name,
       t.target_type, t.target_id, t.subject_id, t.title,
       COALESCE(s.name, '')::text AS subject_name,
       r.author_id AS reply_author_id
FROM messages m
JOIN threads t ON t.id = m.thread_id
LEFT JOIN users u ON u.id = m.author_id
LEFT JOIN subjects s ON s.id = t.subject_id
LEFT JOIN messages r ON r.id = m.reply_to_id
WHERE m.id = $1
`

type GetNotifyMessageRow struct {
	ID             uuid.UUID
	ThreadID       uuid.UUID
	Seq            int64
	AuthorID       *uuid.UUID
	ReplyToID      *uuid.UUID
	DeletedAt      *time.Time
	HiddenForAllAt *time.Time
	Body           string
	AuthorName     string
	TargetType     string
	TargetID       uuid.UUID
	SubjectID      *uuid.UUID
	Title          *string
	SubjectName    string
	ReplyAuthorID  *uuid.UUID
}

// The text a push carries, with its author and discussion.
func (q *Queries) GetNotifyMessage(ctx context.Context, id uuid.UUID) (GetNotifyMessageRow, error) {
	row := q.db.QueryRow(ctx, getNotifyMessage, id)
	var i GetNotifyMessageRow
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.Seq,
		&i.AuthorID,
		&i.ReplyToID,
		&i.DeletedAt,
		&i.HiddenForAllAt,
		&i.Body,
		&i.AuthorName,
		&i.TargetType,
		&i.TargetID,
		&i.SubjectID,
		&i.Title,
		&i.SubjectName,
		&i.ReplyAuthorID,
	)
	return i, err
}

const getNotifySubjectName = `-- name: GetNotifySubjectName :one
SELECT COALESCE(name, '')::text FROM subjects WHERE id = $1
`

func (q *Queries) GetNotifySubjectName(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getNotifySubjectName, id)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const getNotifyTask = `-- name: GetNotifyTask :one
SELECT id, group_id, subject_id, created_by, title, assign_mode, visibility, due_at FROM tasks WHERE id = $1
`

type GetNotifyTaskRow struct {
	ID         uuid.UUID
	GroupID    uuid.UUID
	SubjectID  *uuid.UUID
	CreatedBy  *uuid.UUID
	Title      string
	AssignMode string
	Visibility string
	DueAt      *time.Time
}

func (q *Queries) GetNotifyTask(ctx context.Context, id uuid.UUID) (GetNotifyTaskRow, error) {
	row := q.db.QueryRow(ctx, getNotifyTask, id)
	var i GetNotifyTaskRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.SubjectID,
		&i.CreatedBy,
		&i.Title,
		&i.AssignMode,
		&i.Visibility,
		&i.DueAt,
	)
	return i, err
}

const getNotifyUserName = `-- name: GetNotifyUserName :one
SELECT COALESCE(name, '')::text FROM users WHERE id = $1
`

func (q *Queries) GetNotifyUserName(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getNotifyUserName, id)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const insertNotification = `-- name: InsertNotification :many
INSERT INTO notifications (id, user_id, group_id, type, title, body, data, seq, dedupe_key)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (user_id, dedupe_key) DO NOTHING
RETURNING id, user_id, group_id, type, title, body, data, seq, dedupe_key, read_at, created_at
`

type InsertNotificationParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	GroupID   uuid.UUID
	Type      string
	Title     string
	Body      string
	Data      []byte
	Seq       int64
	DedupeKey string
}

// Returns nothing when the same fact was already delivered to this user.
func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, insertNotification,
		arg.ID,
		arg.UserID,
		arg.GroupID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.Data,
		arg.Seq,
		arg.DedupeKey,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GroupID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Data,
			&i.Seq,
			&i.DedupeKey,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertNotificationDelivery = `-- name: InsertNotificationDelivery :exec
INSERT INTO notification_deliveries (id, notification_id, channel, device_id, status, error, sent_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertNotificationDeliveryParams struct {
	ID             uuid.UUID
	NotificationID uuid.UUID
	Channel        string
	DeviceID       *uuid.UUID
	Status         string
	Error          *string
	SentAt         *time.Time
}

func (q *Queries) InsertNotificationDelivery(ctx context.Context, arg InsertNotificationDeliveryParams) error {
	_, err := q.db.Exec(ctx, insertNotificationDelivery,
		arg.ID,
		arg.NotificationID,
		arg.Channel,
		arg.DeviceID,
		arg.Status,
		arg.Error,
		arg.SentAt,
	)
	return err
}

const listGroupsWithPendingEvents = `-- name: ListGroupsWithPendingEvents :many
SELECT g.id
FROM groups g
LEFT JOIN notifier_cursors c ON c.group_id = g.id
WHERE g.archived_at IS NULL AND g.last_seq > COALESCE(c.last_seq, 0)
ORDER BY g.id
LIMIT $1
`

// Groups whose log has moved past the reader. A new group starts at its
// current head: nobody is notified about what happened before they joined.
func (q *Queries) ListGroupsWithPendingEvents(ctx context.Context, limit int32) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listGroupsWithPendingEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationMutes = `-- name: ListNotificationMutes :many
SELECT id, user_id, group_id, scope_type, scope_id, until, created_at FROM notification_mutes
WHERE user_id = $1::uuid
  AND until > now()
  AND ($2::uuid IS NULL OR group_id = $2::uuid)
ORDER BY until
`

type ListNotificationMutesParams struct {
	UserID  uuid.UUID
	GroupID *uuid.UUID
}

func (q *Queries) ListNotificationMutes(ctx context.Context, arg ListNotificationMutesParams) ([]NotificationMute, error) {
	rows, err := q.db.Query(ctx, listNotificationMutes, arg.UserID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationMute{}
	for rows.Next() {
		var i NotificationMute
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GroupID,
			&i.ScopeType,
			&i.ScopeID,
			&i.Until,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationPrefs = `-- name: ListNotificationPrefs :many
SELECT user_id, group_id, type, enabled, updated_at FROM notification_prefs WHERE user_id = $1 AND group_id = $2
`

type ListNotificationPrefsParams struct {
	UserID  uuid.UUID
	GroupID uuid.UUID
}

func (q *Queries) ListNotificationPrefs(ctx context.Context, arg ListNotificationPrefsParams) ([]NotificationPref, error) {
	rows, err := q.db.Query(ctx, listNotificationPrefs, arg.UserID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationPref{}
	for rows.Next() {
		var i NotificationPref
		if err := rows.Scan(
			&i.UserID,
			&i.GroupID,
			&i.Type,
			&i.Enabled,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, user_id, group_id, type, title, body, data, seq, dedupe_key, read_at, created_at FROM notifications
WHERE user_id = $1::uuid
  AND ($2::uuid IS NULL OR group_id = $2::uuid)
  AND (NOT $3::boolean OR read_at IS NULL)
  AND ($4::timestamptz IS NULL
       OR created_at < $4::timestamptz
       OR (created_at = $4::timestamptz AND id < $5::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $6::int
`

type ListNotificationsParams struct {
	UserID     uuid.UUID
	GroupID    *uuid.UUID
	UnreadOnly bool
	Before     *time.Time
	BeforeID   *uuid.UUID
	Lim        int32
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.UserID,
		arg.GroupID,
		arg.UnreadOnly,
		arg.Before,
		arg.BeforeID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GroupID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Data,
			&i.Seq,
			&i.DedupeKey,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsForPush = `-- name: ListNotificationsForPush :many
SELECT id, user_id, group_id, type, title, body, data, seq, dedupe_key, read_at, created_at FROM notifications WHERE id = ANY ($1::uuid[]) ORDER BY created_at
`

func (q *Queries) ListNotificationsForPush(ctx context.Context, ids []uuid.UUID) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsForPush, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GroupID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Data,
			&i.Seq,
			&i.DedupeKey,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifyRecipients = `-- name: ListNotifyRecipients :many
SELECT m.user_id, COALESCE(u.timezone, 'UTC')::text AS timezone
FROM memberships m
JOIN users u ON u.id = m.user_id
LEFT JOIN notification_prefs p
  ON p.user_id = m.user_id AND p.group_id = m.group_id AND p.type = $1::text
WHERE m.group_id = $2::uuid
  AND m.status = 'ACTIVE'
  AND m.user_id <> ALL ($3::uuid[])
  AND COALESCE(p.enabled, $4::boolean)
  AND NOT EXISTS (
    SELECT 1 FROM notification_mutes mu
    WHERE mu.user_id = m.user_id
      AND mu.group_id = m.group_id
      AND mu.until > $5::timestamptz
      AND ((mu.scope_type = 'GROUP' AND mu.scope_id = m.group_id::text)
        OR (mu.scope_type = 'TYPE' AND mu.scope_id = $1::text)
        OR (mu.scope_type = 'SUBJECT' AND mu.scope_id = $6::text)
        OR (mu.scope_type = 'THREAD' AND mu.scope_id = $7::text))
  )
  AND ($7::text IS NULL OR NOT EXISTS (
    SELECT 1 FROM thread_reads r
    WHERE r.thread_id = $7::uuid
      AND r.user_id = m.user_id
      AND r.last_read_seq >= $8::bigint
  ))
ORDER BY m.user_id
`

type ListNotifyRecipientsParams struct {
	Type           string
	GroupID        uuid.UUID
	Exclude        []uuid.UUID
	DefaultEnabled bool
	Now            time.Time
	SubjectID      *string
	ThreadID       *string
	Seq            int64
}

type ListNotifyRecipientsRow struct {
	UserID   uuid.UUID
	Timezone string
}

// Active members of a group who want this type of notification: not the
// actor, not switched off, not muted, and — for a discussion — not people who
// have already read the message on another screen.
func (q *Queries) ListNotifyRecipients(ctx context.Context, arg ListNotifyRecipientsParams) ([]ListNotifyRecipientsRow, error) {
	rows, err := q.db.Query(ctx, listNotifyRecipients,
		arg.Type,
		arg.GroupID,
		arg.Exclude,
		arg.DefaultEnabled,
		arg.Now,
		arg.SubjectID,
		arg.ThreadID,
		arg.Seq,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotifyRecipientsRow{}
	for rows.Next() {
		var i ListNotifyRecipientsRow
		if err := rows.Scan(&i.UserID, &i.Timezone); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPushTargets = `-- name: ListPushTargets :many
SELECT d.id AS device_id, d.user_id, d.platform, d.push_provider, d.push_token,
       COALESCE(u.timezone, 'UTC')::text AS timezone,
       COALESCE(s.push_enabled, true)::boolean AS push_enabled,
       s.quiet_from, s.quiet_to,
       COALESCE(s.urgent_in_quiet, false)::boolean AS urgent_in_quiet
FROM devices d
JOIN users u ON u.id = d.user_id
LEFT JOIN notification_settings s ON s.user_id = d.user_id
WHERE d.user_id = ANY ($1::uuid[])
  AND d.enabled
  AND d.push_provider = 'EXPO'
  AND d.push_token IS NOT NULL AND d.push_token <> ''
`

type ListPushTargetsRow struct {
	DeviceID      uuid.UUID
	UserID        uuid.UUID
	Platform      string
	PushProvider  *string
	PushToken     *string
	Timezone      string
	PushEnabled   bool
	QuietFrom     *int16
	QuietTo       *int16
	UrgentInQuiet bool
}

// Devices to push to, with the owner's quiet hours and timezone.
func (q *Queries) ListPushTargets(ctx context.Context, userIds []uuid.UUID) ([]ListPushTargetsRow, error) {
	rows, err := q.db.Query(ctx, listPushTargets, userIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPushTargetsRow{}
	for rows.Next() {
		var i ListPushTargetsRow
		if err := rows.Scan(
			&i.DeviceID,
			&i.UserID,
			&i.Platform,
			&i.PushProvider,
			&i.PushToken,
			&i.Timezone,
			&i.PushEnabled,
			&i.QuietFrom,
			&i.QuietTo,
			&i.UrgentInQuiet,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskAssignees = `-- name: ListTaskAssignees :many
SELECT a.user_id, a.status FROM task_assignments a WHERE a.task_id = $1
`

type ListTaskAssigneesRow struct {
	UserID uuid.UUID
	Status string
}

// Everybody with their own part of a task, done or not.
func (q *Queries) ListTaskAssignees(ctx context.Context, taskID uuid.UUID) ([]ListTaskAssigneesRow, error) {
	rows, err := q.db.Query(ctx, listTaskAssignees, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskAssigneesRow{}
	for rows.Next() {
		var i ListTaskAssigneesRow
		if err := rows.Scan(&i.UserID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadParticipants = `-- name: ListThreadParticipants :many
SELECT DISTINCT author_id AS user_id FROM messages
WHERE thread_id = $1 AND author_id IS NOT NULL AND deleted_at IS NULL
`

// Everybody who has written in a discussion — the people it belongs to when
// the whole group is not meant to hear about it (open question №7).
func (q *Queries) ListThreadParticipants(ctx context.Context, threadID uuid.UUID) ([]*uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listThreadParticipants, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*uuid.UUID{}
	for rows.Next() {
		var user_id *uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationsRead = `-- name: MarkNotificationsRead :execrows
UPDATE notifications SET read_at = now()
WHERE user_id = $1::uuid
  AND read_at IS NULL
  AND ($2::uuid IS NULL OR group_id = $2::uuid)
  AND ($3::boolean OR id = ANY ($4::uuid[]))
`

type MarkNotificationsReadParams struct {
	UserID    uuid.UUID
	GroupID   *uuid.UUID
	AllOfThem bool
	Ids       []uuid.UUID
}

func (q *Queries) MarkNotificationsRead(ctx context.Context, arg MarkNotificationsReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationsRead,
		arg.UserID,
		arg.GroupID,
		arg.AllOfThem,
		arg.Ids,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveNotificationSettings = `-- name: SaveNotificationSettings :one
INSERT INTO notification_settings (user_id, push_enabled, quiet_from, quiet_to, urgent_in_quiet)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id) DO UPDATE
SET push_enabled = EXCLUDED.push_enabled, quiet_from = EXCLUDED.quiet_from,
    quiet_to = EXCLUDED.quiet_to, urgent_in_quiet = EXCLUDED.urgent_in_quiet
RETURNING user_id, push_enabled, quiet_from, quiet_to, updated_at, urgent_in_quiet
`

type SaveNotificationSettingsParams struct {
	UserID        uuid.UUID
	PushEnabled   bool
	QuietFrom     *int16
	QuietTo       *int16
	UrgentInQuiet bool
}

func (q *Queries) SaveNotificationSettings(ctx context.Context, arg SaveNotificationSettingsParams) (NotificationSetting, error) {
	row := q.db.QueryRow(ctx, saveNotificationSettings,
		arg.UserID,
		arg.PushEnabled,
		arg.QuietFrom,
		arg.QuietTo,
		arg.UrgentInQuiet,
	)
	var i NotificationSetting
	err := row.Scan(
		&i.UserID,
		&i.PushEnabled,
		&i.QuietFrom,
		&i.QuietTo,
		&i.UpdatedAt,
		&i.UrgentInQuiet,
	)
	return i, err
}

const setNotificationMute = `-- name: SetNotificationMute :one
INSERT INTO notification_mutes (id, user_id, group_id, scope_type, scope_id, until)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, group_id, scope_type, scope_id) DO UPDATE SET until = EXCLUDED.until
RETURNING id, user_id, group_id, scope_type, scope_id, until, created_at
`

type SetNotificationMuteParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	GroupID   uuid.UUID
	ScopeType string
	ScopeID   string
	Until     time.Time
}

func (q *Queries) SetNotificationMute(ctx context.Context, arg SetNotificationMuteParams) (NotificationMute, error) {
	row := q.db.QueryRow(ctx, setNotificationMute,
		arg.ID,
		arg.UserID,
		arg.GroupID,
		arg.ScopeType,
		arg.ScopeID,
		arg.Until,
	)
	var i NotificationMute
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.ScopeType,
		&i.ScopeID,
		&i.Until,
		&i.CreatedAt,
	)
	return i, err
}

const setNotificationPref = `-- name: SetNotificationPref :exec
INSERT INTO notification_prefs (user_id, group_id, type, enabled)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, group_id, type) DO UPDATE SET enabled = EXCLUDED.enabled
`

type SetNotificationPrefParams struct {
	UserID  uuid.UUID
	GroupID uuid.UUID
	Type    string
	Enabled bool
}

func (q *Queries) SetNotificationPref(ctx context.Context, arg SetNotificationPrefParams) error {
	_, err := q.db.Exec(ctx, setNotificationPref,
		arg.UserID,
		arg.GroupID,
		arg.Type,
		arg.Enabled,
	)
	return err
}

const setNotifierCursor = `-- name: SetNotifierCursor :exec
INSERT INTO notifier_cursors (group_id, last_seq, updated_at)
VALUES ($1, $2, now())
ON CONFLICT (group_id) DO UPDATE SET last_seq = GREATEST(notifier_cursors.last_seq, EXCLUDED.last_seq), updated_at = now()
`

type SetNotifierCursorParams struct {
	GroupID uuid.UUID
	LastSeq int64
}

func (q *Queries) SetNotifierCursor(ctx context.Context, arg SetNotifierCursorParams) error {
	_, err := q.db.Exec(ctx, setNotifierCursor, arg.GroupID, arg.LastSeq)
	return err
}
