// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reminders.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createReminder = `-- name: CreateReminder :one
INSERT INTO reminders (id, group_id, user_id, title, note, remind_at, repeat, target_type, target_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, group_id, user_id, title, note, remind_at, repeat, target_type, target_id, status, last_fired_at, created_at, updated_at
`

type CreateReminderParams struct {
	ID         uuid.UUID
	GroupID    uuid.UUID
	UserID     uuid.UUID
	Title      string
	Note       string
	RemindAt   time.Time
	Repeat     string
	TargetType *string
	TargetID   *uuid.UUID
}

func (q *Queries) CreateReminder(ctx context.Context, arg CreateReminderParams) (Reminder, error) {
	row := q.db.QueryRow(ctx, createReminder,
		arg.ID,
		arg.GroupID,
		arg.UserID,
		arg.Title,
		arg.Note,
		arg.RemindAt,
		arg.Repeat,
		arg.TargetType,
		arg.TargetID,
	)
	var i Reminder
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Title,
		&i.Note,
		&i.RemindAt,
		&i.Repeat,
		&i.TargetType,
		&i.TargetID,
		&i.Status,
		&i.LastFiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteReminder = `-- name: DeleteReminder :execrows
DELETE FROM reminders WHERE id = $1 AND user_id = $2
`

type DeleteReminderParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteReminder(ctx context.Context, arg DeleteReminderParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteReminder, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getReminder = `-- name: GetReminder :one
SELECT id, group_id, user_id, title, note, remind_at, repeat, target_type, target_id, status, last_fired_at, created_at, updated_at FROM reminders WHERE id = $1
`

func (q *Queries) GetReminder(ctx context.Context, id uuid.UUID) (Reminder, error) {
	row := q.db.QueryRow(ctx, getReminder, id)
	var i Reminder
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Title,
		&i.Note,
		&i.RemindAt,
		&i.Repeat,
		&i.TargetType,
		&i.TargetID,
		&i.Status,
		&i.LastFiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDueReminders = `-- name: ListDueReminders :many
SELECT id, group_id, user_id, title, note, remind_at, repeat, target_type, target_id, status, last_fired_at, created_at, updated_at FROM reminders
WHERE status = 'SCHEDULED' AND remind_at <= $1::timestamptz
ORDER BY remind_at
LIMIT $2::int
`

type ListDueRemindersParams struct {
	Now time.Time
	Lim int32
}

// What the scanner owes people right now.
func (q *Queries) ListDueReminders(ctx context.Context, arg ListDueRemindersParams) ([]Reminder, error) {
	rows, err := q.db.Query(ctx, listDueReminders, arg.Now, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reminder{}
	for rows.Next() {
		var i Reminder
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.UserID,
			&i.Title,
			&i.Note,
			&i.RemindAt,
			&i.Repeat,
			&i.TargetType,
			&i.TargetID,
			&i.Status,
			&i.LastFiredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReminders = `-- name: ListReminders :many
SELECT id, group_id, user_id, title, note, remind_at, repeat, target_type, target_id, status, last_fired_at, created_at, updated_at FROM reminders
WHERE user_id = $1::uuid
  AND group_id = $2::uuid
  AND (NOT $3::boolean OR status <> 'DONE')
ORDER BY (status = 'DONE'), remind_at
LIMIT $4::int
`

type ListRemindersParams struct {
	UserID   uuid.UUID
	GroupID  uuid.UUID
	OpenOnly bool
	Lim      int32
}

// One person's own reminders: open ones first, then what is already done.
func (q *Queries) ListReminders(ctx context.Context, arg ListRemindersParams) ([]Reminder, error) {
	rows, err := q.db.Query(ctx, listReminders,
		arg.UserID,
		arg.GroupID,
		arg.OpenOnly,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reminder{}
	for rows.Next() {
		var i Reminder
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.UserID,
			&i.Title,
			&i.Note,
			&i.RemindAt,
			&i.Repeat,
			&i.TargetType,
			&i.TargetID,
			&i.Status,
			&i.LastFiredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReminder = `-- name: UpdateReminder :one
UPDATE reminders
SET title = $1, note = $2, remind_at = $3,
    repeat = $4, target_type = $5, target_id = $6,
    status = $7, last_fired_at = $8
WHERE id = $9 AND user_id = $10::uuid
RETURNING id, group_id, user_id, title, note, remind_at, repeat, target_type, target_id, status, last_fired_at, created_at, updated_at
`

type UpdateReminderParams struct {
	Title       string
	Note        string
	RemindAt    time.Time
	Repeat      string
	TargetType  *string
	TargetID    *uuid.UUID
	Status      string
	LastFiredAt *time.Time
	ID          uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) UpdateReminder(ctx context.Context, arg UpdateReminderParams) (Reminder, error) {
	row := q.db.QueryRow(ctx, updateReminder,
		arg.Title,
		arg.Note,
		arg.RemindAt,
		arg.Repeat,
		arg.TargetType,
		arg.TargetID,
		arg.Status,
		arg.LastFiredAt,
		arg.ID,
		arg.UserID,
	)
	var i Reminder
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Title,
		&i.Note,
		&i.RemindAt,
		&i.Repeat,
		&i.TargetType,
		&i.TargetID,
		&i.Status,
		&i.LastFiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
