// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedule.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createScheduleEvent = `-- name: CreateScheduleEvent :one
INSERT INTO schedule_events (id, group_id, subject_id, client_id, title, kind, starts_at, ends_at, timezone,
                             location, teacher, note, rrule, rrule_until, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $15)
RETURNING id, group_id, subject_id, client_id, title, kind, starts_at, ends_at, timezone, location, teacher, note, rrule, rrule_until, created_by, updated_by, version, created_at, updated_at, deleted_at
`

type CreateScheduleEventParams struct {
	ID         uuid.UUID
	GroupID    uuid.UUID
	SubjectID  *uuid.UUID
	ClientID   *uuid.UUID
	Title      string
	Kind       string
	StartsAt   time.Time
	EndsAt     time.Time
	Timezone   string
	Location   string
	Teacher    string
	Note       string
	Rrule      *string
	RruleUntil *time.Time
	CreatedBy  *uuid.UUID
}

func (q *Queries) CreateScheduleEvent(ctx context.Context, arg CreateScheduleEventParams) (ScheduleEvent, error) {
	row := q.db.QueryRow(ctx, createScheduleEvent,
		arg.ID,
		arg.GroupID,
		arg.SubjectID,
		arg.ClientID,
		arg.Title,
		arg.Kind,
		arg.StartsAt,
		arg.EndsAt,
		arg.Timezone,
		arg.Location,
		arg.Teacher,
		arg.Note,
		arg.Rrule,
		arg.RruleUntil,
		arg.CreatedBy,
	)
	var i ScheduleEvent
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.SubjectID,
		&i.ClientID,
		&i.Title,
		&i.Kind,
		&i.StartsAt,
		&i.EndsAt,
		&i.Timezone,
		&i.Location,
		&i.Teacher,
		&i.Note,
		&i.Rrule,
		&i.RruleUntil,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteScheduleException = `-- name: DeleteScheduleException :execrows
DELETE FROM schedule_exceptions WHERE event_id = $1 AND original_date = $2
`

type DeleteScheduleExceptionParams struct {
	EventID      uuid.UUID
	OriginalDate time.Time
}

func (q *Queries) DeleteScheduleException(ctx context.Context, arg DeleteScheduleExceptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteScheduleException, arg.EventID, arg.OriginalDate)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteScheduleExceptionsFrom = `-- name: DeleteScheduleExceptionsFrom :exec
DELETE FROM schedule_exceptions WHERE event_id = $1 AND original_date >= $2::date
`

type DeleteScheduleExceptionsFromParams struct {
	EventID  uuid.UUID
	FromDate time.Time
}

func (q *Queries) DeleteScheduleExceptionsFrom(ctx context.Context, arg DeleteScheduleExceptionsFromParams) error {
	_, err := q.db.Exec(ctx, deleteScheduleExceptionsFrom, arg.EventID, arg.FromDate)
	return err
}

const endScheduleSeries = `-- name: EndScheduleSeries :one
UPDATE schedule_events
SET rrule_until = $1::date, updated_by = $2, version = version + 1
WHERE id = $3 AND version = $4 AND deleted_at IS NULL
RETURNING id, group_id, subject_id, client_id, title, kind, starts_at, ends_at, timezone, location, teacher, note, rrule, rrule_until, created_by, updated_by, version, created_at, updated_at, deleted_at
`

type EndScheduleSeriesParams struct {
	Until     time.Time
	UpdatedBy *uuid.UUID
	ID        uuid.UUID
	Version   int32
}

func (q *Queries) EndScheduleSeries(ctx context.Context, arg EndScheduleSeriesParams) (ScheduleEvent, error) {
	row := q.db.QueryRow(ctx, endScheduleSeries,
		arg.Until,
		arg.UpdatedBy,
		arg.ID,
		arg.Version,
	)
	var i ScheduleEvent
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.SubjectID,
		&i.ClientID,
		&i.Title,
		&i.Kind,
		&i.StartsAt,
		&i.EndsAt,
		&i.Timezone,
		&i.Location,
		&i.Teacher,
		&i.Note,
		&i.Rrule,
		&i.RruleUntil,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getScheduleEvent = `-- name: GetScheduleEvent :one
SELECT id, group_id, subject_id, client_id, title, kind, starts_at, ends_at, timezone, location, teacher, note, rrule, rrule_until, created_by, updated_by, version, created_at, updated_at, deleted_at FROM schedule_events WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetScheduleEvent(ctx context.Context, id uuid.UUID) (ScheduleEvent, error) {
	row := q.db.QueryRow(ctx, getScheduleEvent, id)
	var i ScheduleEvent
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.SubjectID,
		&i.ClientID,
		&i.Title,
		&i.Kind,
		&i.StartsAt,
		&i.EndsAt,
		&i.Timezone,
		&i.Location,
		&i.Teacher,
		&i.Note,
		&i.Rrule,
		&i.RruleUntil,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getScheduleEventByClientID = `-- name: GetScheduleEventByClientID :one
SELECT id, group_id, subject_id, client_id, title, kind, starts_at, ends_at, timezone, location, teacher, note, rrule, rrule_until, created_by, updated_by, version, created_at, updated_at, deleted_at FROM schedule_events WHERE group_id = $1 AND client_id = $2 AND deleted_at IS NULL
`

type GetScheduleEventByClientIDParams struct {
	GroupID  uuid.UUID
	ClientID *uuid.UUID
}

func (q *Queries) GetScheduleEventByClientID(ctx context.Context, arg GetScheduleEventByClientIDParams) (ScheduleEvent, error) {
	row := q.db.QueryRow(ctx, getScheduleEventByClientID, arg.GroupID, arg.ClientID)
	var i ScheduleEvent
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.SubjectID,
		&i.ClientID,
		&i.Title,
		&i.Kind,
		&i.StartsAt,
		&i.EndsAt,
		&i.Timezone,
		&i.Location,
		&i.Teacher,
		&i.Note,
		&i.Rrule,
		&i.RruleUntil,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getScheduleException = `-- name: GetScheduleException :one
SELECT event_id, original_date, kind, starts_at, ends_at, location, teacher, note, updated_by, created_at, updated_at FROM schedule_exceptions WHERE event_id = $1 AND original_date = $2
`

type GetScheduleExceptionParams struct {
	EventID      uuid.UUID
	OriginalDate time.Time
}

func (q *Queries) GetScheduleException(ctx context.Context, arg GetScheduleExceptionParams) (ScheduleException, error) {
	row := q.db.QueryRow(ctx, getScheduleException, arg.EventID, arg.OriginalDate)
	var i ScheduleException
	err := row.Scan(
		&i.EventID,
		&i.OriginalDate,
		&i.Kind,
		&i.StartsAt,
		&i.EndsAt,
		&i.Location,
		&i.Teacher,
		&i.Note,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGroupScheduleEvents = `-- name: ListGroupScheduleEvents :many
SELECT id, group_id, subject_id, client_id, title, kind, starts_at, ends_at, timezone, location, teacher, note, rrule, rrule_until, created_by, updated_by, version, created_at, updated_at, deleted_at FROM schedule_events WHERE group_id = $1 AND deleted_at IS NULL ORDER BY starts_at, id
`

func (q *Queries) ListGroupScheduleEvents(ctx context.Context, groupID uuid.UUID) ([]ScheduleEvent, error) {
	rows, err := q.db.Query(ctx, listGroupScheduleEvents, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduleEvent{}
	for rows.Next() {
		var i ScheduleEvent
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.SubjectID,
			&i.ClientID,
			&i.Title,
			&i.Kind,
			&i.StartsAt,
			&i.EndsAt,
			&i.Timezone,
			&i.Location,
			&i.Teacher,
			&i.Note,
			&i.Rrule,
			&i.RruleUntil,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleEventsInWindow = `-- name: ListScheduleEventsInWindow :many
SELECT e.id, e.group_id, e.subject_id, e.client_id, e.title, e.kind, e.starts_at, e.ends_at, e.timezone, e.location, e.teacher, e.note, e.rrule, e.rrule_until, e.created_by, e.updated_by, e.version, e.created_at, e.updated_at, e.deleted_at FROM schedule_events e
WHERE e.group_id = $1 AND e.deleted_at IS NULL
  AND ((e.starts_at < $2::timestamptz
        AND ((e.rrule IS NULL AND e.ends_at > $3::timestamptz)
             OR (e.rrule IS NOT NULL
                 AND (e.rrule_until IS NULL OR e.rrule_until >= ($3::timestamptz - interval '2 days')::date))))
       OR EXISTS (SELECT 1 FROM schedule_exceptions x
                  WHERE x.event_id = e.id
                    AND x.starts_at < $2::timestamptz
                    AND x.ends_at > $3::timestamptz))
ORDER BY e.starts_at, e.id
`

type ListScheduleEventsInWindowParams struct {
	GroupID    uuid.UUID
	WindowTo   time.Time
	WindowFrom time.Time
}

// Events that may have a class overlapping [window_from, window_to): one-off
// classes inside it, series running at that time, and anything with a class
// moved into it.
func (q *Queries) ListScheduleEventsInWindow(ctx context.Context, arg ListScheduleEventsInWindowParams) ([]ScheduleEvent, error) {
	rows, err := q.db.Query(ctx, listScheduleEventsInWindow, arg.GroupID, arg.WindowTo, arg.WindowFrom)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduleEvent{}
	for rows.Next() {
		var i ScheduleEvent
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.SubjectID,
			&i.ClientID,
			&i.Title,
			&i.Kind,
			&i.StartsAt,
			&i.EndsAt,
			&i.Timezone,
			&i.Location,
			&i.Teacher,
			&i.Note,
			&i.Rrule,
			&i.RruleUntil,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleExceptions = `-- name: ListScheduleExceptions :many
SELECT event_id, original_date, kind, starts_at, ends_at, location, teacher, note, updated_by, created_at, updated_at FROM schedule_exceptions WHERE event_id = ANY ($1::uuid[]) ORDER BY event_id, original_date
`

func (q *Queries) ListScheduleExceptions(ctx context.Context, eventIds []uuid.UUID) ([]ScheduleException, error) {
	rows, err := q.db.Query(ctx, listScheduleExceptions, eventIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduleException{}
	for rows.Next() {
		var i ScheduleException
		if err := rows.Scan(
			&i.EventID,
			&i.OriginalDate,
			&i.Kind,
			&i.StartsAt,
			&i.EndsAt,
			&i.Location,
			&i.Teacher,
			&i.Note,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveScheduleExceptions = `-- name: MoveScheduleExceptions :exec
UPDATE schedule_exceptions SET event_id = $1
WHERE event_id = $2 AND original_date >= $3::date
`

type MoveScheduleExceptionsParams struct {
	ToEventID   uuid.UUID
	FromEventID uuid.UUID
	FromDate    time.Time
}

// A series split in two: changes from the split date on follow the new part.
func (q *Queries) MoveScheduleExceptions(ctx context.Context, arg MoveScheduleExceptionsParams) error {
	_, err := q.db.Exec(ctx, moveScheduleExceptions, arg.ToEventID, arg.FromEventID, arg.FromDate)
	return err
}

const softDeleteScheduleEvent = `-- name: SoftDeleteScheduleEvent :execrows
UPDATE schedule_events
SET deleted_at = $1, updated_by = $2, version = version + 1
WHERE id = $3 AND version = $4 AND deleted_at IS NULL
`

type SoftDeleteScheduleEventParams struct {
	DeletedAt *time.Time
	UpdatedBy *uuid.UUID
	ID        uuid.UUID
	Version   int32
}

func (q *Queries) SoftDeleteScheduleEvent(ctx context.Context, arg SoftDeleteScheduleEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteScheduleEvent,
		arg.DeletedAt,
		arg.UpdatedBy,
		arg.ID,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateScheduleEvent = `-- name: UpdateScheduleEvent :one
UPDATE schedule_events
SET subject_id = $3, title = $4, kind = $5, starts_at = $6, ends_at = $7, timezone = $8,
    location = $9, teacher = $10, note = $11, rrule = $12, rrule_until = $13, updated_by = $14,
    version = version + 1
WHERE id = $1 AND version = $2 AND deleted_at IS NULL
RETURNING id, group_id, subject_id, client_id, title, kind, starts_at, ends_at, timezone, location, teacher, note, rrule, rrule_until, created_by, updated_by, version, created_at, updated_at, deleted_at
`

type UpdateScheduleEventParams struct {
	ID         uuid.UUID
	Version    int32
	SubjectID  *uuid.UUID
	Title      string
	Kind       string
	StartsAt   time.Time
	EndsAt     time.Time
	Timezone   string
	Location   string
	Teacher    string
	Note       string
	Rrule      *string
	RruleUntil *time.Time
	UpdatedBy  *uuid.UUID
}

// Only when nobody changed the event since the editor loaded it.
func (q *Queries) UpdateScheduleEvent(ctx context.Context, arg UpdateScheduleEventParams) (ScheduleEvent, error) {
	row := q.db.QueryRow(ctx, updateScheduleEvent,
		arg.ID,
		arg.Version,
		arg.SubjectID,
		arg.Title,
		arg.Kind,
		arg.StartsAt,
		arg.EndsAt,
		arg.Timezone,
		arg.Location,
		arg.Teacher,
		arg.Note,
		arg.Rrule,
		arg.RruleUntil,
		arg.UpdatedBy,
	)
	var i ScheduleEvent
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.SubjectID,
		&i.ClientID,
		&i.Title,
		&i.Kind,
		&i.StartsAt,
		&i.EndsAt,
		&i.Timezone,
		&i.Location,
		&i.Teacher,
		&i.Note,
		&i.Rrule,
		&i.RruleUntil,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertScheduleException = `-- name: UpsertScheduleException :one
INSERT INTO schedule_exceptions (event_id, original_date, kind, starts_at, ends_at, location, teacher, note, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (event_id, original_date) DO UPDATE
SET kind = EXCLUDED.kind, starts_at = EXCLUDED.starts_at, ends_at = EXCLUDED.ends_at,
    location = EXCLUDED.location, teacher = EXCLUDED.teacher, note = EXCLUDED.note, updated_by = EXCLUDED.updated_by
RETURNING event_id, original_date, kind, starts_at, ends_at, location, teacher, note, updated_by, created_at, updated_at
`

type UpsertScheduleExceptionParams struct {
	EventID      uuid.UUID
	OriginalDate time.Time
	Kind         string
	StartsAt     *time.Time
	EndsAt       *time.Time
	Location     *string
	Teacher      *string
	Note         string
	UpdatedBy    *uuid.UUID
}

func (q *Queries) UpsertScheduleException(ctx context.Context, arg UpsertScheduleExceptionParams) (ScheduleException, error) {
	row := q.db.QueryRow(ctx, upsertScheduleException,
		arg.EventID,
		arg.OriginalDate,
		arg.Kind,
		arg.StartsAt,
		arg.EndsAt,
		arg.Location,
		arg.Teacher,
		arg.Note,
		arg.UpdatedBy,
	)
	var i ScheduleException
	err := row.Scan(
		&i.EventID,
		&i.OriginalDate,
		&i.Kind,
		&i.StartsAt,
		&i.EndsAt,
		&i.Location,
		&i.Teacher,
		&i.Note,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
