// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subjects.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const addSubjectAliases = `-- name: AddSubjectAliases :exec
UPDATE subjects
SET aliases = (SELECT array_agg(DISTINCT a) FROM unnest(aliases || $3::text[]) AS a)
WHERE id = $1 AND group_id = $2
`

type AddSubjectAliasesParams struct {
	ID         uuid.UUID
	GroupID    uuid.UUID
	NewAliases []string
}

func (q *Queries) AddSubjectAliases(ctx context.Context, arg AddSubjectAliasesParams) error {
	_, err := q.db.Exec(ctx, addSubjectAliases, arg.ID, arg.GroupID, arg.NewAliases)
	return err
}

const archiveSubject = `-- name: ArchiveSubject :exec
UPDATE subjects SET archived_at = now() WHERE id = $1 AND group_id = $2
`

type ArchiveSubjectParams struct {
	ID      uuid.UUID
	GroupID uuid.UUID
}

func (q *Queries) ArchiveSubject(ctx context.Context, arg ArchiveSubjectParams) error {
	_, err := q.db.Exec(ctx, archiveSubject, arg.ID, arg.GroupID)
	return err
}

const createSubject = `-- name: CreateSubject :one
INSERT INTO subjects (id, group_id, name, short_name, teacher, teacher_contact, color, semester, aliases, sort_order, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, group_id, name, short_name, teacher, teacher_contact, color, semester, aliases, sort_order, created_by, created_at, updated_at, archived_at
`

type CreateSubjectParams struct {
	ID             uuid.UUID
	GroupID        uuid.UUID
	Name           string
	ShortName      *string
	Teacher        *string
	TeacherContact *string
	Color          *string
	Semester       *string
	Aliases        []string
	SortOrder      int32
	CreatedBy      *uuid.UUID
}

func (q *Queries) CreateSubject(ctx context.Context, arg CreateSubjectParams) (Subject, error) {
	row := q.db.QueryRow(ctx, createSubject,
		arg.ID,
		arg.GroupID,
		arg.Name,
		arg.ShortName,
		arg.Teacher,
		arg.TeacherContact,
		arg.Color,
		arg.Semester,
		arg.Aliases,
		arg.SortOrder,
		arg.CreatedBy,
	)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.ShortName,
		&i.Teacher,
		&i.TeacherContact,
		&i.Color,
		&i.Semester,
		&i.Aliases,
		&i.SortOrder,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getSubject = `-- name: GetSubject :one
SELECT id, group_id, name, short_name, teacher, teacher_contact, color, semester, aliases, sort_order, created_by, created_at, updated_at, archived_at FROM subjects WHERE id = $1 AND group_id = $2
`

type GetSubjectParams struct {
	ID      uuid.UUID
	GroupID uuid.UUID
}

func (q *Queries) GetSubject(ctx context.Context, arg GetSubjectParams) (Subject, error) {
	row := q.db.QueryRow(ctx, getSubject, arg.ID, arg.GroupID)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.ShortName,
		&i.Teacher,
		&i.TeacherContact,
		&i.Color,
		&i.Semester,
		&i.Aliases,
		&i.SortOrder,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const listSubjects = `-- name: ListSubjects :many
SELECT id, group_id, name, short_name, teacher, teacher_contact, color, semester, aliases, sort_order, created_by, created_at, updated_at, archived_at FROM subjects
WHERE group_id = $1 AND ($2::boolean OR archived_at IS NULL)
ORDER BY sort_order, name
`

type ListSubjectsParams struct {
	GroupID         uuid.UUID
	IncludeArchived bool
}

func (q *Queries) ListSubjects(ctx context.Context, arg ListSubjectsParams) ([]Subject, error) {
	rows, err := q.db.Query(ctx, listSubjects, arg.GroupID, arg.IncludeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subject{}
	for rows.Next() {
		var i Subject
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Name,
			&i.ShortName,
			&i.Teacher,
			&i.TeacherContact,
			&i.Color,
			&i.Semester,
			&i.Aliases,
			&i.SortOrder,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreSubject = `-- name: RestoreSubject :exec
UPDATE subjects SET archived_at = NULL WHERE id = $1 AND group_id = $2
`

type RestoreSubjectParams struct {
	ID      uuid.UUID
	GroupID uuid.UUID
}

func (q *Queries) RestoreSubject(ctx context.Context, arg RestoreSubjectParams) error {
	_, err := q.db.Exec(ctx, restoreSubject, arg.ID, arg.GroupID)
	return err
}

const updateSubject = `-- name: UpdateSubject :one
UPDATE subjects
SET name = $3, short_name = $4, teacher = $5, teacher_contact = $6, color = $7, semester = $8, aliases = $9, sort_order = $10
WHERE id = $1 AND group_id = $2
RETURNING id, group_id, name, short_name, teacher, teacher_contact, color, semester, aliases, sort_order, created_by, created_at, updated_at, archived_at
`

type UpdateSubjectParams struct {
	ID             uuid.UUID
	GroupID        uuid.UUID
	Name           string
	ShortName      *string
	Teacher        *string
	TeacherContact *string
	Color          *string
	Semester       *string
	Aliases        []string
	SortOrder      int32
}

func (q *Queries) UpdateSubject(ctx context.Context, arg UpdateSubjectParams) (Subject, error) {
	row := q.db.QueryRow(ctx, updateSubject,
		arg.ID,
		arg.GroupID,
		arg.Name,
		arg.ShortName,
		arg.Teacher,
		arg.TeacherContact,
		arg.Color,
		arg.Semester,
		arg.Aliases,
		arg.SortOrder,
	)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.ShortName,
		&i.Teacher,
		&i.TeacherContact,
		&i.Color,
		&i.Semester,
		&i.Aliases,
		&i.SortOrder,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}
