// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createTag = `-- name: CreateTag :one
INSERT INTO tags (id, group_id, name, slug, color, kind, subject_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, group_id, name, slug, color, kind, subject_id, created_at, updated_at
`

type CreateTagParams struct {
	ID        uuid.UUID
	GroupID   uuid.UUID
	Name      string
	Slug      string
	Color     *string
	Kind      string
	SubjectID *uuid.UUID
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag,
		arg.ID,
		arg.GroupID,
		arg.Name,
		arg.Slug,
		arg.Color,
		arg.Kind,
		arg.SubjectID,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.Slug,
		&i.Color,
		&i.Kind,
		&i.SubjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = $1 AND group_id = $2 AND kind <> 'SUBJECT'
`

type DeleteTagParams struct {
	ID      uuid.UUID
	GroupID uuid.UUID
}

func (q *Queries) DeleteTag(ctx context.Context, arg DeleteTagParams) error {
	_, err := q.db.Exec(ctx, deleteTag, arg.ID, arg.GroupID)
	return err
}

const getTag = `-- name: GetTag :one
SELECT id, group_id, name, slug, color, kind, subject_id, created_at, updated_at FROM tags WHERE id = $1 AND group_id = $2
`

type GetTagParams struct {
	ID      uuid.UUID
	GroupID uuid.UUID
}

func (q *Queries) GetTag(ctx context.Context, arg GetTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, getTag, arg.ID, arg.GroupID)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.Slug,
		&i.Color,
		&i.Kind,
		&i.SubjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTagBySlug = `-- name: GetTagBySlug :one
SELECT id, group_id, name, slug, color, kind, subject_id, created_at, updated_at FROM tags WHERE group_id = $1 AND slug = $2
`

type GetTagBySlugParams struct {
	GroupID uuid.UUID
	Slug    string
}

func (q *Queries) GetTagBySlug(ctx context.Context, arg GetTagBySlugParams) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagBySlug, arg.GroupID, arg.Slug)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.Slug,
		&i.Color,
		&i.Kind,
		&i.SubjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTagBySubject = `-- name: GetTagBySubject :one
SELECT id, group_id, name, slug, color, kind, subject_id, created_at, updated_at FROM tags WHERE subject_id = $1
`

func (q *Queries) GetTagBySubject(ctx context.Context, subjectID *uuid.UUID) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagBySubject, subjectID)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.Slug,
		&i.Color,
		&i.Kind,
		&i.SubjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTags = `-- name: ListTags :many
SELECT id, group_id, name, slug, color, kind, subject_id, created_at, updated_at FROM tags WHERE group_id = $1 ORDER BY kind, name
`

func (q *Queries) ListTags(ctx context.Context, groupID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTags, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Name,
			&i.Slug,
			&i.Color,
			&i.Kind,
			&i.SubjectID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTag = `-- name: UpdateTag :one
UPDATE tags SET name = $3, slug = $4, color = $5 WHERE id = $1 AND group_id = $2 RETURNING id, group_id, name, slug, color, kind, subject_id, created_at, updated_at
`

type UpdateTagParams struct {
	ID      uuid.UUID
	GroupID uuid.UUID
	Name    string
	Slug    string
	Color   *string
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, updateTag,
		arg.ID,
		arg.GroupID,
		arg.Name,
		arg.Slug,
		arg.Color,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.Slug,
		&i.Color,
		&i.Kind,
		&i.SubjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
