// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addTaskAttachment = `-- name: AddTaskAttachment :exec
INSERT INTO task_attachments (task_id, material_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddTaskAttachmentParams struct {
	TaskID     uuid.UUID
	MaterialID uuid.UUID
}

func (q *Queries) AddTaskAttachment(ctx context.Context, arg AddTaskAttachmentParams) error {
	_, err := q.db.Exec(ctx, addTaskAttachment, arg.TaskID, arg.MaterialID)
	return err
}

const countTasks = `-- name: CountTasks :one
SELECT
  count(*) FILTER (WHERE t.status = 'TODO')::int                    AS todo_count,
  count(*) FILTER (WHERE t.status = 'IN_PROGRESS')::int             AS in_progress_count,
  count(*) FILTER (WHERE t.status = 'IN_REVIEW')::int               AS in_review_count,
  count(*) FILTER (WHERE t.status = 'DONE')::int                    AS done_count,
  count(*) FILTER (WHERE t.status = 'CANCELLED')::int               AS cancelled_count,
  count(*) FILTER (WHERE t.status NOT IN ('DONE', 'CANCELLED'))::int AS open_count,
  count(*) FILTER (WHERE t.status NOT IN ('DONE', 'CANCELLED')
                     AND t.due_at IS NOT NULL AND t.due_at < $1::timestamptz)::int AS overdue_count,
  count(*) FILTER (WHERE t.status NOT IN ('DONE', 'CANCELLED')
                     AND t.due_at IS NOT NULL AND t.due_at >= $1::timestamptz
                     AND t.due_at <= $2::timestamptz)::int AS due_soon_count,
  count(*) FILTER (WHERE t.status NOT IN ('DONE', 'CANCELLED')
                     AND (t.created_by = $3 OR t.assign_mode = 'ALL'
                          OR EXISTS (SELECT 1 FROM task_assignments a WHERE a.task_id = t.id AND a.user_id = $3))
                     AND NOT EXISTS (SELECT 1 FROM task_assignments a WHERE a.task_id = t.id
                                       AND a.user_id = $3 AND a.status IN ('DONE', 'CANCELLED')))::int AS mine_count
FROM tasks t
WHERE t.group_id = $4
  AND t.deleted_at IS NULL
  AND (t.visibility = 'GROUP' OR t.created_by = $3)
`

type CountTasksParams struct {
	Now           time.Time
	DueSoonBefore time.Time
	ActorID       *uuid.UUID
	GroupID       uuid.UUID
}

type CountTasksRow struct {
	TodoCount       int32
	InProgressCount int32
	InReviewCount   int32
	DoneCount       int32
	CancelledCount  int32
	OpenCount       int32
	OverdueCount    int32
	DueSoonCount    int32
	MineCount       int32
}

func (q *Queries) CountTasks(ctx context.Context, arg CountTasksParams) (CountTasksRow, error) {
	row := q.db.QueryRow(ctx, countTasks,
		arg.Now,
		arg.DueSoonBefore,
		arg.ActorID,
		arg.GroupID,
	)
	var i CountTasksRow
	err := row.Scan(
		&i.TodoCount,
		&i.InProgressCount,
		&i.InReviewCount,
		&i.DoneCount,
		&i.CancelledCount,
		&i.OpenCount,
		&i.OverdueCount,
		&i.DueSoonCount,
		&i.MineCount,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (id, group_id, subject_id, created_by, client_id, title, description, kind, status,
                   priority, assign_mode, visibility, due_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, group_id, subject_id, created_by, client_id, title, description, kind, status, priority, assign_mode, visibility, due_at, notified_offsets, pinned_by, pinned_at, completed_at, created_at, updated_at, deleted_at
`

type CreateTaskParams struct {
	ID          uuid.UUID
	GroupID     uuid.UUID
	SubjectID   *uuid.UUID
	CreatedBy   *uuid.UUID
	ClientID    *uuid.UUID
	Title       string
	Description string
	Kind        string
	Status      string
	Priority    string
	AssignMode  string
	Visibility  string
	DueAt       *time.Time
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ID,
		arg.GroupID,
		arg.SubjectID,
		arg.CreatedBy,
		arg.ClientID,
		arg.Title,
		arg.Description,
		arg.Kind,
		arg.Status,
		arg.Priority,
		arg.AssignMode,
		arg.Visibility,
		arg.DueAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.SubjectID,
		&i.CreatedBy,
		&i.ClientID,
		&i.Title,
		&i.Description,
		&i.Kind,
		&i.Status,
		&i.Priority,
		&i.AssignMode,
		&i.Visibility,
		&i.DueAt,
		&i.NotifiedOffsets,
		&i.PinnedBy,
		&i.PinnedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteTaskAssignments = `-- name: DeleteTaskAssignments :exec
DELETE FROM task_assignments
WHERE task_id = $1 AND NOT (user_id = ANY ($2::uuid[]))
`

type DeleteTaskAssignmentsParams struct {
	TaskID  uuid.UUID
	UserIds []uuid.UUID
}

func (q *Queries) DeleteTaskAssignments(ctx context.Context, arg DeleteTaskAssignmentsParams) error {
	_, err := q.db.Exec(ctx, deleteTaskAssignments, arg.TaskID, arg.UserIds)
	return err
}

const deleteTaskAttachments = `-- name: DeleteTaskAttachments :exec
DELETE FROM task_attachments
WHERE task_id = $1 AND NOT (material_id = ANY ($2::uuid[]))
`

type DeleteTaskAttachmentsParams struct {
	TaskID      uuid.UUID
	MaterialIds []uuid.UUID
}

func (q *Queries) DeleteTaskAttachments(ctx context.Context, arg DeleteTaskAttachmentsParams) error {
	_, err := q.db.Exec(ctx, deleteTaskAttachments, arg.TaskID, arg.MaterialIds)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, group_id, subject_id, created_by, client_id, title, description, kind, status, priority, assign_mode, visibility, due_at, notified_offsets, pinned_by, pinned_at, completed_at, created_at, updated_at, deleted_at FROM tasks WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTask(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.SubjectID,
		&i.CreatedBy,
		&i.ClientID,
		&i.Title,
		&i.Description,
		&i.Kind,
		&i.Status,
		&i.Priority,
		&i.AssignMode,
		&i.Visibility,
		&i.DueAt,
		&i.NotifiedOffsets,
		&i.PinnedBy,
		&i.PinnedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTaskByClientID = `-- name: GetTaskByClientID :one
SELECT id, group_id, subject_id, created_by, client_id, title, description, kind, status, priority, assign_mode, visibility, due_at, notified_offsets, pinned_by, pinned_at, completed_at, created_at, updated_at, deleted_at FROM tasks WHERE group_id = $1 AND client_id = $2 AND deleted_at IS NULL
`

type GetTaskByClientIDParams struct {
	GroupID  uuid.UUID
	ClientID *uuid.UUID
}

func (q *Queries) GetTaskByClientID(ctx context.Context, arg GetTaskByClientIDParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByClientID, arg.GroupID, arg.ClientID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.SubjectID,
		&i.CreatedBy,
		&i.ClientID,
		&i.Title,
		&i.Description,
		&i.Kind,
		&i.Status,
		&i.Priority,
		&i.AssignMode,
		&i.Visibility,
		&i.DueAt,
		&i.NotifiedOffsets,
		&i.PinnedBy,
		&i.PinnedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTaskView = `-- name: GetTaskView :one
SELECT t.id, t.group_id, t.subject_id, t.created_by, t.client_id, t.title, t.description, t.kind, t.status, t.priority, t.assign_mode, t.visibility, t.due_at, t.notified_offsets, t.pinned_by, t.pinned_at, t.completed_at, t.created_at, t.updated_at, t.deleted_at,
       COALESCE((SELECT a.status FROM task_assignments a WHERE a.task_id = t.id AND a.user_id = $1), '')::text AS my_status,
       COALESCE((SELECT array_agg(a.user_id ORDER BY a.created_at) FROM task_assignments a WHERE a.task_id = t.id), '{}')::uuid[] AS assignee_ids,
       COALESCE((SELECT array_agg(att.material_id ORDER BY att.created_at) FROM task_attachments att WHERE att.task_id = t.id), '{}')::uuid[] AS attachment_ids,
       (SELECT count(*) FROM task_assignments a WHERE a.task_id = t.id AND a.status = 'DONE')::int AS done_count,
       -- A task for everybody is handed to every active member, not just to
       -- those who already marked their progress.
       (CASE WHEN t.assign_mode = 'ALL'
             THEN (SELECT count(*) FROM memberships m WHERE m.group_id = t.group_id AND m.status = 'ACTIVE')
             ELSE (SELECT count(*) FROM task_assignments a WHERE a.task_id = t.id)
        END)::int AS assigned_count
FROM tasks t
WHERE t.id = $2 AND t.deleted_at IS NULL
`

type GetTaskViewParams struct {
	ActorID uuid.UUID
	ID      uuid.UUID
}

type GetTaskViewRow struct {
	Task          Task
	MyStatus      string
	AssigneeIds   []uuid.UUID
	AttachmentIds []uuid.UUID
	DoneCount     int32
	AssignedCount int32
}

func (q *Queries) GetTaskView(ctx context.Context, arg GetTaskViewParams) (GetTaskViewRow, error) {
	row := q.db.QueryRow(ctx, getTaskView, arg.ActorID, arg.ID)
	var i GetTaskViewRow
	err := row.Scan(
		&i.Task.ID,
		&i.Task.GroupID,
		&i.Task.SubjectID,
		&i.Task.CreatedBy,
		&i.Task.ClientID,
		&i.Task.Title,
		&i.Task.Description,
		&i.Task.Kind,
		&i.Task.Status,
		&i.Task.Priority,
		&i.Task.AssignMode,
		&i.Task.Visibility,
		&i.Task.DueAt,
		&i.Task.NotifiedOffsets,
		&i.Task.PinnedBy,
		&i.Task.PinnedAt,
		&i.Task.CompletedAt,
		&i.Task.CreatedAt,
		&i.Task.UpdatedAt,
		&i.Task.DeletedAt,
		&i.MyStatus,
		&i.AssigneeIds,
		&i.AttachmentIds,
		&i.DoneCount,
		&i.AssignedCount,
	)
	return i, err
}

const insertTaskAssignments = `-- name: InsertTaskAssignments :exec
INSERT INTO task_assignments (task_id, user_id)
SELECT $1::uuid, unnest($2::uuid[])
ON CONFLICT DO NOTHING
`

type InsertTaskAssignmentsParams struct {
	TaskID  uuid.UUID
	UserIds []uuid.UUID
}

func (q *Queries) InsertTaskAssignments(ctx context.Context, arg InsertTaskAssignmentsParams) error {
	_, err := q.db.Exec(ctx, insertTaskAssignments, arg.TaskID, arg.UserIds)
	return err
}

const insertTaskAttachments = `-- name: InsertTaskAttachments :exec
INSERT INTO task_attachments (task_id, material_id)
SELECT $1::uuid, m.id
FROM materials m
WHERE m.id = ANY ($2::uuid[])
  AND m.group_id = $3
  AND m.status <> 'DELETED'
  -- A file kept in another task stays there (D43).
  AND (m.task_id IS NULL OR m.task_id = $1::uuid)
ON CONFLICT DO NOTHING
`

type InsertTaskAttachmentsParams struct {
	TaskID      uuid.UUID
	MaterialIds []uuid.UUID
	GroupID     uuid.UUID
}

func (q *Queries) InsertTaskAttachments(ctx context.Context, arg InsertTaskAttachmentsParams) error {
	_, err := q.db.Exec(ctx, insertTaskAttachments, arg.TaskID, arg.MaterialIds, arg.GroupID)
	return err
}

const listTaskAssignments = `-- name: ListTaskAssignments :many
SELECT task_id, user_id, status, completed_at, created_at, updated_at FROM task_assignments WHERE task_id = $1 ORDER BY created_at
`

func (q *Queries) ListTaskAssignments(ctx context.Context, taskID uuid.UUID) ([]TaskAssignment, error) {
	rows, err := q.db.Query(ctx, listTaskAssignments, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskAssignment{}
	for rows.Next() {
		var i TaskAssignment
		if err := rows.Scan(
			&i.TaskID,
			&i.UserID,
			&i.Status,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskDueReminders = `-- name: ListTaskDueReminders :many
SELECT t.id, t.group_id, t.subject_id, t.created_by, t.client_id, t.title, t.description, t.kind, t.status, t.priority, t.assign_mode, t.visibility, t.due_at, t.notified_offsets, t.pinned_by, t.pinned_at, t.completed_at, t.created_at, t.updated_at, t.deleted_at, o.offset_minutes::int AS offset_minutes
FROM tasks t
JOIN unnest($1::int[]) AS o (offset_minutes) ON true
WHERE t.deleted_at IS NULL
  AND t.status NOT IN ('DONE', 'CANCELLED')
  AND t.due_at IS NOT NULL
  AND t.due_at - make_interval(mins => o.offset_minutes) <= $2::timestamptz
  -- Deadlines long past are not announced (a task imported after the fact).
  AND t.due_at >= $2::timestamptz - make_interval(mins => $3::int)
  AND NOT (o.offset_minutes = ANY (t.notified_offsets))
ORDER BY t.due_at, o.offset_minutes
LIMIT $4
`

type ListTaskDueRemindersParams struct {
	Offsets      []int32
	Now          time.Time
	GraceMinutes int32
	MaxRows      int32
}

type ListTaskDueRemindersRow struct {
	Task          Task
	OffsetMinutes int32
}

// Tasks whose deadline reminder is due: one row per offset that fired.
func (q *Queries) ListTaskDueReminders(ctx context.Context, arg ListTaskDueRemindersParams) ([]ListTaskDueRemindersRow, error) {
	rows, err := q.db.Query(ctx, listTaskDueReminders,
		arg.Offsets,
		arg.Now,
		arg.GraceMinutes,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskDueRemindersRow{}
	for rows.Next() {
		var i ListTaskDueRemindersRow
		if err := rows.Scan(
			&i.Task.ID,
			&i.Task.GroupID,
			&i.Task.SubjectID,
			&i.Task.CreatedBy,
			&i.Task.ClientID,
			&i.Task.Title,
			&i.Task.Description,
			&i.Task.Kind,
			&i.Task.Status,
			&i.Task.Priority,
			&i.Task.AssignMode,
			&i.Task.Visibility,
			&i.Task.DueAt,
			&i.Task.NotifiedOffsets,
			&i.Task.PinnedBy,
			&i.Task.PinnedAt,
			&i.Task.CompletedAt,
			&i.Task.CreatedAt,
			&i.Task.UpdatedAt,
			&i.Task.DeletedAt,
			&i.OffsetMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT t.id, t.group_id, t.subject_id, t.created_by, t.client_id, t.title, t.description, t.kind, t.status, t.priority, t.assign_mode, t.visibility, t.due_at, t.notified_offsets, t.pinned_by, t.pinned_at, t.completed_at, t.created_at, t.updated_at, t.deleted_at,
       COALESCE((SELECT a.status FROM task_assignments a WHERE a.task_id = t.id AND a.user_id = $1), '')::text AS my_status,
       COALESCE((SELECT array_agg(a.user_id ORDER BY a.created_at) FROM task_assignments a WHERE a.task_id = t.id), '{}')::uuid[] AS assignee_ids,
       COALESCE((SELECT array_agg(att.material_id ORDER BY att.created_at) FROM task_attachments att WHERE att.task_id = t.id), '{}')::uuid[] AS attachment_ids,
       (SELECT count(*) FROM task_assignments a WHERE a.task_id = t.id AND a.status = 'DONE')::int AS done_count,
       -- A task for everybody is handed to every active member, not just to
       -- those who already marked their progress.
       (CASE WHEN t.assign_mode = 'ALL'
             THEN (SELECT count(*) FROM memberships m WHERE m.group_id = t.group_id AND m.status = 'ACTIVE')
             ELSE (SELECT count(*) FROM task_assignments a WHERE a.task_id = t.id)
        END)::int AS assigned_count
FROM tasks t
WHERE t.group_id = $2
  AND t.deleted_at IS NULL
  -- Private tasks belong to their author only.
  AND (t.visibility = 'GROUP' OR t.created_by = $1)
  AND ($3::uuid IS NULL OR t.subject_id = $3::uuid)
  AND (NOT $4::boolean OR t.subject_id IS NULL)
  AND ($5::text IS NULL OR t.kind = $5::text)
  AND (cardinality($6::text[]) = 0 OR t.status = ANY ($6::text[]))
  AND (NOT $7::boolean OR t.status NOT IN ('DONE', 'CANCELLED'))
  AND (NOT $8::boolean
       OR (t.status NOT IN ('DONE', 'CANCELLED') AND t.due_at IS NOT NULL AND t.due_at < $9::timestamptz))
  AND ($10::timestamptz IS NULL OR (t.due_at IS NOT NULL AND t.due_at <= $10::timestamptz))
  -- "Mine": created by me, handed to me, or handed to everybody.
  AND (NOT $11::boolean
       OR t.created_by = $1
       OR t.assign_mode = 'ALL'
       OR EXISTS (SELECT 1 FROM task_assignments a WHERE a.task_id = t.id AND a.user_id = $1))
  AND ($12::text IS NULL
       OR t.title ILIKE '%' || $12::text || '%' ESCAPE '\'
       OR t.description ILIKE '%' || $12::text || '%' ESCAPE '\')
ORDER BY (t.pinned_at IS NULL), t.pinned_at DESC, (t.due_at IS NULL), t.due_at, t.created_at DESC, t.id
LIMIT $13
`

type ListTasksParams struct {
	ActorID     uuid.UUID
	GroupID     uuid.UUID
	SubjectID   *uuid.UUID
	NoSubject   bool
	Kind        *string
	Statuses    []string
	OpenOnly    bool
	Overdue     bool
	Now         time.Time
	DueBefore   *time.Time
	Mine        bool
	LikePattern *string
	MaxRows     int32
}

type ListTasksRow struct {
	Task          Task
	MyStatus      string
	AssigneeIds   []uuid.UUID
	AttachmentIds []uuid.UUID
	DoneCount     int32
	AssignedCount int32
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]ListTasksRow, error) {
	rows, err := q.db.Query(ctx, listTasks,
		arg.ActorID,
		arg.GroupID,
		arg.SubjectID,
		arg.NoSubject,
		arg.Kind,
		arg.Statuses,
		arg.OpenOnly,
		arg.Overdue,
		arg.Now,
		arg.DueBefore,
		arg.Mine,
		arg.LikePattern,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksRow{}
	for rows.Next() {
		var i ListTasksRow
		if err := rows.Scan(
			&i.Task.ID,
			&i.Task.GroupID,
			&i.Task.SubjectID,
			&i.Task.CreatedBy,
			&i.Task.ClientID,
			&i.Task.Title,
			&i.Task.Description,
			&i.Task.Kind,
			&i.Task.Status,
			&i.Task.Priority,
			&i.Task.AssignMode,
			&i.Task.Visibility,
			&i.Task.DueAt,
			&i.Task.NotifiedOffsets,
			&i.Task.PinnedBy,
			&i.Task.PinnedAt,
			&i.Task.CompletedAt,
			&i.Task.CreatedAt,
			&i.Task.UpdatedAt,
			&i.Task.DeletedAt,
			&i.MyStatus,
			&i.AssigneeIds,
			&i.AttachmentIds,
			&i.DoneCount,
			&i.AssignedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTaskNotified = `-- name: MarkTaskNotified :exec
UPDATE tasks
SET notified_offsets = (SELECT array_agg(DISTINCT x) FROM unnest(notified_offsets || $1::integer[]) AS x)
WHERE id = $2
`

type MarkTaskNotifiedParams struct {
	Offsets []int32
	ID      uuid.UUID
}

func (q *Queries) MarkTaskNotified(ctx context.Context, arg MarkTaskNotifiedParams) error {
	_, err := q.db.Exec(ctx, markTaskNotified, arg.Offsets, arg.ID)
	return err
}

const setTaskPinned = `-- name: SetTaskPinned :one
UPDATE tasks
SET pinned_by = $1::uuid, pinned_at = $2::timestamptz
WHERE id = $3 AND deleted_at IS NULL
RETURNING id, group_id, subject_id, created_by, client_id, title, description, kind, status, priority, assign_mode, visibility, due_at, notified_offsets, pinned_by, pinned_at, completed_at, created_at, updated_at, deleted_at
`

type SetTaskPinnedParams struct {
	PinnedBy *uuid.UUID
	PinnedAt *time.Time
	ID       uuid.UUID
}

func (q *Queries) SetTaskPinned(ctx context.Context, arg SetTaskPinnedParams) (Task, error) {
	row := q.db.QueryRow(ctx, setTaskPinned, arg.PinnedBy, arg.PinnedAt, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.SubjectID,
		&i.CreatedBy,
		&i.ClientID,
		&i.Title,
		&i.Description,
		&i.Kind,
		&i.Status,
		&i.Priority,
		&i.AssignMode,
		&i.Visibility,
		&i.DueAt,
		&i.NotifiedOffsets,
		&i.PinnedBy,
		&i.PinnedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const setTaskStatus = `-- name: SetTaskStatus :one
UPDATE tasks
SET status = $1, completed_at = $2::timestamptz
WHERE id = $3 AND deleted_at IS NULL
RETURNING id, group_id, subject_id, created_by, client_id, title, description, kind, status, priority, assign_mode, visibility, due_at, notified_offsets, pinned_by, pinned_at, completed_at, created_at, updated_at, deleted_at
`

type SetTaskStatusParams struct {
	Status      string
	CompletedAt *time.Time
	ID          uuid.UUID
}

func (q *Queries) SetTaskStatus(ctx context.Context, arg SetTaskStatusParams) (Task, error) {
	row := q.db.QueryRow(ctx, setTaskStatus, arg.Status, arg.CompletedAt, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.SubjectID,
		&i.CreatedBy,
		&i.ClientID,
		&i.Title,
		&i.Description,
		&i.Kind,
		&i.Status,
		&i.Priority,
		&i.AssignMode,
		&i.Visibility,
		&i.DueAt,
		&i.NotifiedOffsets,
		&i.PinnedBy,
		&i.PinnedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteTask = `-- name: SoftDeleteTask :exec
UPDATE tasks SET deleted_at = $1::timestamptz WHERE id = $2 AND deleted_at IS NULL
`

type SoftDeleteTaskParams struct {
	DeletedAt time.Time
	ID        uuid.UUID
}

func (q *Queries) SoftDeleteTask(ctx context.Context, arg SoftDeleteTaskParams) error {
	_, err := q.db.Exec(ctx, softDeleteTask, arg.DeletedAt, arg.ID)
	return err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET subject_id = $1::uuid,
    title = $2,
    description = $3,
    kind = $4,
    priority = $5,
    assign_mode = $6,
    visibility = $7,
    due_at = $8::timestamptz,
    notified_offsets = CASE WHEN $9::boolean THEN '{}'::integer[] ELSE notified_offsets END
WHERE id = $10 AND deleted_at IS NULL
RETURNING id, group_id, subject_id, created_by, client_id, title, description, kind, status, priority, assign_mode, visibility, due_at, notified_offsets, pinned_by, pinned_at, completed_at, created_at, updated_at, deleted_at
`

type UpdateTaskParams struct {
	SubjectID     *uuid.UUID
	Title         string
	Description   string
	Kind          string
	Priority      string
	AssignMode    string
	Visibility    string
	DueAt         *time.Time
	ResetNotified bool
	ID            uuid.UUID
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.SubjectID,
		arg.Title,
		arg.Description,
		arg.Kind,
		arg.Priority,
		arg.AssignMode,
		arg.Visibility,
		arg.DueAt,
		arg.ResetNotified,
		arg.ID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.SubjectID,
		&i.CreatedBy,
		&i.ClientID,
		&i.Title,
		&i.Description,
		&i.Kind,
		&i.Status,
		&i.Priority,
		&i.AssignMode,
		&i.Visibility,
		&i.DueAt,
		&i.NotifiedOffsets,
		&i.PinnedBy,
		&i.PinnedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertTaskAssignmentStatus = `-- name: UpsertTaskAssignmentStatus :one
INSERT INTO task_assignments (task_id, user_id, status, completed_at)
VALUES ($1, $2, $3, $4::timestamptz)
ON CONFLICT (task_id, user_id) DO UPDATE
SET status = EXCLUDED.status, completed_at = EXCLUDED.completed_at
RETURNING task_id, user_id, status, completed_at, created_at, updated_at
`

type UpsertTaskAssignmentStatusParams struct {
	TaskID      uuid.UUID
	UserID      uuid.UUID
	Status      string
	CompletedAt *time.Time
}

func (q *Queries) UpsertTaskAssignmentStatus(ctx context.Context, arg UpsertTaskAssignmentStatusParams) (TaskAssignment, error) {
	row := q.db.QueryRow(ctx, upsertTaskAssignmentStatus,
		arg.TaskID,
		arg.UserID,
		arg.Status,
		arg.CompletedAt,
	)
	var i TaskAssignment
	err := row.Scan(
		&i.TaskID,
		&i.UserID,
		&i.Status,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
