// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: uploads.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const completeUpload = `-- name: CompleteUpload :execrows
UPDATE uploads SET status = 'COMPLETED', material_id = $2, completed_at = now()
WHERE id = $1 AND status = 'PENDING'
`

type CompleteUploadParams struct {
	ID         uuid.UUID
	MaterialID *uuid.UUID
}

func (q *Queries) CompleteUpload(ctx context.Context, arg CompleteUploadParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeUpload, arg.ID, arg.MaterialID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createUpload = `-- name: CreateUpload :one
INSERT INTO uploads (id, group_id, user_id, storage, storage_key, file_name, mime, size_bytes, meta, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, group_id, user_id, storage, storage_key, file_name, mime, size_bytes, meta, status, material_id, expires_at, completed_at, created_at
`

type CreateUploadParams struct {
	ID         uuid.UUID
	GroupID    uuid.UUID
	UserID     uuid.UUID
	Storage    string
	StorageKey string
	FileName   string
	Mime       string
	SizeBytes  int64
	Meta       []byte
	ExpiresAt  time.Time
}

func (q *Queries) CreateUpload(ctx context.Context, arg CreateUploadParams) (Upload, error) {
	row := q.db.QueryRow(ctx, createUpload,
		arg.ID,
		arg.GroupID,
		arg.UserID,
		arg.Storage,
		arg.StorageKey,
		arg.FileName,
		arg.Mime,
		arg.SizeBytes,
		arg.Meta,
		arg.ExpiresAt,
	)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Storage,
		&i.StorageKey,
		&i.FileName,
		&i.Mime,
		&i.SizeBytes,
		&i.Meta,
		&i.Status,
		&i.MaterialID,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUpload = `-- name: GetUpload :one
SELECT id, group_id, user_id, storage, storage_key, file_name, mime, size_bytes, meta, status, material_id, expires_at, completed_at, created_at FROM uploads WHERE id = $1
`

func (q *Queries) GetUpload(ctx context.Context, id uuid.UUID) (Upload, error) {
	row := q.db.QueryRow(ctx, getUpload, id)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Storage,
		&i.StorageKey,
		&i.FileName,
		&i.Mime,
		&i.SizeBytes,
		&i.Meta,
		&i.Status,
		&i.MaterialID,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listExpiredUploads = `-- name: ListExpiredUploads :many
SELECT id, group_id, user_id, storage, storage_key, file_name, mime, size_bytes, meta, status, material_id, expires_at, completed_at, created_at FROM uploads WHERE status = 'PENDING' AND expires_at < $1 ORDER BY expires_at LIMIT $2
`

type ListExpiredUploadsParams struct {
	ExpiresAt time.Time
	Limit     int32
}

func (q *Queries) ListExpiredUploads(ctx context.Context, arg ListExpiredUploadsParams) ([]Upload, error) {
	rows, err := q.db.Query(ctx, listExpiredUploads, arg.ExpiresAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Upload{}
	for rows.Next() {
		var i Upload
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.UserID,
			&i.Storage,
			&i.StorageKey,
			&i.FileName,
			&i.Mime,
			&i.SizeBytes,
			&i.Meta,
			&i.Status,
			&i.MaterialID,
			&i.ExpiresAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUploadExpired = `-- name: MarkUploadExpired :exec
UPDATE uploads SET status = 'EXPIRED' WHERE id = $1 AND status = 'PENDING'
`

func (q *Queries) MarkUploadExpired(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markUploadExpired, id)
	return err
}
