// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, name, email, password_hash, locale, timezone, secured_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, email, password_hash, locale, timezone, avatar_key, global_role, settings, secured_at, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	ID           uuid.UUID
	Name         string
	Email        *string
	PasswordHash *string
	Locale       string
	Timezone     string
	SecuredAt    *time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Locale,
		arg.Timezone,
		arg.SecuredAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Locale,
		&i.Timezone,
		&i.AvatarKey,
		&i.GlobalRole,
		&i.Settings,
		&i.SecuredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password_hash, locale, timezone, avatar_key, global_role, settings, secured_at, created_at, updated_at, deleted_at FROM users WHERE lower(email) = lower($1) AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Locale,
		&i.Timezone,
		&i.AvatarKey,
		&i.GlobalRole,
		&i.Settings,
		&i.SecuredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, password_hash, locale, timezone, avatar_key, global_role, settings, secured_at, created_at, updated_at, deleted_at FROM users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Locale,
		&i.Timezone,
		&i.AvatarKey,
		&i.GlobalRole,
		&i.Settings,
		&i.SecuredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const markUserSecured = `-- name: MarkUserSecured :exec
UPDATE users SET secured_at = COALESCE(secured_at, now()) WHERE id = $1
`

func (q *Queries) MarkUserSecured(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markUserSecured, id)
	return err
}

const setUserCredentials = `-- name: SetUserCredentials :one
UPDATE users
SET email = COALESCE($2, email),
    password_hash = COALESCE($3, password_hash),
    secured_at = COALESCE(secured_at, now())
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, email, password_hash, locale, timezone, avatar_key, global_role, settings, secured_at, created_at, updated_at, deleted_at
`

type SetUserCredentialsParams struct {
	ID           uuid.UUID
	Email        *string
	PasswordHash *string
}

func (q *Queries) SetUserCredentials(ctx context.Context, arg SetUserCredentialsParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserCredentials, arg.ID, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Locale,
		&i.Timezone,
		&i.AvatarKey,
		&i.GlobalRole,
		&i.Settings,
		&i.SecuredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users SET deleted_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET name = $2, locale = $3, timezone = $4, settings = $5
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, email, password_hash, locale, timezone, avatar_key, global_role, settings, secured_at, created_at, updated_at, deleted_at
`

type UpdateUserProfileParams struct {
	ID       uuid.UUID
	Name     string
	Locale   string
	Timezone string
	Settings []byte
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.Name,
		arg.Locale,
		arg.Timezone,
		arg.Settings,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Locale,
		&i.Timezone,
		&i.AvatarKey,
		&i.GlobalRole,
		&i.Settings,
		&i.SecuredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
